### ISSUE TITLE
[utilities.widths] Variable name and sensible defaults

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/inuitcss#101]
@inuitcss/core 

Fractions are really powerful and foremost intuitive. It's the main reason that made me preach inuit's `layout` + `widths` (and its precursor [csswizardry-grids](https://github.com/csswizardry/csswizardry-grids/blob/master/csswizardry-grids.scss)) as the "last grid you'll ever need". 

Everyone gets fractions. "One half" (`.u-1/2`) of a container is always one half of the container. `.u-6/12` is not that intuitive in its intent.. 

Chunk of code like this:

```html
<div class="u-1/3 u-1/2@mobile">
```
is much more clear than:
```html
<div class="u-4/12 u-6/12@mobile">
```

Also, it's far easier to think in fractions than in columns.

Having said all that, I have two questions here:

1.  Should we rename `$inuit-columns` to `$inuit-fractions` (or something better)? Also, should all mentions of "columns" be rephrased to fractions?
2. Are 12 and 16 best defaults inuit should encourage? My personal feel is that [previous version of `inuit-widths`] (https://github.com/inuitcss/trumps.widths/blob/master/_trumps.widths.scss) had more sensible defaults (wholes, halves, thirds, quarters, and fifths). Enough to make most kinds of layouts out there.

**Comment by florianbouvot** [comment]
> Should we rename $inuit-columns to $inuit-fractions (or something better)? Also, should all mentions of "columns" be rephrased to fractions?

That a small point but I think "fractions" would be better than "columns". 👍 

> Are 12 and 16 best defaults inuit should encourage? My personal feel is that previous version of inuit-widths had more sensible defaults (wholes, halves, thirds, quarters, and fifths). Enough to make most kinds of layouts out there.

Fully agree, I think we should encourage this approach and switch to halves, thirds, quarters, and fifths default. 👍

**Comment by csshugs** [comment]
@nenadjelovac 

> Should we rename $inuit-columns to $inuit-fractions (or something better)? Also, should all mentions of "columns" be rephrased to fractions?

Yes (rename to `$inuit-fractions`) and yes (rephrase all mentions of "columns").

> Are 12 and 16 best defaults inuit should encourage? My personal feel is that previous version of inuit-widths had more sensible defaults (wholes, halves, thirds, quarters, and fifths). Enough to make most kinds of layouts out there.

I'd vote for:

```scss
$inuit-fractions: (
    1,
    2,
    3,
    4,
    5,
    12,
) !default;
```

**Comment by florianbouvot** [comment]
I'd vote for:

```
$inuit-fractions: (
    1,
    2,
    3,
    4,
    5,
) !default;
```

*without the 12 😆 *

**Comment by csshugs** [comment]
@florianbouvot I'm fine with it 😄

**Comment by florianbouvot** [comment]
TODO : update comments to follow latest updates (my english is too bad for this kind of work).

**Comment by florianbouvot** [comment]
@inuitcss/core who can update comments cleanly?

**Comment by csshugs** [comment]
@florianbouvot I take a look at it.
