### ISSUE TITLE
[tools.widths] Is missing `u-1/1` class and having classes like `u-12/12` and `u-16/16` intentional?

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/inuitcss#102]
@csswizardry Is this a bug? It looks like an [old issue](https://github.com/inuitcss/tools.widths/issues/2) that we had fixed with [this chunk of code](https://github.com/inuitcss/tools.widths/blob/master/_tools.widths.scss#L28-L52), so I'm curious if this is intentional?

**Comment by LayZeeDK** [comment]
u-1/1 is `width: 100%` which is the default in `objects.layout`. Classes like `u-12/12` and `u-16/16` is useful when generating classes using e.g. a CMS grid.

**Comment by csshugs** [comment]
> Classes like u-12/12 and u-16/16 is useful when generating classes using e.g. a CMS grid.

Good point!

**Comment by nenadjelovac** [comment]
@LayZeeDK 
>u-1/1 is width: 100% which is the default in objects.layout

Yes, it's true that `o-layout__item` is `width: 100%` by default. But `u-1/1` can be used on other stuff than just layout. 

>Classes like u-12/12 and u-16/16 is useful when generating classes using e.g. a CMS grid.

I am not sure if I understand this. Can you give me an example of where `u-1/1` would not do the trick? I just want to understand the context. 
thnx

**Comment by LayZeeDK** [comment]
I do see your point about using the width utilities with other components.

In a CMS I would allow the user to choose how many columns a section should span out of say 12 columns. The CMS could output markup with a template like `<div class="u-{{columnSize}}/12">` and it would work no matter the combination chosen by the user.

**Comment by nenadjelovac** [comment]
@LayZeeDK the main problem is that it is *not* column(s), it's fraction. See my comment and following discussion [here](https://github.com/inuitcss/inuitcss/issues/101). 

So in your CMS user could alter the widths of section with wholes, halves, thirds, quarters, fifths etc (this is in my opinion and experience enough to make a lot of layouts out there).

In the CMS you'd ask something like:

>How wide do you want this to section to be?
>
- one whole (full width)
- one half
- one third
- two thirds

And then in template you'd output `<div class="u-{{columnSize}}">`.

*Note: this is just an example to illustrate the point and could be better UX wise.*

**Comment by LayZeeDK** [comment]
You are right that this could be a better way to present it to the (CMS) user. But building the CMS UI and the markup generated are two different things.

Also, even in the `utilities.widths` it is currently referred to as _columns_:
````
// How many columns would you like in your grid system(s)? By default, inuitcss
// builds you a 12 and a 16 column grid.
$inuit-columns: 12 16 !default;

**Comment by nenadjelovac** [comment]
@LayZeeDK 

>Also, even in the utilities.widths they are currently referred to as columns

Yup, we already have issue raised about that [here](https://github.com/inuitcss/inuitcss/issues/101) ;). I would have written `<div class="u-{{ fraction }}">` instead, but didn't want to add confusion into discussion.

**Comment by csswizardry** [comment]
I think for the sake of cleanliness, completeness, and encapsulation, actually generating `u-12/12`, `u-16/16`, etc.  is probably the correct thing to do (despite what we did last time).

**Comment by nenadjelovac** [comment]
@csswizardry I just realized I could still use `u-1/1` with this solution so it has my use case covered ;) Closing this.
