### ISSUE TITLE
[utilities.widths] Make obvious that there are pull and push classes

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/inuitcss#104]
[Pull and push classes](https://github.com/inuitcss/inuitcss/blob/develop/tools/_tools.widths.scss#L25-L41) are generated alongside [width utility](https://github.com/inuitcss/inuitcss/blob/develop/utilities/_utilities.widths.scss) classes. But it's nowhere to be found in comments or examples (for example, I didn't know about it until I accidentally checked the code for widths mixin :)). Maybe the best solution is to point it out via examples in comments in `utility.widths`? 

@inuitcss/core what do you think?

**Comment by florianbouvot** [comment]
> I didn't know about it until I accidentally checked the code for widths mixing

Same for me, I understand the relationship between widths and push/pull but I think we need to split them in separate files.

**Comment by csshugs** [comment]
> I think we need to split them in separate files.

...or just completely drop 'em? I personally never needed them, but I might be an exception there.

**Comment by florianbouvot** [comment]
@csshugs I ~~never~~ rarely needed them too but I think there are some use case. That's why I propose to separate widths and push/pull 😉

**Comment by dnixx** [comment]
I use pull and push on almost every project. I've replaced them with flexbox, though, which I personally would very much like to see in inuitcss as well. :)

**Comment by anselmh** [comment]
Push and pull is needed and I think we should not remove them from the codebase. However, pointing out how to use them and that they exist should be a major goal indeed.

> I think we need to split them in separate files.

Hm, I’m not sure if that’s reasonable as they’re directly related to the width classes and rely on that code to work. On the other hand, moving them into a separate file would make it a opt-in for users, so @csshugs for example could leave that partial out since he doesn’t use it.

**Comment by csshugs** [comment]
> so @csshugs for example could leave that partial out since he doesn’t use it

@anselmh exactly

**Comment by csshugs** [comment]
@anselmh 

> Hm, I’m not sure if that’s reasonable as they’re directly related to the width classes and rely on that code to work.

I think push and pull can be considered as additions to widths, but not directly dependent on it. So splitting them is possible and not risky. But I get your point.

**Comment by csshugs** [comment]
@inuitcss/core 
I think we need a poll:
* 👍  for splitting `push`/`pull` and `widths` into separate files
* 🍺  for keeping them in one file (but at least make the existence of `push`/`pull` more obvious)

**Comment by robjwood** [comment]
I voted for a split but only for selfish reasons as I've never used them.

What _are_ they for? Does anyone have an example use case?

**Comment by csshugs** [comment]
@robjwood 
> I voted for a split but only for selfish reasons as I've never used them.

That's a totally valid reason.

> What are they for? Does anyone have an example use case?

Imagine a grid with two items. Both items have a width of 1/4 of the container width. But the items shall not be aligned to the left but rather be offset with 1/4 width off the left. So you "push" each item to the right with an amount of 1/4:

![bildschirmfoto-2016-07-29-um-12 19 59](https://cloud.githubusercontent.com/assets/4582857/17245606/867fbd22-5587-11e6-8113-6e4f616c9e5c.jpg)

(pull is the other way round, i.e. pull items to the left)

**Comment by robjwood** [comment]
@csshugs I undertand. I think to achieve the example you highlighted I've previously put a wrapper around those items and centred the items within it. There's always multiple ways to achieve the same thing! 

In the example you showed it does feel like the use of `pull` and `push` is distinct enough from widths to justify splitting them.

Thanks for the example.

**Comment by csshugs** [comment]
You're welcome!

**Comment by dnixx** [comment]
Pull and push can also be used to reorder the layout on different devices. And you can even change the source order if you want the most important markup on top (the content) and the less important stuff on the bottom (side menu), while still being able to display it the other way around.

![pull-and-push](https://cloud.githubusercontent.com/assets/3981388/17248581/ca0aab42-559b-11e6-8e18-6132fbd87b7f.png)

**Comment by robjwood** [comment]
@dnixx Agree that flexbox would be better but that's an interesting use case. Thanks.

**Comment by csshugs** [comment]
Current poll-result:

👍 : 7
🍺 : 0

No beer?!?! What's wrong with you?

Anyway. Seems like we agreed on splitting `push`/`pull` from `widths`. 

But do we then have one file with push/pull

* * `_utilities.push-and-pull.scss`

or do we have two files:

* `_utilities.push.scss`
* `_utilities.pull.scss`

**Comment by nenadjelovac** [comment]
@csshugs I'd go with push and pull being one file.

**Comment by florianbouvot** [comment]
@csshugs one file for push and pull.

**Comment by csshugs** [comment]
@nenadjelovac @florianbouvot 

So I actually would name it `_utilities.push-and-pull.scss`?

And for responsive I'd go and do a second file named `_utilities.push-and-pull-responsive.scss`?

**Comment by csswizardry** [comment]
> So I actually would name it _utilities.push-and-pull.scss?

Maybe just `_utilities.push-pull.scss` for now.

> And for responsive I'd go and do a second file…

No. I don’t think we should have separate files for responsive.

**Comment by aaronstezycki** [comment]
Does push and pull depend directly on widths though?

How about naming convention of seperate files which depend on another _{section}.{component-name}.{extension}.scss?

So for push and pull = `_utilities.widths.push-pull.scss`

That way when you look in the 'file tree' in your chosen editor, the files appear together and have a certain relevancy?

**Comment by csswizardry** [comment]
Giving this some thought. Separating things out means we will have to double on on the logic involved in generating the classes (checking for Sass MQ, defining the fractions the looping through the fractions).

The title of this issue is *Make obvious that there are pull and push classes*—we can do that with better documentation, rather than causing a bunch of work by splitting files up.

I think they should both stay in the same file unless there are truly compelling reasons to separate them.

**Comment by csshugs** [comment]
> [...]unless there are truly compelling reasons to separate them.

One reason is that the push and pull classes are always generated, but are not always needed (e.g. I barely use them in any of my projects). 

I agree, that we would double the logic involved, but I honestly don't know if that's necessarily a bad thing.

Just wanted to point out that right now, there is generated CSS which might be considered as bloat which is potentially against inuitcss' advert of a ”framework with a tiny footprint”.

**Comment by csswizardry** [comment]
> Just wanted to point out that right now, there is generated CSS which might be considered as bloat which is potentially against inuitcss' advert of a ”framework with a tiny footprint”.

How about we leave them in the file but behind a feature switch?

```
// Optionally, inuitcss can generate classes to offset items by a certain width.
// Would you like to generate these types of class as well?
$inuit-offsets: false !default;
```

1. Make the classes more obvious.
2. Leave them in the same file.
3. Make them optional.

**Comment by nenadjelovac** [comment]
@csswizardry that would do it for me.

**Comment by florianbouvot** [comment]
@csswizardry ok for me too 😉

**Comment by csswizardry** [comment]
I have a PR for this at #129 👍

**Comment by dnixx** [comment]
> How about we leave them in the file but behind a feature switch?

Then what's the difference between uncommenting imports from main.scss and toggling feature switches? Isn't that inconsistent?

**Comment by csswizardry** [comment]
> Then what's the difference between uncommenting imports from main.scss and toggling feature switches?

I would argue that offsets and widths are similar enough to belong in the same file, which has the added benefit of consolidating the logic required to build them both.

**Comment by zerodburn** [comment]
I had completely missed pull and push classes from InuitCSS, thanks for that source order use case @dnixx. Making them more obvious in the documentation would be great.

**Comment by nenadjelovac** [comment]
@zerodburn 
>Making them more obvious in the documentation would be great.

it's already updated https://github.com/inuitcss/inuitcss/blob/develop/utilities/_utilities.widths.scss. Is it better now?

**Comment by zerodburn** [comment]
@nenadjelovac yep. I'm definitely going to test out the ordering with push and pull today. If it works well we should definitely add an example similar to @dnixx's to the full documentation.

**Comment by herzinger** [comment]
I also never used pulls or pushes. That user case should definitely be added to the documentation.

That being said, I'd most likely opt out of it for most projects even so, so it's a nice feature to be optional, in my opinion.

**Comment by csshugs** [comment]
I'm closing this since #129 is already merged in and hence this issue is solved.
