### ISSUE TITLE
[tools.mixins] [utilities.hide] Mixin is not prefixed

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/inuitcss#105]
Mixin is not prefixed with `inuit-` in:

- [tools.mixins](https://github.com/inuitcss/inuitcss/blob/develop/tools/_tools.mixins.scss#L108)
- [utilities.hide](https://github.com/inuitcss/inuitcss/blob/develop/utilities/_utilities.hide.scss#L11)

**Comment by florianbouvot** [comment]
True, can you create a PR ?

**Comment by florianbouvot** [comment]
@nenadjelovac I open it 😉
