### ISSUE TITLE
[utilities.widths] Separate non-responsive and responsive

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#111]
inuitcss use and include [Sass-mq](https://github.com/sass-mq/sass-mq) but if someone want to use another tool I think we need to split widths like that:

_utilities.widths.scss
```
$inuit-fractions: 1 2 3 4 5 !default;

@include inuit-widths($inuit-fractions);
```

_utilities.widths-responsive.scss
```
$inuit-responsive-fractions: 1 2 3 4 5 !default;

@include inuit-widths($inuit-responsive-fractions, \@#{$inuit-bp-name});
```

*And same approach for push/pull if separating from widths [refs #104]*

Thoughts ?

**Comment by csshugs** [comment]
@florianbouvot 
I already proposed an [identical idea](https://github.com/inuitcss/inuitcss/issues/80#issuecomment-233947112). 
Didn't get approved 😞

**Comment by florianbouvot** [comment]
@csshugs I didn't pay attention to that point.

**Comment by nenadjelovac** [comment]
@florianbouvot @csshugs I'd suggest reopening this so we could discuss further. @csshugs's proposal was a part of another discussion so it might got overlooked.

**Comment by csshugs** [comment]
Since I welcome the idea of splitting the widths in generell, I reopen this issue :)

**Comment by csswizardry** [comment]
I think (_think_) we can probably tidy this up. Rather than splitting out into more files, we could just do something like:

```scss
@if (variable-exists(mq-breakpoints)) {
  // GENERATE WIDTHS
}
```

Means people don’t need to read through multiple files, and the framework will just behave accordingly if someone chooses another MQ manager.
