### ISSUE TITLE
[generic.shared] Use rem units?

### ISSUE THREAD

**Issue by johannes-r** [inuitcss/inuitcss#112]
Can't we use `rem` units here instead of `px`? Like the original [generic.shared](https://github.com/inuitcss/generic.shared/blob/master/_generic.shared.scss) did?

use:
```
@include inuit-rem(margin-bottom, $inuit-global-spacing-unit);
```

instead of:
```
margin-bottom: $inuit-global-spacing-unit;
```

Or is there a reason this hasn't been ported over?

**Comment by florianbouvot** [comment]
Personally, I'm in favor of using `rem` when possible... 

@inuitcss/core ?

**Comment by csshugs** [comment]
OK, but when we decide to use `rem` for `generic.shared`, why limit it to just this partial. It would make sense then to use `rem`-unit everywhere else where spacing is concerned.

**Comment by nenadjelovac** [comment]
@csshugs exactly. It has to be framework wide.

**Comment by csshugs** [comment]
@inuitcss/core 
Do I get a permission from one of you to submit a PR to evaluate the implementability of this?

**Comment by nenadjelovac** [comment]
@csshugs go for it. Try it out. But I'd leave final say if we should merge it to @csswizardry

**Comment by florianbouvot** [comment]
@csshugs let's go 😉

**Comment by csshugs** [comment]
I'm not very happy with the result :-(

It kinda violates [our guidelines](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md#simplicity-is-paramount). Especially this one:

> all code that comes into inuitcss should be as simple and CSS-like as possible.

Providing mixins in all various places just to get margins/paddings seems a bit ridiculous.

@inuitcss/core Thoughts?

**Comment by nenadjelovac** [comment]
>I'm not very happy with the result :-(

@csshugs agree 100%. 

How often do you guys had the need to change the whole site based on `rem`? I personally haven't had the need in any of my projects yet..

**Comment by csshugs** [comment]
> `px` does it for me.

Agree 👍

**Comment by anselmh** [comment]
In nearly every project I set the base font-size using `em`, then reference this via `rem` or `em` in other modules. This makes it super easy to do responsive sizing such as displaying a smaller font-size on mobile (which is recommended due to the display-size/device-eye-distance difference).

What I wonder: Why do we need to rely on the `inuit-rem` mixin for this and can’t just use `rem`? I think we don’t actively provide IE8 support so this should be fine?

Currently the mixin is duplicate (one time as function, one time as mixin) in our codebase btw, but that’s a different issue I think. https://github.com/inuitcss/inuitcss/blob/49feb0bede1bbe4ecaaa8aa11d66d7e26ce24a66/tools/_tools.functions.scss#L12 + https://github.com/inuitcss/inuitcss/blob/13507af43373610418853ca2d3d12686e6974752/tools/_tools.mixins.scss#L59

**Comment by florianbouvot** [comment]
@csshugs 
> I'm not very happy with the result :-(

True :anguished:

@anselmh 

> What I wonder: Why do we need to rely on the inuit-rem mixin for this and can’t just use rem? I think we don’t actively provide IE8 support so this should be fine?

I fully agree with you but we already talk about IE8 (refs #6). Can we convert px to rem at [settings.core](https://github.com/inuitcss/inuitcss/blob/develop/settings/_settings.core.scss#L95-L98) level?

**Comment by anselmh** [comment]
> EDIT : I think that team who need IE8 support can easily rely on tools like PostCSS fallbacks that do the job (better than us)…

That sounds indeed very very reasonable. Glad you thought about this! I’d be in absolute favor of recommending usage of PostCSS for such fallbacks in addition to our tiny inuitcss. :)

**Comment by johannes-r** [comment]
The main reason why I thought about setting this in `rem` was to keep the vertical rhythm between the 'shared elements' intact when I scale the (`em`) font-size on my html element (e.g. to achieve the goal @anselmh mentioned or responsive typography in general).

But you're right, this might be a too specific use case.

**Comment by florianbouvot** [comment]
This issue reminds me this article ["In CSS use pixels not em"](http://jgthms.com/in-css-use-pixels-not-em.html) subject of debate in French community.

**Comment by nenadjelovac** [comment]
@florianbouvot just a note, you couldn't do this

```
$inuit-global-spacing-unit-tiny: inuit-rem($inuit-global-spacing-unit * $inuit-global-spacing-unit-factor-tiny);
```

because `settings` layer is included before `tools` layer (where `inuit-rem` function is at).

**Comment by florianbouvot** [comment]
@nenadjelovac Oh yeah 😆

*I try to switch from px to rem in current my current project and I have Sass error for things like this:*
```
.btn {
  ...
  padding: $inuit-global-spacing - 2px;
  border: 2px solid currentColor;
  ...
}

**Comment by nenadjelovac** [comment]
@florianbouvot I'd use `calc()` ;) See support [here](http://caniuse.com/#search=calc)

**Comment by anselmh** [comment]
Well, for your project @florianbouvot you could and probably should alter `box-sizing`, if you need to stick to `border: 2px;` or choose a rem value for the border as well.

You shouldn’t use `calc()` anywhere. In this case, I’d say it’s not recommended. The issue is that `calc()` is calculated and rendered dynamically, causing the page to slow down in the browser if used too often or on heavy calculations.

**Comment by florianbouvot** [comment]
@nenadjelovac @anselmh thank you for your feedback.

@inuitcss/core you think it's possible/suitable to move from `px` to `rem`?

**Comment by nenadjelovac** [comment]
@anselmh 

>You shouldn’t use calc() anywhere. In this case, I’d say it’s not recommended. The issue is that calc() is calculated and rendered dynamically, causing the page to slow down in the browser if used too often or on heavy calculations.

Yeah, I didn't take this possibility into account. But do you have any tests/articles about it? What I found with quick search is this:

>I've never run usage testing on it, but it theoretically shouldn't be at all painful to the painter.  When the website is painting, the renderer has to convert everything to real pixel values anyway, and doing math on those real pixels values is trivial.﻿

Also found this http://stackoverflow.com/a/26935512. So it seems if used carefully there shouldn't be much issues with it.

**Comment by anselmh** [comment]
Well, there is a reason on why `calc()` took quite some time to be implemented into browsers, it’s because of the performance. Of course you won’t notice much in most cases but I don’t think it would be appropriate to use calc in a framework. On a project-specific level, I just wanted to say: Be a bit careful and don’t use it everywhere ;)
But I think this is also off-topic :D

**Comment by nenadjelovac** [comment]
@anselmh 
>Of course you won’t notice much in most cases but I don’t think it would be appropriate to use calc in a framework.

It was related to @florianbouvot's [question](https://github.com/inuitcss/inuitcss/issues/112#issuecomment-237052155) about buttons in his project. I am strongly against having this in the framework.

But yeah, let's not off-topic any more :D

**Comment by csshugs** [comment]
> @inuitcss/core you think it's possible/suitable to move from px to rem?

Back to the topic:
If we [decide to drop IE < 9 support](https://github.com/inuitcss/inuitcss/issues/116), we should definitely just use `rem`.

**Comment by csswizardry** [comment]
Rems can be added using a post processor; it’s not inuitcss’ job to provide global rems when they usually aren’t needed (i.e. you should only use rems if you actually want the padding of your buttons to change when the font-size of your `html` element changes).

I vote that we don’t use rems globally.

**Comment by csswizardry** [comment]
1. I think that using rems globally is usually not the correct thing to do (happy to expand if people need it).
2. If people want rems throughout the whole project, they can use [a post-processor](https://teamtreehouse.com/library/convert-pixels-to-rems).
3. inuitcss should provide rems for typography-specific things (font-sizes, margins on type elements).
4. We can probably achieve point 3 without needing an entire file for it.
