### ISSUE TITLE
Remove support for IE < 9?

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/inuitcss#116]
@inuitcss/core It's been highlighted in comments on [another issue](https://github.com/inuitcss/inuitcss/issues/112#issuecomment-237000176) that PostCSS could handle IE < 9 support for users that really need it (via [node-pixrem](https://github.com/robwierzbowski/node-pixrem) perhaps). Removing official support for oldie browsers would make the code lighter and make us more nimble in inuitcss development ;)

**Comment by anselmh** [comment]
I think we should do this. Also, shouldn’t we embrace using PostCSS’ [autoprefixer](https://github.com/postcss/autoprefixer) anyway?

**Comment by csswizardry** [comment]
This *completely* removes IE8 support. As in, this will stop fundamental parts of the framework working in IE8. We will no longer have any layout. I think this is too destructive. I don’t want to provide full support for IE8, but removing layout completely is a step too far.

**Comment by csshugs** [comment]
@csswizardry 
Why is layout affected by this?

**Comment by csswizardry** [comment]
Because the layout system uses the font-size hack, and using rems will stop the hack from working.

**Comment by nenadjelovac** [comment]
Damn, forgot about that!

@csshugs check [these lines](https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.layout.scss#L104-L111).

**Comment by csshugs** [comment]
@nenadjelovac @csswizardry 
Well we could just take the `@if` away there:

```scss
@if ($inuit-use-markup-fix == false) {
  font-size: $inuit-global-font-size;
  font-size: 1rem;
}
```

**Comment by csshugs** [comment]
...I mean, if it's just the layout that concerns you.

**Comment by nenadjelovac** [comment]
@csshugs yes, but it's used in [font size mixin](https://github.com/inuitcss/inuitcss/blob/develop/tools/_tools.font-size.scss) as well.

@inuitcss/core I think we should agree what our intent is. 

1. If we officially offer support for IE < 9 then we have to agree how far we want to take it. In that case `$inuit-oldIE` remains.
2. If we want to just offer fallback where we *know* something will break, then we can do it the way @csshugs suggested.

**Comment by csshugs** [comment]
Nr. 2 makes our lives easier, I guess.

I mean, IE 8! We should do the least possible to support IE 8.

**Comment by csswizardry** [comment]
> I mean, IE 8! We should do the least possible to support IE 8.

In principle I agree, but it would be irresponsible to leave IE8 users looking at a page full of `font-size: 0;` layouts.

**Comment by csshugs** [comment]
> but it would be irresponsible to leave IE8 users looking at a page full of font-size: 0; layouts.

That's why I'd vote for Nr. 2.

**Comment by csshugs** [comment]
When you have a look at the [last commit](https://github.com/inuitcss/inuitcss/commit/197830c5629b7ad13dee4c5e1c8bffe8e2b597c8), you see that it's

A. IE8 compatible 
B. Simple (no Sass magic to detect whether we support IE8 or not)

If we some day will decide to drop IE8 support, all we have to do is remove (currently) three lines of code.

**Comment by csshugs** [comment]
@inuitcss/core 
What do you think about it looking at this [two](https://github.com/inuitcss/inuitcss/commit/e0a203b3750a57b612edbd2e9f254d47d4afa152) [commits](https://github.com/inuitcss/inuitcss/commit/197830c5629b7ad13dee4c5e1c8bffe8e2b597c8), i.e. take away the Sass logic and just put the font-size fallback in there? This would keep the IE8 compatibility and makes the Sass code cleaner. Feels like a solid compromise to me.

**Comment by nenadjelovac** [comment]
@csshugs I'm still down with that solution ;)

**Comment by csshugs** [comment]
@nenadjelovac So you want to completely drop IE8 support? Or let everything as is?

**Comment by nenadjelovac** [comment]
>1. If we officially offer support for IE < 9 then we have to agree how far we want to take it. In that case $inuit-oldIE remains.
>2. If we want to just offer fallback where we know something will break (layout, font-size), then we can do it the way @csshugs suggested.

I vote for No. 2 :) Hope that helps :)

**Comment by csshugs** [comment]
#176 is merged.
