### ISSUE TITLE
[tools.widths] Integrate the mixin into `utilities.widths`

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#117]
Can't we just integrate the widths-mixin into `_utilities.widths`.

I think it makes no sense to separate them because one will never have just one partial of these two. They'll always go hand-in-hand, or do I overlook something here?

[See here](https://github.com/inuitcss/inuitcss/blob/87b603e3b60e6d20f9c0a91cd2558f12ff0b298d/tools/_tools.mixins.scss#L5-L6)

**Comment by nenadjelovac** [comment]
Good catch @csshugs! I agree that we should practice [what we preach](https://github.com/inuitcss/inuitcss/blob/87b603e3b60e6d20f9c0a91cd2558f12ff0b298d/tools/_tools.mixins.scss#L5-L6).

**Comment by florianbouvot** [comment]
Agree too

**Comment by csswizardry** [comment]
Thanks! I’d already started working on a fix for this in a private branch (at the same time as creating responsive spacing utilities). Happy to merge this when you’re ready to open a PR 👍
