### ISSUE TITLE
Remove `inuit-hocus` function

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#119]
As mentioned [here](https://github.com/inuitcss/inuitcss/issues/5#issuecomment-237194046), there seems to exist an uncertainty if we need the `inuit-halve` function at all.

IMO it is too specific for inuitcss, especially since it is not used at all in the framework at the moment.

Thoughts?

**Comment by florianbouvot** [comment]
Agree 😉

**Comment by nenadjelovac** [comment]
Let's remove it ;)

**Comment by csshugs** [comment]
Ok, let's come back to this when/if #118 gets merged, so we just need to remove the file.
