### ISSUE TITLE
Width utility class name inconsistencies

### ISSUE THREAD

**Issue by thosetinydreams** [inuitcss/inuitcss#120]
There seem to be some inconsistencies referencing the width Utilities in comments across the files.

- the [_objects.layout.scss](https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.layout.scss) file is referencing classes like `u-width-1/3@medium` (notice the **width** word), 

- while the [_utilities.widths.scss] (https://github.com/inuitcss/inuitcss/blob/develop/utilities/_utilities.widths.scss) file is referencing `u-3/12@mobile` (no **width** word).

I'm assuming these are supposed to be one and the same, and just the classes without the word width seem to be working.

**Comment by csshugs** [comment]
@thosetinydreams Well spotted! Absolutely right.

**Comment by csswizardry** [comment]
Thanks, @thosetinydreams!
