### ISSUE TITLE
Consistent guideline for empty lines

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#124]
The amount of empty lines varies a bit at the moment. 

Examples:
- https://github.com/inuitcss/inuitcss/blob/6b59185094d41391185746aa868f927d7a7bcbbf/elements/_elements.headings.scss#L10-L11
- https://github.com/inuitcss/inuitcss/blob/6b59185094d41391185746aa868f927d7a7bcbbf/elements/_elements.images.scss#L18-L19
- https://github.com/inuitcss/inuitcss/blob/6b59185094d41391185746aa868f927d7a7bcbbf/objects/_objects.tables.scss#L12-L17
- https://github.com/inuitcss/inuitcss/blob/6b59185094d41391185746aa868f927d7a7bcbbf/objects/_objects.block.scss#L14-L15

Or I am just not getting it right. 

Either way: I think we need to write down these guidelines somewhere to get a consistent code appearance. Just a few words, like ”Use 1 empty line when..., use 2 empty lines when..., use 5 empty lines when...”.

**Comment by csswizardry** [comment]
Whilst this does need fixing, I’m keen not to get too distracted and concerned with such small things. I will try to codify a style :)

**Comment by csshugs** [comment]
@csswizardry Yeah, I just wanted to have this issue open, just to keep this in mind. Not something that needs to be fixed right now.

**Comment by herzinger** [comment]
There are some talk about it [here](http://cssguidelin.es/#meaningful-whitespace), should it be the goal?

**Comment by davidbwaters** [comment]
While it is such a small thing, I noticed trying to be consistent with it was difficult.  I think many choosing Inuit are standards evangelists and could be bothered by this.  ;)

**Comment by csshugs** [comment]
#342 is merged.
