### ISSUE TITLE
Set up and add CI service to this github repository

### ISSUE THREAD

**Issue by anselmh** [inuitcss/inuitcss#135]
Since we’re in the aim of adding unit tests for some parts of our scss code, we want to have this as a CI hook in this github repository.

I vote for CircleCI here since it’s one of the better ones and Travis can sometimes be weird and slow.

**Comment by tymondesigns** [comment]
Can circle CI run multiple languages in one go ?

**Comment by anselmh** [comment]
Ruby and node.js? Yes, should be possible. I just wonder if we can run ruby-sass and libsass in one test environment easily.

**Comment by anselmh** [comment]
Landed via 01f5b3bacb9600b4d6d1d8cbf5b6af633047db0d.
