### ISSUE TITLE
Evaluate if we can use stylelint for inuitcss

### ISSUE THREAD

**Issue by anselmh** [inuitcss/inuitcss#137]
It would be great if we could lint the project’s code. The best and most advanced linter these days for CSS/Scss is http://stylelint.io/, so we should evaluate this for the project.

To evaluate:
* Does it work with our ~~whitespace~~ _(-> Nope it doesn’t)_ / empty lines options?
* [x] any other weirdness that occurs during testing

I’ll give this a try in the next days and report back here.

**Comment by herzinger** [comment]
How's it going?

**Comment by csshugs** [comment]
@anselmh 
Anything more we need to lint with stylelint, or can we close this issue?
I don't think there will be a chance to check our empty lines, especially because we have different amounts of empty lines.

**Comment by anselmh** [comment]
I think checks are complete and I think we should merge it as soon as possible now.

----
Anselm
