### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#14]
Add a CONTRIBUTING.md file to describe general git/GitHub workflow as described [here](https://github.com/inuitcss/inuitcss/issues/11#issuecomment-228753485). Maybe @csswizardry can take care of that and outline the most important points briefly? Harry, you seem to have concrete guidelines in mind for that.

**Comment by csshugs** [comment]
@anselmh 
cc @inuitcss/core

What I was actually after is a `CONTRIBUTING.md` (for the [inuitcss repo](https://github.com/inuitcss/inuitcss)), where [the branching strategy etc.](https://github.com/inuitcss/inuitcss/issues/11#issuecomment-228753485) is manifested. 

Why I brought this up initially is: I don't know exactly how to contribute here on GitHub (How to call the feature branch, how to write commit messages (referencing other issues etc.)). I could teach it to myself by analysing the history of the repo. So it's not necessarily for me (although I would appreciate a summary in one `.md` file). It's rather for devs "outside" of the inuitcss team that are willing to contribute.

@anselmh So, of course the link you posted above still appllies and hence could be part of that new `CONTRIBUTING.md` of this repo.

**Comment by herzinger** [comment]
I'm REALLY interested in it too.

**Comment by csshugs** [comment]
My request for a `CONTRIBUTING.md` file was met, so I'm closing this issue.
