### ISSUE TITLE
Consider reduce  duplicated widths 

### ISSUE THREAD

**Issue by area73** [inuitcss/inuitcss#146]
I see that when you are generating utility class for  widths, push, pull you are duplicating code for same "equivalent" widths 

here is an example of the output:

**u-1/1 {...}
.u-push-1/1 {...}
.u-pull-1/1 {...}**
.u-1/2 {...}
.u-push-1/2 {...}
.u-pull-1/2 {...}
**.u-2/2 {...}
.u-push-2/2 {...}
.u-pull-2/2 {...}**
.u-1/3 {...}
.u-push-1/3 {... }
.u-pull-1/3 {.. }
.u-2/3 {...}
.u-push-2/3 {...}
.u-pull-2/3 {... }
**.u-3/3 {... }
.u-push-3/3 {... }
.u-pull-3/3 {...}**

I mark in bold what you are repeating  

So trying to do a   ”framework with a tiny footprint”. maybe you should get rid of those duplications.

I already did that on a project base on your old mixin for columns-width. I put it here so you can have it as a reference of what I did or if you like a can create a PR and may schedule some time in a couple of weeks to make it

```
@mixin columns-width($columns-count, $columns-widths-delimiter, $device: "")
{
    @for $x from 1 through $columns-count
    {
        @for $y from 1 through $x
        {

            @if ($y == $x and $x != 1) or
                ($y % 2 == 0 and $x % 2 == 0) or
                ($y % 3 == 0 and $x % 3 == 0) or
                ($y % 5 == 0 and $x % 5 == 0)
            {
                // do nothing we already have that fraction
            }
            @else
            {
                &--#{$device}#{$y}#{$columns-widths-delimiter}#{$x}
                {
                    width: percentage($y / $x);
                }
            }
        }
    }
}
```

**Comment by tymondesigns** [comment]
I agree that duplication can be eliminated here, but I think this would be a more elegant solution:

```sass
@mixin inuit-widths($columns, $breakpoint: null) {

  // Loop through the number of columns for each denominator of our fractions.
  @each $denominator in $columns {

    // Begin creating a numerator for our fraction up until we hit the
    // denominator.
    @for $numerator from 1 through $denominator {
      
      // Ensure we only create a single full width variant.
      @if ($numerator != $denominator or $numerator == 1) {

        // Build a class in the format `.u-3/4[@<breakpoint>]`.
        .u-#{$numerator}\/#{$denominator}#{$breakpoint} {
          width: ($numerator / $denominator) * 100% !important;
        }
  
        @if ($inuit-offsets == true) {
  
          /**
          * 1. Defensively reset any leftover or conflicting `left`/`right` values.
          */
  
          // Build a class in the format `.u-push-1/2[@<breakpoint>]`.
          .u-push-#{$numerator}\/#{$denominator}#{$breakpoint} {
            position: relative;
            right: auto; /* [1] */
            left: ($numerator / $denominator) * 100% !important;
          }
  
          // Build a class in the format `.u-pull-5/6[@<breakpoint>]`.
          .u-pull-#{$numerator}\/#{$denominator}#{$breakpoint} {
            position: relative;
            right: ($numerator / $denominator) * 100% !important;
            left: auto; /* [1] */
          }
  
        }
      
      }

    }

  }

}
```

**Comment by area73** [comment]
well that's what I was saying. if you don't use module "%" with all your common denomitaros (that there will be your prime numbers) you will get a lot of duplicarions upon your total number of columns
 ie: 2/4, 2/6, 3/6, 4/6 etc etc

So the only way to asure not to have duplication is to check for molue in all prime numer in between total col number.
In the example that I post it could be improve with a mixin that could grab all the prime numbers to be use , but For the sake of simplicity in that project y didn't do it.

**Comment by florianbouvot** [comment]
@area73 thanks again for your feedback but we already discuss this here #102.

> I think for the sake of cleanliness, completeness, and encapsulation, actually generating u-12/12, u-16/16, etc. is probably the correct thing to do (despite what we did last time).
[@csswizardry comment](https://github.com/inuitcss/inuitcss/issues/102#issuecomment-237565594)

**Comment by herzinger** [comment]
I used to have a little function/mixin pair that used extend to group all classes with identical rules, based on common denominators and such. Of course, extend doesn't play well with media queries, and after reading @csswizardry's [text on gzip ](http://csswizardry.com/2016/02/mixins-better-for-performance/) I opted to leave this out.
