### ISSUE TITLE
Using $inuit-global-spacing-unit as a rem value?

### ISSUE THREAD

**Issue by zerodburn** [inuitcss/inuitcss#147]
I've just started to change the em value on the html element at larger breakpoints so that I can change font-sizes everywhere:

```
html {
	...

	@include mq($from: massive) {
		font-size: 1.5em;
	}
}
```
and while the font sizes on base elements (p, figure, headings etc) increase **and all `margin-bottom`'s increase too**, the padding used in the `objects` layer does not. E.g. `_components.box` uses a standard `px` padding of `$inuit-global-spacing-unit`. If it was `rem` then obviously the padding would increase with that font-size: 1.5em rule I have on the html global element.

I'm thinking it would make sense for paddings to be set in `rem` too. I'm sure there is sound logic and reasoning for **not** using `rem`'s, but as there is limited documentation on this project I was just wondering if someone would mind explaining why it's done this way? I'm sure I've missed something or I haven't quite understood how to use it correctly.

This is probably more of a discussion than an issue, but I'm just after some help or advice if possible. 

My hunch is that it's related to vertical rhythm but to be honest I have always been baffled by the auto `line-height`'s generated by the inuit-font-size mixin. E.g. why do the default `line-height`'s change like this:

```
1.7 at h2 (30px)
1   at h3 (26px)
1.3 at h4 (20px)
```

Surely a `line-height` of 1 at h3 is far too small in relation to the h2 or h4, I don't get how this leads to good vertical rhythm. I've looked at the mixin's source code but I don't really understand it, If someone knows please could they explain it and maybe we can add it into the documentation? Cheers

**Comment by herzinger** [comment]
I need to think about the vertical spacing with rem, but nothing to bad comes to mind right now. But about the line-heights, it's to keep everything sitting on a baseline grid. The idea is that every line of text has as the height a value that can be divided by the base line height. I personally do think there is room for improvement in the function, and I often set the line-height myself with that in mind. 

I usually work with much smaller baselines. E.g: with a 6px baseline, I would have at the minimum:
`
1.2  (or 36px) at h2 (30px)
1.15 (or 30px) at h3 (26px)
1.2  (or 24px) at h4 (20px)
`
...and I can increase these values, but always with 6px increment steps.

That is, IMO the best way to work with type on baseline grids.

**Comment by zerodburn** [comment]
@herzinger thanks for answering. How can you tell everything is on a baseline grid. Do you use a background-image on the body element with lines or something? I might give that a try...

With regards to using rem's as the global spacing unit it was just a question, if anyone has any thoughts I'd love to hear them :)

**Comment by herzinger** [comment]
Yes, you could use a background to check it, there's a number of ways to do just that. There's even browser extensions that do so. But I usually just trust the math and the general look of the page. It's not that hard.

**Comment by csshugs** [comment]
I'm closing this, because we wont introduce a rem value for `$inuit-global-spacing-unit`. You can read about it [here](https://github.com/inuitcss/inuitcss/issues/112#issuecomment-237563580).
