### ISSUE TITLE
Porting

### ISSUE THREAD

**Issue by herzinger** [inuitcss/inuitcss#148]
Hi there,

I've been following inuitcss for a long time now, since the first repo, but it's being some time since I checked it, so I missed on the start of this united version. Right now I'm at the early/mid stages of the development of a ui tool kit for a social media site where I work, around the former inuitcss modules. It's quite the big project.

With that in mind, I have 2 questions:

1. Is there any tips or things I should have in mind to go about porting my project to this version?
2. There are some stuff I do differently, some modules I didn't implement as I had another way I prefer to achieve and that kind of thing. I'd love to get involved with inuit's development to both bring stuff like that to the discussion table and contribute with things the team already want to achieve and could use some help. How should I go about it?

**Comment by csshugs** [comment]
@herzinger 

> Is there any tips or things I should have in mind to go about porting my project to this version?

I guess there are three big changes you have to make:
* You have to update the classes in your markup with the new `o-` and `u-` namespaces
* There are no responsive spacings anymore. So if you used them, you have to come up with a custom solution like [this](https://github.com/inuitcss/inuitcss/commit/37e91d57a0e341f606fb0c63186baf3e7a276f6c)
* And, of course, some modules are not included in the new beta version anymore, like `objects.list-ui`. You can either just keep using the pre-alpha versions of those modules or you provide a custom solution for them, as well.

Apart from that I would say there are no more big changes to be expected to come in the new version, so I would consider it relatively safe to port over your project.

> There are some stuff I do differently, some modules I didn't implement as I had another way I prefer to achieve and that kind of thing.

Well that's exactly what we want the people to do with inuitcss. Take the pieces that fits you and leave those bits out that you don't like/don't need and extend the framework with functionality you need for you specific project.

> I'd love to get involved with inuit's development to both bring stuff like that to the discussion table and contribute with things the team already want to achieve and could use some help. How should I go about it?

Of course, we appreciate any kind of help/suggestion/discussion/bug reporting. 
If you have anything you think the framework would benefit from, please first [have a look at `CONTRIBUTING.md`](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md), and will be grateful for any kind of contribution.

**Comment by herzinger** [comment]
Thank you very much for the answer. I already used the $inuit-feature-namespage variables to add the namespace fragments, and no responsive spacing, so it should be fine. As soon as I have some time I'll fork this repo and take a look at how I can go about contributing.

**Comment by csshugs** [comment]
👍
