### ISSUE TITLE
[utilities.spacing] Responsive spacings

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#149]
What's our take on responsive spacings?

**Comment by csshugs** [comment]
I would have add a commit to show a first approach but I can't push at the moment (proxy problems at our office).

**Comment by csshugs** [comment]
The code in the commit above would generate ~730 lines of CSS (for the 4 default Sass-MQ breakpoints). As soon as Sass-MQ is included, these 730 lines of CSS are always generated. Do we want this? Or do we rather want to "hide" this behind a flag so the users can opt-in? Do we want to integrate responsive spacings at all?

**Comment by herzinger** [comment]
I don't think there is a need for responsive spacing as utility classes. Those are supposed to be used for minute adjustments only, and inuitcss is not an atomic design framework, right? It seens overkill, to me.

**Comment by area73** [comment]
I still don't get it why you guys took off the conditional vars on most of your files. I though it was a nice idea having conditionals and then you decide to override it or not

**Comment by StormersFan** [comment]
Surprised me as well @area73. I liked that feature myself.

**Comment by herzinger** [comment]
I also really liked it

**Comment by csshugs** [comment]
@area73 @StormersFan @herzinger 
On why we took off the conditional vars, [have a look at this answer](https://github.com/inuitcss/inuitcss/issues/58#issuecomment-243081435).

---

Is anyone of @inuitcss/core thinking that responsive spacings are a good idea?

I'm not sure if we should "bloat" the framework with that. It feels to risky in terms of the possibility of creating black boxes in case someone defines 10 breakpoints and generates ~2000 lines of code because of that.

Maybe it's a better idea to leave that to the individual inuitcss users. Or maybe someone provides an inuitcss plugin for that, someday.

**Comment by nenadjelovac** [comment]
@csshugs 
>Maybe it's a better idea to leave that to the individual inuitcss users. Or maybe someone provides an inuitcss plugin for that, someday.

I would go with this one.

**Comment by csshugs** [comment]
OK, I abandon the idea of integrating responsive spacings (for know).
