### ISSUE TITLE
[elements.forms] New partial for form "resetting"?

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#156]
I'm porting this issue over from the [deprecated CONTRIBUTING repo](https://github.com/inuitcss/CONTRIBUTING/issues/21). Thanks @corbpaul for addressing this.

The question is whether we should provide a kind of reset file for forms [like so](https://github.com/corbpaul/inuit/blob/inuit-extended/base/_base.forms.scss). 

Would this still be generic enough, or is this too opinionated for inuitcss?

**Comment by anselmh** [comment]
IMO it’s not too opinionated and I’d love to see this in inuitcss.

**Comment by csshugs** [comment]
Anyone got other best practices to be add to [this](https://github.com/inuitcss/inuitcss/commit/e16c11add32b918e2af21d891baef03f92057f9c)?

**Comment by nenadjelovac** [comment]
@csshugs it seems to me that what you added should actually go in [`_generic.reset.scss`](https://github.com/inuitcss/inuitcss/blob/develop/generic/_generic.reset.scss), instead of separate file in elements layer. I say that because all there is are bunch of properties that just reset values.

**Comment by csshugs** [comment]
@nenadjelovac Yeah, you're right. [I modified that](https://github.com/inuitcss/inuitcss/commit/e67e7541ce5837c5dc77b23c15c64da09d22e2f4).

**Comment by csshugs** [comment]
#193 is merged
