### ISSUE TITLE
[utilities.widths] responsive 'mobile' not working

### ISSUE THREAD

**Issue by moog16** [inuitcss/inuitcss#160]
I was digging through _utilities.widths, and noticed that the classes are created using these for loops:

```
@if (variable-exists(mq-breakpoints)) {
  @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {
    @include mq($from: $inuit-bp-name) {
      @include inuit-widths($inuit-fractions, \@#{$inuit-bp-name});
    }
  }
}
```
 When I try using the class `u-1/3@mobile`, I would expect it to create `max-width` media query. But in this loop we are only using `mq($from...)`. I fixed this by creating an if/else within the @each loop:

```
@if (variable-exists(mq-breakpoints)) {
  @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {
    $isMobile: ($inuit-bp-name == mobile);
    @if $isMobile {
      @include mq($until: $inuit-bp-name) {
        @include inuit-widths($inuit-fractions, \@#{$inuit-bp-name});
      }
    } @else {
      @include mq($from: $inuit-bp-name) {
         @include inuit-widths($inuit-fractions, \@#{$inuit-bp-name});
       }
    }
  }
}
```
Notice the `$until`.

This isn't a final solution, but I was hoping you guys could incorporate this into the framework.

**Comment by tymondesigns** [comment]
I prefer the mobile first approach myself. 

And I don't think we should mix the media queries in the way that you suggest.

I agree that if you name your breakpoints as `mobile`, `tablet`, `desktop` etc then it makes it more confusing.

Alternatively you could leave out the `mobile` breakpoint and assume that `u-1/2` will be in effect on mobile and `u-1/4@tablet` on tablets and so on.

**Comment by csshugs** [comment]
I should mention that the current implementation of responsive widths is just a default solution which is likely to be dropped in favor of a custom solution by any developer project-wise. Hence this condition:

```scss
@if (variable-exists(mq-breakpoints)) {
  ...
}
```

That is, if you want to use another tool as Sass-MQ, you can do so. 

So, being a default solution, we want it [as simple as possible](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md#simplicity-is-paramount) even more. We don't want to overcomplicate the things, so we take a mobile first approach by default and keep it simple by not providing extra Sass functionality to be able to choose between mobile first and desktop first.

IMO, inuitcss shouldn't introduce Sass complexity here.
What does @inuitcss/core think?

**Comment by florianbouvot** [comment]
@csshugs fully agree.

**Comment by nenadjelovac** [comment]
@csshugs I agree we shouldn't introduce Sass complexity.

However, I can see why things are confusing for @moog16. As @tymondesigns said:

>[...] if you name your breakpoints as mobile, tablet, desktop etc then it makes it more confusing.

I totally agree on this. So, @moog16 you can take the mobile first approach @tymondesigns suggested:

>[...] leave out the mobile breakpoint and assume that u-1/2 will be in effect on mobile and u-1/4@tablet on tablets and so on.

 and make a settings file in your project named something like `_settings.sass-mq.scss`. There you can have following breakpoints (just an example):

```sass
$mq-breakpoints: (
    md:  320px,
    lg:  769px,
    xlg: 980px,
    xxlg: 1300px
);
```

(md = medium, lg = large, xl = extralarge, xxl = extraextralarge). 

Then in your html you'd write classes in mobile first approach:

```html
<div class="layout__item u-1/2 u-3/4@md u-2/5@lg u-1/3@xlg">
```

This is how I'd personally do it, which helps me not having to write any Sass logic/functionality in my project. Also, I can use this file in my starter kit so that I have the same workflow across different projects.

**Comment by moog16** [comment]
Ah gotcha. This makes a lot of sense. I was accustomed to using the old [inuit-widths](https://github.com/inuitcss/trumps.widths-responsive/blob/master/_trumps.widths-responsive.scss), and thought it was a bug. This approach really simplifies it. 

Thanks again!

**Comment by nenadjelovac** [comment]
@moog16 No problems, and glad we could help ;)
