### ISSUE TITLE
[utilities.spacing] how to tackle responsive variations?

### ISSUE THREAD

**Issue by gijsroge** [inuitcss/inuitcss#161]
This isn't so much as an issue but i'm wondering how one would manage the spacings when they have to be smaller/bigger on different viewport sizes.

Would it be doable to create variations of every spacing for different viewport sizes by modifying the spacings loops? Or what would be the best way to tackle this?

Thanks!

**Comment by csshugs** [comment]
@gijsroge 
It is totally doable, but doubtable that we will introduce this into the framework at the moment. 

We already discussed this topic in #149. Take a look there to see how you can polyfill this yourself into the framework.

**tl;dr:**
Import this bit of Sass in your utilities layer to get responsive spacings:

```scss
@if (variable-exists(mq-breakpoints)) {

  @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {

    @include mq($from: $inuit-bp-name) {

      @each $property in $inuit-spacing-properties {

        @each $direction in $inuit-spacing-directions {

          @each $size, $value in $inuit-spacing-sizes {

            .u-#{$property}#{$direction}#{$size}\@#{$inuit-bp-name} {
              #{$property}#{$direction}: $value !important;
            }

          }

        }

      }

    }

  }

}
```

**Comment by gijsroge** [comment]
Okay, not a fan either. Thanks for clearing this up!

**Comment by csshugs** [comment]
You're welcome!
