### ISSUE TITLE
For documentation: font-size mixin needs unit

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#162]
Hi, 
I am new here, and I think it would help very much to mention at the font-size mixin that the $font-size actually needs a unit going along with its value, otherwise an error is thrown. (Or adapt error message asking something like "Did you include incude a font-size unit such as px?")

Thank you!
Robert

**Comment by csshugs** [comment]
@rowild 
[2ed7edd](https://github.com/inuitcss/inuitcss/commit/2ed7edd9df50f32b49fdf93be4329650499b5f77) adds a warning when not giving `$font-size` in `@include inuit-font-size` a `px` unit.

@inuitcss/core This does makes sense to add to the mixin, right?

**Comment by florianbouvot** [comment]
@csshugs looks good 😉

**Comment by rowild** [comment]
Thank you!

**Comment by csshugs** [comment]
#185 is merged.
