### ISSUE TITLE
Comments in the form of sassdoc?

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#164]
Since comments are needed anyway, and sass delivers sassDoc, I would like to encourage to use a commenting style that supports the sassdoc syntax.

**Comment by csshugs** [comment]
We already decided not to use SassDoc. You can read about it in #150

**Comment by rowild** [comment]
Thank you for pointing that out!
Still strange, since inuitcss advertises itself as a "sass-based framework". As a benefit it would lead to nothing else but a consistent way of commenting, eventually across all sass frameworks, which – imho –  justifies changing the commenting style...

**Comment by csshugs** [comment]
> As a benefit it would lead to nothing else but a consistent way of commenting, eventually across all sass frameworks

Got your point.

**BUT:** The commenting style of SassDoc is a Sass comment, hence it doesn't get printed in the compiled CSS. We actually do want this to be the case, so we are using CSS comments where appropriate and Sass comments, where it must not be printed to the compiled CSS.
