### ISSUE TITLE
Proposal: Adding 0 columns to _utilities.widths.scss

### ISSUE THREAD

**Issue by thewinger** [inuitcss/inuitcss#165]
Why not adding a 0 columns in widths? 
```
if $numerator == 0 { 
   display: none !important
}
```
So the reading of the HTML code would be 
Li element occupies 1 out of 12 columns in mobile and 0 columns in tablet for example.

I know there is a hide utility but, can both things live together or would it be against DRY principle?

**Comment by csshugs** [comment]
@thewinger 
IMO this would be too specific to be introduced to the framework.

I admit that I did this myself from time to time, but always felt a bit dirty. Hiding entire layout columns seems not like being best practice, hence inuitcss should not promote doing so.

This approach cries for a inuitcss plugin. though. Feel free to provide a repo for your solution to extend the framework with that kind of functionality.

**Comment by nenadjelovac** [comment]
@thewinger I agree with @csshugs that this is too specific to be included in the framework.

Also, you can add this to your project via hide classes (as suggested [here](https://github.com/inuitcss/inuitcss/issues/175#issuecomment-249136059)). So you'd have a general `u-hidden@<breakpoint-name>` which you can use on any element and with any class instead adding this dirty way of having a `0` class (which you can use only on layout).
