### ISSUE TITLE
Question: why are padding and other values in px?

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#167]
Please forgive, if this is a stupid question!

While digging and testing inuitcss I discovered that many values still are generate as px units (all objects, for example. Wouldn't it be more appropriate to generate those values as (r)em?

**Comment by kaydwithers** [comment]
Rems can be a pain to work with. I prefer working with px. But I use 'rem-calc(18px)' for rem conversion.

**Comment by csshugs** [comment]
tl;dr:
We don't use rems, where they are not needed (see quote below).

> Rems can be added using a post processor; it’s not inuitcss’ job to provide global rems when they usually aren’t needed (i.e. you should only use rems if you actually want the padding of your buttons to change when the font-size of your html element changes).

— @csswizardry ([August, 4th 2016](https://github.com/inuitcss/inuitcss/issues/112#issuecomment-237563580) in #112 )
