### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [inuitcss/inuitcss#169]
Hello @csswizardry ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I am not sure which files are needed to grab on [npm](https://www.npmjs.com/package/inuitcss).
Please help me confirm which `js` or `css` file is necessary.
Thank for your help!

https://github.com/cdnjs/cdnjs/issues/9044

**Comment by csshugs** [comment]
@kennynaoh 
inuitcss does not provide any kind of `js` files. 
And although it's a pure CSS framework, it doesn't provide any `css` either.

This repository really just offers a bunch of `scss` partials which you could grab, so I don't see any sense in hosting it on cdnjs. 
If someone wants to use inuitcss, they need to compile the SCSS partials to CSS first to be able to use it in production.

**Comment by kaydwithers** [comment]
@csshugs i think this might be worth exploring. A CDN of a built .css file with everything from Inuit switched on. I often use a built main.css inuit file for a quick way to access the grid on some of my quick projects and also for js fiddles. A CDN would be great for this type of thing.

**Comment by herzinger** [comment]
Actually Just having a compiled version somewhere to use in codepen/jsfiddle/etc would be great already.

**Comment by csshugs** [comment]
> Actually Just having a compiled version somewhere to use in codepen/jsfiddle/etc would be great already.

I'm really struggling with that idea, because that's just not how we imagine inuitcss to be used.

@inuitcss/core Thoughts?

**Comment by nenadjelovac** [comment]
@csshugs agreed. But interesting idea for someone that might find this useful.

@herzinger @kaydwithers  Is there a way that someone does this semi-automatically on another repo?

**Comment by herzinger** [comment]
You could just have one dist/ dir in the repo, maybe even with different options if relevant. Them we could link the raw file in our snippets. It could carry a disclaimer of sorts pointing out it's only there for code snippets and exemples, not actual use in projects. So yeah, not a real cdn, since this would encourage people to link it in real projects.

**Comment by florianbouvot** [comment]
> that's just not how we imagine inuitcss to be used.

@csshugs I agree. 
As @nenadjelovac I think for codepen usage it's interesting but via another repo with **disclaimer** (so I'm shared about that point).

**Comment by csshugs** [comment]
I really would like to know @csswizardry opinion on this one.

I'm still afraid, providing a full generated CSS version of inuitcss could potentially encourage people to just use all of it in a real project. This would lead to potentially unused CSS which is against the idea of inuitcss.

**Comment by herzinger** [comment]
It could also be a .scss file without imports, with all of the codebase in one file. I could write a little script to generate such a file, if needed.

**Comment by anselmh** [comment]
>>   I'm still afraid, providing a full generated CSS version of inuitcss could potentially encourage people to just use all of it in a real project. This would lead to potentially unused CSS which is against the idea of inuitcss.
>
> ... I think that would be 'their' problem, and not yours. If inuit is used incorrectly, then they haven't read the documentation and theory behind it, or it's been poorly documented. I think this is a great idea for testing purposes on codepen/jsfiddle. A project such as this would also benefit from the ease of use on those websites (codepen etc)... you might find that Inuit is used a lot more, if it's easily accessible.

I disagree here. It’s the authors task to ensure that users will use the framework in the intended way. As we as authors intend the framework to not be used as a whole, but only with the chunks you really need, it would be fatal to officially provide a compiled, full-source `.css`-file of inuitcss.

While I can see the advantage of having this for Codepen or JSBin, I’m sure that those services could either provide this on their own or people can build it on their own.
So I’m not opposing the entire idea but saying that we should not provide this officially and we should not advertise this idea of a full css file anywhere.

**Comment by hayatbiralem** [comment]
I have an idea for this. How about `inuitcss/sample-projects`? We can create simple projects like a todo app or a blog page.

In this way we can provide real life examples of how to use the inuitcss.

**Comment by kaydwithers** [comment]
> I have an idea for this. How about inuitcss/sample-projects? We can create simple projects like a todo app or a blog page.

I remember when I first started using Inuit as a Junior Developer, it was somewhat frustrating. Setting up the project and turning things off an on caused me a lot of confusion. I think a sample project is a great idea for users new to Inuit.

**Comment by rowild** [comment]
@anselmh I do understand your point! Providing the whole framework invites users to just copy/paste each an everything into there project and then overwrite it.

But that is the problem of all CSS frameworks and UIs, be it Bootstrap, Foundation, Material Design, also jQuery etc. Most of the critique the have to endure has its roots in exactly that situation: simply link to the whole framework.

CDNs offer some release to that problem, and meanwhile it is quite reasonable to assume that Bootstrap 3 is cached... of course, that doesn't solve problems like high specificity peaks, performance issues, modularization and the like.

But we have tons of examples and showcases of how those frameworks/UI tools can be used, more often than not with warnings on how to use them better, discussions, opinions, use cases, etc.

While inuitcss demands quite a different approach to handling CSS in general and itself as a framework, it definitely even more so needs the possibility to be discussed in a broad sense. Therefore I strongly vote for supporting CDNs and online snippet platforms.

**Comment by csshugs** [comment]
@rowild 

> But that is the problem of all CSS frameworks and UIs, be it Bootstrap, Foundation, Material Design, also jQuery etc. Most of the critique the have to endure has its roots in exactly that situation: simply link to the whole framework.

Exactly! That's why we are not providing a full CSS file—so we are not exposed to this critique, as well. 

I'm with @anselmh here: We should do everything we can to ensure the framework is used as intended. And inuitcss is absolutely not intended to be used "blindly" by just taking the full CSS file without looking into what's really needed of that file.
If someone wants to use it that way, we can and (of course) will not prevent them from doing so by generating that CSS file on their own. But we will not encourage them by delivering this officially, because it would be against the core intention of inuitcss.

**Comment by zomars** [comment]
I'm also using codepen to test new components, it would be nice to be able to import inuitcss for quick debugging.

**Comment by rowild** [comment]
I'd like to take up the discussion here again. 
It turns out that many frameworks like to have a pen in there forums, where people ask questions. And it is a most helpful thing to have (see GSAP, e.g.).
At the moment I try to prepare a question, having troubles with c-btn formats. It could be easily shown, what the problem is, if I just copied a link to a pen into my post. And for people, who care to have a look at it, could quickly fork the pen, adjust the code, and post back the link. Quick and easy.
So I really would like to vote for a CDN or something similar of inuitcss!!!

**Comment by zomars** [comment]
@rowild if it serves you I've hosted a out of the box version with all base components and objects [here](https://cdn.rawgit.com/zomars/7c47c14b96bc88e649d5e8fb1b030db0/raw/8e5251b4bbb3c0e364395ca317714a3af97ab011/inuitcss.css). I've used this a a [CodePen](https://codepen.io/zomars/pen/WjJOwO) also.

**Comment by rowild** [comment]
@zomars Thank you so much! Bookmarked!
