### ISSUE TITLE
comma missing in generic.shared

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#170]
in "generic/_generic.shared.scss", around line 18, there is a comma missing after the "pre"-tag:

```scss
blockquote, p, pre
```
should be:
```scss
blockquote, p, pre,
```

**Comment by florianbouvot** [comment]
@rowild thank you, we will fix it now 😉

**Comment by florianbouvot** [comment]
@rowild I close this issue, [PR #171](https://github.com/inuitcss/inuitcss/pull/171)

**Comment by rowild** [comment]
That was quick! Thanks!
