### ISSUE TITLE
Question: why is there width:100% in o-layout__item?

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#172]
The comments (documentation) says that the o-layout* classes should be used with utility classes to generate a grid system. Since u-1/4 etc. define a width on the element, there is no reason, why there should be a 100% width declared on o-layout__item. 

Right?
Or what is wrong with my thinking?

Thanks!

**Comment by tymondesigns** [comment]
Because a 100% width is a sensible default. Especially given that inuitcss is geared towards a mobile first approach (by default).

**Comment by csshugs** [comment]
@rowild 
@tymondesigns is absolutely right.
