### ISSUE TITLE
Responsive line-breaks

### ISSUE THREAD

**Issue by herzinger** [inuitcss/inuitcss#173]
Would you be interested in utility classes to hide/reveal `<br>` tags based on breakpoints?

**Comment by csshugs** [comment]
IMO that would be too specific to be integrated into the framework.

But definitely a suited use case for an inuitcss plugin.

**Comment by rowild** [comment]
@herzinger could you elaborate a bit on that idea? I've never been in a situation, where it was a topic to hide/reveal a ```<br>``` tag and would very much like to know, what such a situation could be? Thanks!

**Comment by nenadjelovac** [comment]
@herzinger it's better to add show/hide classes for general purposes (something along [these lines](https://github.com/inuitcss/inuitcss/issues/175)) and then just use those on your `<br>` tag. Then you would take [mobile first approach](https://zellwk.com/blog/how-to-write-mobile-first-css/) (which we go into details [here](https://github.com/inuitcss/inuitcss/issues/160#issuecomment-247567581)) and do something like:

```html
<br class="u-hidden@md u-hidden@xlg">
```

Which would hide the line break on medium and extralarge viewports (for example).

**Comment by csshugs** [comment]
I'm also the opinion, that this would be suited for general hide/show classes.
Therefore, this is related to #175 and I close this.
