### ISSUE TITLE
named breakpoints and javascript

### ISSUE THREAD

**Issue by herzinger** [inuitcss/inuitcss#174]
I don't know if it would be good to be added to this project, but I did a little something to allow me to access the same breakpoint names from the sass in my javascript. I though about posting it to see what you think and, it it falls too much out of scope, as a curiosity:

```sass
/* ==========================================================================
   #RESPONSIVEJS
   ========================================================================== */

/**
 * Append a pseudo element (:after) to the body, to be able to detect 
 * our named breakpoints via javascript.
 */

 @if (inuit-config(env) == dev and inuit-config(debug) == true) {
    
  body:after {
    position:   fixed;
    top:        0; 
    right:      0;
    display:    block;
    padding:    $inuit-global-spacing-unit-small $inuit-global-spacing-unit;
    background: #00f;
    color:      #fff;
    z-index:    99999;
  }

} @else {

  body:after { display: none; }

}


/*  1. it has to be a string, inside quotation marks */

@if (variable-exists(mq-breakpoints)) {

  // Loop through the list of breakpoints
  @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {

    @include mq($from: $inuit-bp-name) {
      
      body:after {
        content: '#{$inuit-bp-name}'; /* [1] */
      }

    }
  }

}
```

I have an angular directive to trigger a custom event when the breakpoints change, but you can access the value anyway you like with `window.getComputedStyle(body, ':after')`. I also use string replacement in my build process to change the value of `$inuit-config.env`, so I don't add the visual indicator in production.

**Comment by rowild** [comment]
This looks very interesting! Any chance you could share the Angular directive, too?Maybe as a CodePen or sth similar? Thanks!

**Comment by herzinger** [comment]
Bure, here you go: http://codepen.io/herzinger/pen/EgkEjW

Open he js console to see the the result. The scss snippet is in debug mode so you can compare the console logs to the css media-queries' trigger.

**Comment by nenadjelovac** [comment]
@herzinger I think this is really useful. However, I am not sure if it fits into the framework. Might be better for you to make as an inuit plugin ("add on") in a separate repo ;)

@inuitcss/core thoughts?

**Comment by csshugs** [comment]
@nenadjelovac 
Same opinion.

**Comment by herzinger** [comment]
How would one go about developing a plugin for inuitcss? Are there any guidelines?

**Comment by csshugs** [comment]
@herzinger 
If the plugin is just an extra Sass partial, just put it in an extra repo and make it available through bower/npm ([example](https://github.com/csshugs/objects.split)).

In this specific case, you'll probably need some JS. I have no experience whatsoever about that, so I don't now about that.

But we certainly will add a section about providing inuitcss plugins in the documentation.

**Comment by herzinger** [comment]
Besides this one, I have some other ideas, but I think they should work as much as plugins for inuitcss, as as standalone code, if possible. I'll make a repo this weekend post a link here for opinions, thanks.

**Comment by csshugs** [comment]
👍

**Comment by rowild** [comment]
Thank you, @herzinger ! Very interested!
