### ISSUE TITLE
What about horizontal spacing?

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#179]
Hi,

I wonder why we use the same value in the horizontal space with `$inuit-global-spacing-unit`?

Sorry, I'm confused.

My font-size 16px and my line-height 24px so global spacing unit is 24px (as you recommended). With these values, vertical space of paragraphs is a little bigger than 30px and it's ok for me.

I want to use `o-layout` for following case with 30px horizontal space.

![image](https://cloud.githubusercontent.com/assets/2085468/18986102/02bfddb0-8704-11e6-895e-6b91cc73d4b6.png)

Am I define a new variable `$inuit-global-spacing-unit-horizontal` or create new object `o-grid` for this?

What you suggest?

Thanks in advance.

**Comment by csshugs** [comment]
@hayatbiralem 
If you really want to change the horizontal spacing for `.layout` which is by default `$inuit-global-spacing-unit`, I'd suggest to omit the inuit layout-object and write it yourself with a custom variable that fit your needs (e.g. `$inuit-global-spacing-unit-horizontal`). If you don't use the inuit layout-object, you can name your custom object `o-layout` too, of course and don't need to rename it to `.o-grid` or something.

**Comment by hayatbiralem** [comment]
Thank you @csshugs, I see.
Closing :)
