### ISSUE TITLE
[objects.ratio] Duplicate key error

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#181]
Hi,

I add new ratios to the `$inuit-ratios`  and then I received the following error message:

> Duplicate key 1 in map (...

My new map looks like:

```scss
$inuit-ratios: (
  1:1,
  2:1,
  1:2,
  1:3,
  4:3,
  16:9,
) !default;
```

I can see where the problem is so I tried to solve it with this way and it works:

```scss
$inuit-ratios: (
  (1,1), 
  (2,1), 
  (1,1), 
  (1,3), 
  (4,3), 
  (16,9),
) !default;
```

But, I think previous version was more cute. If there is a more elegant way, I'd like to know.

Thanks.

**Comment by hayatbiralem** [comment]
This works too, sass is incredible!

```
$inuit-ratios: (
  1 1,
  2 1,
  1 2,
  1 3,
  4 3,
  16 9,
) !default;
```

Better, right?

**Comment by herzinger** [comment]
No, between the two, the comma separated version is more readable. But one way or another, I don't think it should be changed. Is there any rationale behind those extra ratios? The current ones are all common patterns. The ones you added seen completely useless, unless it's a really specific use case, and as such should be a project specific addition, not part of the framework.

**Comment by hayatbiralem** [comment]
I need that ratios for a masonry like component but you are right, again :) I think component specific ratios more sense.

Thanks.

**Comment by florianbouvot** [comment]
@hayatbiralem I don't understand why there is an error, I need to test it.

@herzinger 

> The current ones are all common patterns. The ones you added seen completely useless, unless it's a really specific use case, and as such should be a project specific addition, not part of the framework.

Yes and no 😆 

Yes, we will not add project specific ratio to inuitcss.
No, @hayatbiralem is right, in your own project you can alter this list to fit your needs.

**Comment by hayatbiralem** [comment]
Thanks @florianbouvot,

That was my intention but I think there was some misunderstandings. Those has eliminated with your comment. Cool 👍

**Comment by herzinger** [comment]
@florianbouvot the error comes from a duplicated key. It's a map of key:value pairs, and "1:1", "1:2" and "1:3" all have the same key (1).

**Comment by florianbouvot** [comment]
Key must be unique in [Sass Maps](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps) so I think we need to use a Sass Lists instead.

**Comment by florianbouvot** [comment]
Like @hayatbiralem example, I propose to switch from Sass map to list.

@inuitcss/core do you think we need to refactor `@each` using `nth($list, $n)` ?

```
@each $ratio in $inuit-ratios {

  $antecedent: nth($ratio, 1);
  $consequent: nth($ratio, 2);
 
  @if (type-of($antecedent) != number) {
    @error "`#{$antecedent}` needs to be a number."
  }

  @if (type-of($consequent) != number) {
    @error "`#{$consequent}` needs to be a number."
  }

  .o-ratio--#{$antecedent}\:#{$consequent}:before {
    padding-bottom: ($consequent/$antecedent) * 100%;
  }

}
```

**Comment by florianbouvot** [comment]
@herzinger I like the syntax but it doesn't work for me:

```
Error in plugin 'sass'
Message:
    src/css/objects/_objects.ratio.scss
Error: Invalid null operation: "null div 1".
        on line 71 of src/css/objects/_objects.ratio.scss
>>       padding-bottom: ($consequent/$antecedent) * 100%;
   -----------------------^
```

**Comment by herzinger** [comment]
@florianbouvot check out the PR I just made. I was able to build it with no problems using a clone of your repo.

**Comment by florianbouvot** [comment]
@herzinger It works, I was thinking that `:` will cause an issue : I'm not a Sass expert 😆

**Comment by herzinger** [comment]
@florianbouvot no problems, I am, and I'm here to help :)"

**Comment by florianbouvot** [comment]
@herzinger I read Sass documentation and I don't find this syntax in List...

**Comment by herzinger** [comment]
@florianbouvot it's a list of one index maps. Sass lists are like arrays, and maps are like objects. What I did is an array of objects, each with only one key:value pair.

**Comment by csshugs** [comment]
Closing this since #183 is merged.

Thanks @hayatbiralem for pointing out the issue and @herzinger for working out the PR! 👍
