### ISSUE TITLE
Interim showcase links in documentation?

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#186]
Dear inuitcss core members,

at the moment, inuitcss is not very welcoming for new people. There is no documentation, no example guide, no showcase etc. This makes it unnecessarily hard for newcomers of different experience levels and it also does not appear very friendly compared to other OS projects who fight for their audience.

It is also only partially helpful to say "read OOCSS, BEM, ITCSS" etc when ITCSS itself is actually not documented yet, being the key element to inuitcss.

Therefore I would suggest to include some links to websites that use the new version of inuitcss. Or include some other examples of components and how they should be used next to or with objects etc. I sure you do have enough examples.

This could be an interim solution or for the long run, but it should be something offered now. (And I know there will be reactions like "we don't like to present sample code as long as we are in beta" or the like... but you should! and post the changes that could come along with the examples...)

We all collaborate with other people, but not all those people comment, even though they are desillusioned. So I dare to speak up for all those I know and hope to find your understanding. inuitcss looks intriguing, but at the moment people tend to switch to SUIT or Tachyons, just because they are missing some guidlines and examples here... that's a pity!

That actually also touches the Codepen topic mentioned somewhere else. Of course there should be a possibility to include it there! What better way to promote it?!?!?

Thanks for reading my 2 cents!

**Comment by area73** [comment]
HI @rowild , I made a web repo for inuit CSS that may help you to understand better the architecture involved.

although it doesn't reflect the last changes of this repo , it will give you a good starting point to understand ITCSS, BEM, and Inuit components.

http://inuit-village.github.io/inuit-village/
 
I hope this can help you :)

**Comment by herzinger** [comment]
I intend to write examples and snippets for inuitcss as soon as the codepen matter is decided.

**Comment by anselmh** [comment]
Documenting inuitcss is now a relatively high prioritization for us in the core team. Until now, the source has changed a lot since the last major version so we decided to do the documentation only at a point where we’re getting to a more stable version and we’ll start soon now doing that to improve the situation.

I’m glad other people have written great posts, articles and demos already and in the meantime we need you to refer to those.

**Comment by kaydwithers** [comment]
I have made a kitchen sink for a Inuit/ITCSS project we are currently working on. It might be of some help.

https://kaydwithers.github.io/kitchen-sink/

**Comment by rowild** [comment]
@area73 , @kaydwithers Thank you for your contributions! Highly appreciated!

Did anybody already finish a website with the new inuitcss? Any chance you post a link?

I did my first little steps with this "coming soon" page:
www.ghoncheh-asadiazadeh.com

Any helpful feedback would be most welcome!

**Comment by kaydwithers** [comment]
@rowild you can try searching the source code using this website 

http://publicwww.com/websites/%22o-layout%22/

**Comment by herzinger** [comment]
@rowild I'm refactoring https://lejour.com.br with inuitcss. The institutional part is done. There's also  an small application I'm starting on today.

**Comment by rowild** [comment]
Thanks for the valuable feedback!
