### ISSUE TITLE
Slack community

### ISSUE THREAD

**Issue by hatzipanis** [inuitcss/inuitcss#189]
Any thought to having a public Slack channel? We're using Inuit heavily in our everyday work and it would be great to be able to exchange ideas and contribute.

**Comment by hatzipanis** [comment]
I usually think of GitHub Issues as a place for _issues_ and not discussion. I'd love to be able to engage in fluid conversation with other heavy users to see how they're tackling common challenges. That leaves Github Issues as a clutter-free way to discuss bugs and other shortcomings? However I wouldn't be against using Issues for this sort of discussion, if the mods were happy with this.

**Comment by rowild** [comment]
What @hatzipanis says is totally true. For me, it seems awkward to go to git for asking questions. Slack is a wonderful solution for problem discussion (and even team organization like inuitcss/core?). Since Slack it has been used by many others already, it would be a supporting tool that many people already know how to handle.

+1

**Comment by anselmh** [comment]
I agree that discussions that don’t target the framework development or the documentation itself but the usage or even meta discussions about some projects should stay out of github issues.

We’re considering this internally in the near future but first want to focus on providing a full documentation first and publish a stable version, before caring about this issue. Thanks for your patience :)

**Comment by hatzipanis** [comment]
I'm not quite sure I understand the reasoning?

Surely creating an official Slack channel and building a healthy community can only bring good things to Inuit, no? Don't they even go hand in hand with trying to get documentation together and preparing a stable version? Not to mention we currently have no place to discuss ideas, solve design challenges and learn from one another without creating Issues which as previously discussed doesn't feel like the right place.

I'll gladly help with moderation as I'm on Slack every day.

Ultimately up to you but I feel we could learn a lot from each other.

**Comment by anselmh** [comment]
@hatzipanis you mean the reason behind the prioritization of this? It’s because it adds up to our time we spend on the project. Of course it helps to have moderators like you on the Slack channel but I know it’s required that the core team also watches the discussions and replies to certain questions. We’d also need to have a sort of auto-invitation tool in place to get people on board and all this needs work. I believe that having a proper documentation and a stable framework is more important than investing time into that solution at this moment. This is why _I personally_ don’t want to invest time on this now, even though I think it’s a great idea.

**Comment by hatzipanis** [comment]
Fair play, I'll leave it there. It sounds like the team is under the pump/under resourced so if you ever need any help with the current priorities I'd be glad to lend an active hand.

**Comment by herzinger** [comment]
I can also help, pretty actively.

**Comment by herzinger** [comment]
Issues like #196 are good arguments for a slack channel or some other solution like that. I believe I can answer myself most questions about usage and things like that, and I'm basically online every waking moment (from Brazil, so GMT-3)

**Comment by StormersFan** [comment]
Is there perhaps an interim solution for a Slack channel until something official is established? I don't consider myself a developer, but I put together a platform using the latest version of inuitcss and would love to ask questions and exchange ideas with people like @hatzipanis and @herzinger. Given the resource constraints, I don't want to distract the core team and others from the wonderful work they're doing so I've avoided posting on GitHub.

**Comment by anselmh** [comment]
I think there's no issue with opening a github issue for these kind of things until we have a slack. Maybe just add a prefix such as [community] issue title. 

----
Anselm

**Comment by herzinger** [comment]
GitHub issues are not the place for that. I'll create a slack channel and take care of it myself, just treat it as unofficial.

**Comment by rowild** [comment]
@herzinger Thank you!

**Comment by jahvi** [comment]
Gitter can also be used as an alternative, not as featured packed but it gets the job done.

**Comment by herzinger** [comment]
@anselmh your invitation bounced. Maybe there was a typo in your email address?

**Comment by herzinger** [comment]
Could we drop the link in the readme and close this issue?

**Comment by davidbwaters** [comment]
patiently waiting for an invite :)

**Comment by herzinger** [comment]
@davidbwaters I've sent you one on December 4. Today you requested another, but you do realise we live in different countries with different timezones, right? Just sent another.

**Comment by diegosantamarta** [comment]
Good idea @herzinger. Just submitted the form ;-)

**Comment by zomars** [comment]
Submitted :)

**Comment by csshugs** [comment]
For now, we will not provide a public inuitcss Slack channel, unfortunately.

But I like to point you to the [“unofficial” Slack channel](#issuecomment-253886663) by @herzinger where we can solve problems and discuss things regarding inuitcss (and beyond). All thanks to @herzinger for setting it up and managing it!
