### ISSUE TITLE
[_example.components.buttons.scss] ghost buttons' modifiers may not be right.

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#195]
Hi,

This is an example, I know that but I use ghost buttons in my current project like inuitcss button component example. In my case I need override some properties (color, etc) at the moment and then I noticed that `&.c-btn--primary` usage may not be right:

```html
<button class="c-btn c-btn--ghost c-btn--primary">
  I'm a Primary Ghost Button
</button>
```

Instead it may be more accurate if we use `&--primary`.

In this case we need to use the button component as follows:

```html
<button class="c-btn c-btn--ghost c-btn--ghost--primary">
  I'm a Primary Ghost Button
</button>
```

I think this method is more suitable for BEM.

I'm not sure but instead of this maybe we can use stateful namespace like `is-ghost` ([ref](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#stateful-namespaces-is-has-)):

```html
<button class="c-btn c-btn--primary is-ghost">
  I'm a Primary Ghost Button
</button>
```

What do you think about these?

**Comment by anselmh** [comment]
> I'm not sure but instead of this maybe we can use stateful namespace like is-ghost (ref):

A ghost button is not a state but a modifier, as is the primary button. No spec/convention says you can’t or shouldn’t have more than one modifier of a module. Therefore I think the current, initial usage is totally correct.

**Comment by herzinger** [comment]
No, the example is right. `.c-btn` is the core component, `.c-btn--primary` defines the color as the primary one and `.c-btn--ghost` gives the transparent bordered style. That is the right way to do it. You should never have a modifier of a modifier, like your first suggestion, and state classes are for dynamic states, not alternative styling.

**Comment by hayatbiralem** [comment]
@anselmh and @herzinger thanks. I understand that you are right.
Then I'll get back into the old :)
