### ISSUE TITLE
Readme points to non-existent documentation

### ISSUE THREAD

**Issue by raghunayyar** [inuitcss/inuitcss#199]
More of a query than an issue.
The ReadMe says the documentation is on the website but I have been seeing a coming soon thing since like an year or may be more. Any awesome resource?

**Comment by herzinger** [comment]
Okay, so let's make it in a real issue:

1. The README should not imply there is a "full documentation" until it's true. That's just confusing.
2. It should instead point out how it's well documented in the code itself.

**Comment by florianbouvot** [comment]
@raghunayyar documentation is one of your priority to get out of beta. Thank you for your patience.

I close this and invite you to follow this existing one #58.

@inuitcss/core should we update the readme ?

**Comment by raghunayyar** [comment]
This is awesome. I would also try helping out if possible. I have been working with Inuit since sometime now and its pretty good I must say.

**Comment by florianbouvot** [comment]
@raghunayyar you're welcome, thank you for your enthusiasm and your support 😉

**Comment by nenadjelovac** [comment]
@florianbouvot I've changed the name of the issue, and labels (and reopened the issue), since this is IMO something that is not true at the moment. I agree with @herzinger's comment:

>The README should not imply there is a "full documentation" until it's true. That's just confusing.

**Comment by florianbouvot** [comment]
@nenadjelovac no problem, that's why I ask team to know if we need to update it 😉 

> @inuitcss/core should we update the readme ?

**Comment by florianbouvot** [comment]
@nenadjelovac we can temporarily remove the "Full Documentation" section or write something to explain that full documentation will be available soon, thoughts ?

**Comment by csshugs** [comment]
@florianbouvot 
cc @inuitcss/core 

Since I agree with @herzinger, too, I think [your commit](https://github.com/inuitcss/inuitcss/commit/b765f4a2f613fd243fe357524bcd159ed93ca042) is worth a PR. It looks pretty embarrassing to point the users to a documentation, which is not existent, IMO.

**Comment by florianbouvot** [comment]
Meged, thanks @raghunayyar.
