### ISSUE TITLE
[utilities.widths] offset utilities fails on responsive when used twice

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#200]
Hi,

I found a bug on offset utilities.

If I want to build responsive layout like this:

![image](https://cloud.githubusercontent.com/assets/2085468/19429487/a2c9ccc4-9458-11e6-96a4-eeb4aaafa387.png)

.. I need some code like this:

```html
<div class="o-layout">

  <div class="o-layout__item u-1/3@tablet u-1/5@desktop">
    <p>1</p>
  </div>

  <div class="o-layout__item u-2/3@tablet u-2/5@desktop u-push-2/5@desktop">
    <p>3</p>
  </div>

  <div class="o-layout__item u-2/3@tablet u-push-1/3@tablet u-2/5@desktop u-pull-2/5@desktop">
    <p>2</p>
  </div>

</div>
```

.. but it doesn't work. Look at [my pen](http://codepen.io/hayatbiralem/pen/ALPVzm).

Because of this our `left: auto;` and `right: auto;` resets doesn't override other important properties like `left: 33.33333% !important;`.

We must use `left: auto !important;` and `right: auto !important;` for solving this bug.

Working example [here](http://codepen.io/hayatbiralem/pen/jrvzOz?editors=0100).

**Comment by csshugs** [comment]
@hayatbiralem Well spotted!

@inuitcss/core Any concerns with [this one](https://github.com/inuitcss/inuitcss/commit/40dd9eabd1639a2a2fd3d41cd18a21b53ac214c9)? Anything that we overlooked?

**Comment by florianbouvot** [comment]
@csshugs adding `!important` to fix that is ok for me 👍

**Comment by nenadjelovac** [comment]
@csshugs should we add `!important` to `position: relative;` as well? I think it might make sense.

**Comment by csshugs** [comment]
@nenadjelovac 
Since it's an utility anyway, you're probably right.

**Comment by nenadjelovac** [comment]
@csshugs then it's ready for PR ;)
