### ISSUE TITLE
[objects.layout] Do we need responsive gutter size modifiers?

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#201]
Hi,

Actually, I need this at the moment and I want to know your opinion.

If we use huge gutters on any responsive project for above desktop, we must reduce gutters below tablet or phone.

If we need the huge gutters also we need that responsive modifiers too, IMO.

What do you think?

**Comment by csshugs** [comment]
@hayatbiralem 
We already had a discussion about this in the now [deprecated layout object repository](https://github.com/inuitcss/objects.layout/issues/9) some time ago.

Although this issue might be a bit old, IMO the points mentioned there are still valid for the layout module, i.e. it would increase the complexity.

It's not that complex to provide modifier classes for that by themselves, though.

**Comment by hayatbiralem** [comment]
I think I don't need it. Complexity is not an issue for me but unnecessary codes is, I guess. I'll continue with a custom object at this time. Thank you 👍

**Comment by florianbouvot** [comment]
I read again this issue and I think we can use custom proprieties at project level:

```
@import "node_modules/inuitcss/objects/objects.layout";

:root {
  --layout-gutter: 24px;
}

@media screen and (min-width: 45em) {  
  :root {
    --spacing: 20px;  
  }
}

.o-layout--gutter-responsive {
    margin-left: calc(-1 * var(--layout-gutter));

  > .o-layout__item {
    padding-left: var(--layout-gutter);
  }

}
```

**Comment by nenadjelovac** [comment]
@florianbouvot support is [_kinda_ good](http://caniuse.com/#feat=css-variables) IMO :) :D

**Comment by hayatbiralem** [comment]
@florianbouvot your approach is very nice and cleaner, thanks :)
@nenadjelovac I think we don't need CSS Vars at the moment. For example this is good for me:

```sass
@import "node_modules/inuitcss/objects/objects.layout";

.o-layout--gutter-responsive {
    margin-left: -24px;

  > .o-layout__item {
    padding-left: 24px;
  }
}

@media screen and (min-width: 45em) {  
  .o-layout--gutter-responsive {
    margin-left: -48px;

    > .o-layout__item {
      padding-left: 48px;
    }
  }
}
```
