### ISSUE TITLE
Can we open a new repo for the plugin list?

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#207]
Hi,

Can we open a new repo under the inuitcss organization for the plugin list like [Sketch Plugin Directory](https://github.com/sketchplugins/plugin-directory). This is a simple `README.md` file actually. 

I think `inuitcss/plugin-directory` would be good.

What do you think about this?

**Comment by hayatbiralem** [comment]
.. or we can create a new file in the main project root with name `PLUGINS.md` like `CONTRIBUTING.md`.

**Comment by florianbouvot** [comment]
I prefer a specific repo to something like `PLUGINS.md` in the main repo.

**Comment by csshugs** [comment]
...or even better: Providing a collection of all available plugins on the upcoming documentation site.   

I would like to wait until inuitcss is out of beta, then announce it officially, advertise the usage/building of inuitcss plugins, see what happens, and **then** list them somewhere.

**Comment by hayatbiralem** [comment]
I think it is quite reasonable.
Let's wait :)
