### ISSUE TITLE
[tools.hidden] Improve text accessibility

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#212]
As you can read in the following articles I think we can update `Inuit-hidden-visually` mixin :

* [Beware smushed off-screen accessible text](https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe#.9hmuq3328)

---

* [Cache-cache CSS](http://www.ffoodd.fr/cache-cache-css/) (in French)
* [CSS Hide-and-Seek](http://hugogiraudel.com/2016/10/13/css-hide-and-seek/) (English translation)
* [Gist](https://gist.github.com/ffoodd/000b59f431e3e64e4ce1a24d5bb36034)

Thoughts ?

**Comment by csshugs** [comment]
@florianbouvot 
> Cache-cache CSS (in French)

In French ... Seriously? 

😄 

No seriously. Totally missed those articles. Seems to make sense to update our code.
