### ISSUE TITLE
[settings.global] transition timing

### ISSUE THREAD

**Issue by fuhlig** [inuitcss/inuitcss#214]
The transition-duration in `$global-transition` (despite being in example files) should not be written as a division as the output will be:
`transition: 0.33333333s;` (depending on precision)

Suggestion: 0.3s or 300ms

The transition should also include a property and timing-function otherwise it uses the default `all` and `linear`

```
// simple
$global-transition: all 0.3s ease;

// 'advanced'
$global-transition-property: all;
$global-transition-duration: 0.3s;
$global-transition-timing-function: ease;

$global-transition: $global-transition-property $global-transition-duration $global-transition-timing-function;

.component {
  transition: $global-transition;
}
```

This might be out of scope for the inuit framework but just setting a duration could be a potential promotion of *bad practice*  for transition.
It is open for discussion ofcourse and I'd be happy to open a Pull-Request when needed.

**Comment by herzinger** [comment]
Seeing as it's only an example file, I don't see any problems here. You can do that in your own project if you want. There's no reason to make the exemple more complex.

**Comment by clindsey** [comment]
@fuhlig I think you have a good point about how the examples should be pragmatic since they're likely going to be used as a reference whether that was the intention or not.

**Comment by herzinger** [comment]
Look, I agree that the best way to go about something like this is the way @fuhlig pointed out. To be more precise, his "advanced" exemple. Incidentally, it's the way I use it myself. But rather than introducing complexity in a exemple file, I would first consider removing the transition variable from it altogether.

**Comment by csshugs** [comment]
Just because it's an example file, we still should not promote bad practice, so I'm with @fuhlig here (his simple example).

**Comment by nenadjelovac** [comment]
>Just because it's an example file, we still should not promote bad practice, so I'm with @fuhlig here (his simple example).

Fully agreed with @csshugs and @fuhlig here.

**Comment by anselmh** [comment]
Okay folks, thanks for the feedback on it, we changed the example now to a better default value. 😊
