### ISSUE TITLE
[utilities.spacing] Provide responsive spacings

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#217]
@inuitcss/core 
We desperately need responsive spacings! 

I've adjusted the `utilities.spacings` partial:

[DEMO](http://www.sassmeister.com/gist/9de73c180a95ddf32c2b7911d385703f)

The idea is: 
Having a Sass-map (3 levels deep) in which we/the user can define which variants should be generated. The map in the [Sassmeister demo](http://www.sassmeister.com/gist/9de73c180a95ddf32c2b7911d385703f) contains all possible variants. It's just to show, how it works. The map could just as well look like this:

``` scss
$inuit-spacing: (
  'margin': (
    null: (
      null: $inuit-global-spacing-unit
    ),
    '-bottom': (
      null: $inuit-global-spacing-unit,
      '-none': 0
    ),
    '-left': (
      '-large': $inuit-global-spacing-unit-large
    )
  )
) !default;
```

This way we could provide a map with some default values and the inuitcss user could override the map and continually add values when he needs more variants.

One thing is missing in my example, though: The classnames could not be changed anymore (e.g. to `.u-mb++`) without changing the generated CSS property (try adjusting the map in the demo).

I'm absolutely no Sass expert. **Can someone please look over the demo and tell me if/how this can be improved so that the classnames are configurable?**

**Comment by herzinger** [comment]
I can take a look into it around the end of the week (I've been working around the clock, so it's a bit hard right now). But why the change of heart? I've seen responsive spacing suggestions get shot down more than once here, if I'm not mistaken.

**Comment by csshugs** [comment]
@herzinger 

> But why the change of heart? I've seen responsive spacing suggestions get shot down more than once here, if I'm not mistaken.

It got shot down because it would have been: All responsive spacing variants or none (i.e. one huge block of generated CSS at once).

When my proposed solution works, it would be a perfect opt-in mechanism for the inuitcss users. Just add those spacings you need by add values to the map.

**Comment by herzinger** [comment]
@csshugs yes, but at the cost of a lot more complexity.

**Comment by csshugs** [comment]
@herzinger 
I'd argue that it's not that much more complexity than [the spacings as we have them now](https://github.com/inuitcss/inuitcss/blob/715402a4608421148f85229e9e884e1e43bad02d/utilities/_utilities.spacing.scss).

But yeah, it's a compromise ultimately. That's why I struggled to implement responsive spacings in the first place.

But IMO, responsive spacings are the only big thing left in inuitcss at the moment.

**Comment by herzinger** [comment]
IMO a 3 level deep configuration sass map is way too complex for not that much value. Also, I think that kinda cherry-picking fells a bit awkward. But I'll take a look. There are some simpler ways to accomplish this.

**Comment by florianbouvot** [comment]
If we remove some customization and assume a naming like `u-margin-direction-size\@breakpoint` can we reduce complexity?

**Comment by hayatbiralem** [comment]
I think responsive spacings are good for everyone.
I wrote a cleaner code for this in [here](http://www.sassmeister.com/gist/5fe744a2833a2e092cc20fdc91e4c073) with a sass mixin.

Hope this helps ✌️

**Comment by florianbouvot** [comment]
It looks good, thank you @hayatbiralem

**Comment by herzinger** [comment]
I have a very good idea on how to provide exactly what @csshugs wants in a clearer manner, but I think #230 should be merged first, to use that version as the base. So I'll wait that PR's conclusion before submitting mine.

**Comment by csshugs** [comment]
@herzinger 

#230 is merged. I'm eager to see what your idea on this was 😃

**Comment by herzinger** [comment]
@csshugs #236 o/"

**Comment by csshugs** [comment]
#259 is merged, so I'm closing this.
