### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by herzinger** [inuitcss/inuitcss#218]
Between version bumps, there is bound to have some breaking chances. Evento minor chances should be documented in my opinion. Since every change to inuitcss is done via pull requests, it should be fairly easy to create a simple changelog. I can create one with the changes from beta-3 to beta-4, and we can add from there at every merge in master, before tagging.

Last time I updated there were some small issues, and it was simple and to fix because I'm so active here, but it could be annoying were that not the case.

**Comment by herzinger** [comment]
Better yet would be to update this changelog at every PR merge in the develop branch.

**Comment by csshugs** [comment]
@herzinger 

> Better yet would be to update this changelog at every PR merge in the develop branch.

I think this is a great idea! 

> I can create one with the changes from beta-3 to beta-4

Would you mind to open a PR for this?

**Comment by anselmh** [comment]
I partly agree to this but first want to mention that Git/Github provides tools for this automatically, so I wonder if we really need a manually written changelog.

1. **Commit history:** This should give you a full idea on what’s changed between versions. If commit messages are written clearly, this should ideally be already enough.
2. **[Github releases](https://github.com/inuitcss/inuitcss/releases):** Admittedly, we currrently don’t use it but likely should do this. It provides an easy way to share the new features, deprecations, changes alongside with the git tag = git release. This would also ensure, every time there’s a release, the Changelog gets updated on the same place.

If nothing of that can be agreed on, I’d love to stick to a CHANGELOG.md [like this one](https://github.com/use-init/init/blob/master/CHANGELOG.md) here for this. It means indeed that every change needs to be documented in there (at the moment when you create the PR).

**Comment by mmzoo** [comment]
> If commit messages are written clearly, this should ideally be already enough.

I disagree. When I seek to upgrade inuit, there is no way I can see what is breaking and non-breaking by browsing through hundreds of commits. Additionally, not all commits change behavior.

> Admittedly, we currrently don’t use it but likely should do this

Yes, the changelog could be added to the releases. But firstly, there is no way for contributors to do that, and secondly, it's not in version control.

If there is a CHANGELOG.md, it's easy to comment on any PR:" Please update the changelog as well before merging.".

For inspiration: http://keepachangelog.com

**Comment by csshugs** [comment]
#309 is merged, so closing this.
