### ISSUE TITLE
normalize as a dependency

### ISSUE THREAD

**Issue by herzinger** [inuitcss/inuitcss#219]
About normalize, we should use it as an npm dependency, as I mentioned in issue #206.

> This [ importing .css files into sass ] currently just works with libsass, unfortunately. That's why we cannot install it as a dependency and have to copy/paste it.
> - @csshugs 

We can just copy the file to where we need it, changing the extension to `.scss` in a simple `postinstall npm script`. Nothing would change for the users. May I make a PR for that?

**Comment by anselmh** [comment]
@herzinger yes, that’d be a good idea in _my_ opinion.

**Comment by csshugs** [comment]
Personally, I also like this idea. But I like to add that running an extra script is an extra potentially point of failure. Currently the user could (although it's not recommended) just download this repo without needing to run a npm script or something to be ready to start using inuitcss.

On the other hand, when downloading inuitcss manually, Sass-MQ has to be downloaded manually, too.

**Comment by anselmh** [comment]
> On the other hand, when downloading inuitcss manually, Sass-MQ has to be downloaded manually, too.

Exactly. I think we can expect users to do this. We need to document the reliance on normalize.css but apart from that, I think it’s the best way to use a direct dependency. Much less effort for us to maintain a custom port of normalize.scss and instant updates for our users if a new normalize.css is published.

**Comment by florianbouvot** [comment]
Sorry for commit mistake, I think it work for npm.

**Comment by anselmh** [comment]
Cool, cool. Bower should work the same way if we add it to the bower.json file as well.

**Comment by twittkopf** [comment]
What do you think about creating a symlink to normalize.css instead of copying the file, wouldn't that be a bit more elegant?

_Disclaimer: I don't know if/how this works on Windows._

**Comment by anselmh** [comment]
> What do you think about creating a symlink to normalize.css instead of copying the file, wouldn't that be a bit more elegant?
>
> Disclaimer: I don't know if/how this works on Windows.

That’s exactly the reason why we don’t do this. Symlinks work fundamentally different between different operating systems and therefore it’s not a good idea to depend on a symlink via npm script in an open source project, in my opinion.

**Comment by herzinger** [comment]
That's not even the problem. If we would do that, we could simply link from `node_modules` (or the bower equivalent), but we want to change the extension to be able to `@import` into our sass files.

**Comment by herzinger** [comment]
I got ill last week and ended up not doing some things I promised. Is this issue done with already?

**Comment by csshugs** [comment]
#227 got rejected, so I'm closing this.
