### ISSUE TITLE
Error - Functions can only contain variable declarations and control directives

### ISSUE THREAD

**Issue by nearkingdom** [inuitcss/inuitcss#222]
On line 12 of _tools.rem.scss I get the following error:

**Functions can only contain variable declarations and control directives.**

`@error "`#{$value}` needs to be a pixel value.";`

```
// Convert any px value into its rem equivalent.
@function inuit-rem($value) {

  @if (type-of($value) == number) {

    @if (unit($value) != "px") {
      @error "`#{$value}` needs to be a pixel value.";
    }

  } @else {
    @error "`#{$value}` needs to be a number.";
  }

  @return $value / $inuit-global-font-size * 1rem;

}
```

**Comment by anselmh** [comment]
Can you please share what code triggered the error, @nearkingdom?

**Comment by nearkingdom** [comment]
I noticed the the message appears in Live Reload when I using gulp.

**Comment by anselmh** [comment]
But are you using the mixing anywhere in your code? If so, please share how you use it and with which value. Thanks :)

**Comment by nearkingdom** [comment]
I'm not sure I totally understand the question,

I'm referencing the _tools.rem.scss file in my node_modules folder from my main.scss file which live reload reads:

`@import "../../node_modules/inuitcss/tools/tools.rem";`

I guess the function inuit-rem is being used within _compontent.buttons.scss which is also being used referenced in main.scss.

**Comment by herzinger** [comment]
@nearkingdom what @anselmh wants to know is how you are using the function in your own code, to see if you are using it wrong. That being said, I found some issues with similar errors in the `libsass` repository concerning `@else` in one of their beta versions. `gulp-sass` uses `libsass` internally, so could you try and see in your `package.json` what version of `gulp-sass` you are using?

>gulp-sass is a very light-weight wrapper around node-sass, which in turn is a Node binding for libsass, which in turn is a port of Sass. Because of this, the issue you're having likely isn't a gulp-sass issue, but an issue with one of those three projects.

Also, try installing version 2.3.2 (which is the one I'm using, without errors) and see if it goes away.

**Comment by nearkingdom** [comment]
I guess I'm not using the function at all - I'm just referencing the file - I havn't written any code yet.
@import "../../node_modules/inuitcss/tools/tools.rem"; 

I made sure I'm on gulp-sass 2.3.2 and I get the same errors.

I have commented out the function while I work on the project.

**Comment by herzinger** [comment]
@nearkingdom I see. Is the project you are working on up somewhere I can take a look at it? I feel like it has something to do with your setup.

That being said, this is not a vital function. In fact, theres an [open thread](https://github.com/inuitcss/inuitcss/issues/204) about removing it from the framework and I think it would survive until the next version bump. Even so, It would be nice to understand the issue you are facing all the same.

**Comment by herzinger** [comment]
I don't think there is anything we should do about this, since it's certainly nothing wrong with inuitcss itself. I would like to see the setup as a matter of curiosity, and I could maybe help solve it by doing so, but either way this issue can be safely closed.

**Comment by csshugs** [comment]
> it's certainly nothing wrong with inuitcss itself

Agree. But let's see if we can help @nearkingdom to solve his problem. @nearkingdom can you give us some more information. What actual Sass version do you have (not gulp-sass) and did you already tried to run Sass standalone in the command line?

**Comment by csshugs** [comment]
@nearkingdom I'd love to hear some feedback from you. Did you managed to solve this issue?

**Comment by csshugs** [comment]
I'm closing this now, since @nearkingdom seems to have solved this. 

I would like to know what was the actual problem, though. If you could give us any feedback on this, that would be awesome. Cheers!
