### ISSUE TITLE
Small modifier name inconsistency.

### ISSUE THREAD

**Issue by aaronstezycki** [inuitcss/inuitcss#234]
I've seen a change from shortened names using the  --rev modifier on objects to a --reverse. The pack object still uses the --rev name convention. Only a small hiccup, but I'm a sucker for consistency. 👍

https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.pack.scss#L86

**Comment by florianbouvot** [comment]
Good point, thank you @aaronstezycki

**Comment by florianbouvot** [comment]
Merged.
