### ISSUE TITLE
inuit-widths default delimiter parameters cause empty spaces in output css classes

### ISSUE THREAD

**Issue by Zsolt-R** [inuitcss/inuitcss#239]
I noticed that the updated inuit-widths mixin delimiter parameters output empty spaces when generating the css classes. I noticed if I delete the empty spaces where the default values are declared the css classes are processed correctly.

This causes empty spaces:
```scss
$inuit-widths-delimiter: \/ !default;
$inuit-widths-breakpoint-separator: \@ !default;
```
This outputs correctly:
```scss
$inuit-widths-delimiter:\/!default;
$inuit-widths-breakpoint-separator:\@!default;
```
### Output
Current output
```css
 .u-push-3\/ 12\@ wide {
   ...
  }
```
instead of
```css
  .u-push-3\/12\@wide {
    ...
  }
```

**Comment by florianbouvot** [comment]
@Zsolt-R can you give us some info about how you compile your Sass and which build tool did you use?

**Comment by Zsolt-R** [comment]
Hi Florian, I use Prepros (https://prepros.io/), and is set to use LibSass for compilation and that's it.

**Comment by herzinger** [comment]
wow, prepros! that sure brings memories... Did you try using this?
```sass
$inuit-widths-delimiter: "\/" !default;
$inuit-widths-breakpoint-separator: "\@" !default;
```

Sorry, but I can't test it right now.

**Comment by Zsolt-R** [comment]
@herzinger,just tested and it doesn't work.

**Comment by herzinger** [comment]
@Zsolt-R okay, I downloaded a trial and tested it, first the way it is right now, without quotes and... It worked as it should, no extra spaces.

Are you using the latest version of Prepros (5.10.2)? Are you using a custom command to compile the sass? Any other custom configuration? What's your system like? Anything unusual in your build process? Is the project up anywhere i could take a look? I doesn't seen to be a problem with inuitcss, and that sintaxe is valid.

**Comment by Zsolt-R** [comment]
I am using win 10 with the latest prepros and no any addition to the build. The project is private but I can send you a zip on yr email if it helps,would this be ok for you?

**Comment by herzinger** [comment]
Sure. I'm at work on Mac OS right now, but I have a Win 10 installation at home. I can test it there tonight. Can you [fill this up](https://herzinger.typeform.com/to/h6e3Km) so I can add you to the slack channel I'm maintaining? You can send it there.

**Comment by Zsolt-R** [comment]
Ok done.

**Comment by herzinger** [comment]
After lots of tests, I couldn't find anything wrong here. Even @Zsolt-R's own project, being compiled by the same version of prepros, in the same OS, with the same configurations, worked the way it's supposed to work for me, so I was unable to reproduce the error in any way. I'm forced to assume it's some anomaly in his environment, so nothing we can do to help, as it is. This issue can be safely closed.

**Comment by herzinger** [comment]
@Zsolt-R you can work around this issue, by predefining the delimiter variable with some not reserved string. That's the reason they were made into variables in the first place. So you would do something like this in your main imports file:

```scss 
$inuit-fractions-separator:  '-of-';
@import "utilities/utilities.widths";
```

That will generate classes like:
```css
.u-1-of-2 {}
.u-2-of-5@desktop {}
.u-1-of-3@mobile {}
```

**Comment by csshugs** [comment]
Thanks @herzinger for investigating! 👍 

@Zsolt-R If you can't work out the "real" problem causing this issue, the way @herzinger suggested is almost non-dirty way of working around it:

```scss
$inuit-widths-delimiter:\/;
$inuit-widths-breakpoint-separator:\@;
@import "utilities/utilities.widths";
```
