### ISSUE TITLE
Grid implementation samples?

### ISSUE THREAD

**Issue by troymclure1** [inuitcss/inuitcss#240]
Hi Guys,
I've been a huge fan of this project for ages. Now that it has changed I'm finding it hard to get my head around the new grid + sass-mq. Is there some sort of working sample kicking around as it's not working for me as expected.

Thanks in advance .

**Comment by csshugs** [comment]
@troymclure1 

> I've been a huge fan of this project for ages

❤️ 

> Is there some sort of working sample kicking around

No, not yet, unfortunately.

> it's not working for me as expected.

Maybe you can explain your problem here and we can help you out?

**Comment by csshugs** [comment]
@troymclure1 

I just quickly [created a Sassmeister gist](http://www.sassmeister.com/gist/7de193ae4c027e48745c4f8d63478a39). Maybe it clarifies your thoughts?

(Open the HTML output at Sassmeister and drag your browser window to see responsive behaviour)

**Comment by troymclure1** [comment]
@csshugs thanks for posting that, your awesome!. I guess that I missed the part about creating the widths myself.....

Can you put some of those links int he readme so other people can benefit?

**Comment by csshugs** [comment]
@troymclure1 

> Can you put some of those links int he readme so other people can benefit?

I don't think putting Sassmeister snippets in the Readme is a sustainable idea. We're currently working on an official documentation where this topic will surely get addressed.

Please bear in mind that we are still in beta. Although the code itself is very much progressed, documentation is still missing. 

Until then, we are happy to help clarifying things in the manner of GitHub issues, though.
