### ISSUE TITLE
Question: how is o-layout__right|reverse etc supposed to work?

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#243]
I try to get into the mind of inuitcss again, but with not much success. Using this SCSS:

``` 


<div class="o-wrapper">

    <div class="o-layout o-layout--right">

        <div class="o-layout__item" style="width:30%;">
            123
        </div>

        <div class="o-layout__item" style="background:red; width:30%;">
            234
        </div>

        <div class="o-layout__item" style="background:green; width:30%;">
            345
        </div>

    </div>

</div>
```

I actually expected that the layout items would be rendered from left to right, also when using reverse. But instead I get fullwidth divs rendered in the same direction all the time.

Could anybody please post a working example? Thank you!

**Comment by jamielovelace** [comment]
I think you are after the 'o-layout--reverse' modifier. 

'o-layout--right' will just simply align them on the right, so everything will be left to right, but bunched up on the right, so if you have a an item thats one-third and on its own 'row' lets say, it will be on the right instead of the left

**Comment by herzinger** [comment]
The "right" modifier makes the whole block be rendered from right to left, without messing with the items order. [See here](http://www.sassmeister.com/gist/3d1bc4dabad4ba510384feffe6057e7b).

For the result you want, use "reverse"

**Comment by herzinger** [comment]
while we are in this topic, I would like to suggest some changes. First:

```scss
.o-layout--reverse {
  direction: rtl;

  > .o-layout__item {
    direction: ltr;
    text-align: left;
  }

}
```
This `text-align: left` server no purpose. It does nothing for the object, and needs to be overwritten if you want right aligned text.

Also, we need a --left modifier too. If you are user a ltr grid, you can chose to render if from left (the default), center or right. But if you are user rtl (the --reverse modifier), theres no way to render it from left.

**Comment by rowild** [comment]
Thanks for the example!

**Comment by nenadjelovac** [comment]
@herzinger could you make a separate issue out of your proposed changes please?

**Comment by herzinger** [comment]
@nenadjelovac It's done.

**Comment by csshugs** [comment]
Since the initial question is answered, I'm closing this.
