### ISSUE TITLE
Question: how to use sass-mq

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#244]
Is there anywhere a little sample that explains how to implement sass-mp!
At the moment I load it to bower. Then, in den main include file, I define the breakpoint list. After that I include the mq script from the bower folder. But I am missing all the 1/3, 2/5 etc that are supposed to be generated in the layout object... they seem not to be generated...

Thanks!

**Comment by rowild** [comment]
This is the SCSS I use:

```
$mq-base-font-size: $base-font-size;
$mq-responsive: true;
$mq-breakpoints: (
        mobile: 320px,
        tablet: 740px,
        desktop: 980px,
        wide: 1300px
);
$mq-static-breakpoint: desktop;
$mq-show-breakpoints: (mobile, tablet, desktop, wide);
$mq-media-type: all;

@import "../../bower_components/sass-mq/mq";
[...]
@import "../../bower_components/inuitcss/utilities/utilities.widths";
``` 

Thoe u-1/3 classes won't just get generated...

**Comment by rowild** [comment]
Oh, I am sorry. I used "u-1\/3" in the HTML instead of "u-1/3".
Everything fine! Sorry for bothering!

**Comment by herzinger** [comment]
> But I am missing all the 1/3, 2/5 etc that are supposed to be generated in the layout object

Those classes are not part of the layout object, but are width utility classes.

> I used "u-1/3" in the HTML instead of "u-1/3".

what?

**Comment by rowild** [comment]
Sorry, meant u-1\/3 instead of u-1/3

**Comment by herzinger** [comment]
That's still the same

**Comment by jamielovelace** [comment]
Think its the escaping of the character :)

**Comment by jamielovelace** [comment]
Think its the escaping of the character :)

On Fri, 25 Nov 2016 at 14:49 Henrique Erzinger

<
mailto:Henrique Erzinger <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

That's still the same

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/inuitcss/inuitcss/issues/244#issuecomment-262971047
, or

**Comment by herzinger** [comment]
Ah, okay. Now that makes more sense.
