### ISSUE TITLE
layout object optimization

### ISSUE THREAD

**Issue by herzinger** [inuitcss/inuitcss#245]
Opening this dedicated issue as asked. As I said [here, in issue ](https://github.com/inuitcss/inuitcss/issues/243#issuecomment-262970374)#243, the `text-align: left;` in `.o-layout--reverse  > .o-layout__item` does nothing. Also, quoting myself:

>[...] we need a --left modifier too. If you are using a ltr grid, you can chose to render if from left (the default), center or right. But if you are using rtl (the --reverse modifier), there's no way to render it from left.

**Comment by csshugs** [comment]
Actually seems like `text-align: left;` doesn't have any affect.

> [...] we need a --left modifier too. If you are using a ltr grid, you can chose to render if from left (the default), center or right. But if you are using rtl (the --reverse modifier), there's no way to render it from left.

Agreed.

**Comment by csshugs** [comment]
#262 is merged.

Thanks @herzinger!
