### ISSUE TITLE
o-table--huge?

### ISSUE THREAD

**Issue by aaronstezycki** [inuitcss/inuitcss#247]
A Question as to do we realistically really need a table with table cell padding of 96px?

... actually do we even need o-table--large? These classes seem a bit OTT for me.

Should these have a variable map ( i.e. $table-spacing:(); ) with increments of 12px? (12px, 24px, 36px, 48px) as a default that can be overwritten?

At the minute the current table cell padding styles seems a little bit excessive.

**Comment by herzinger** [comment]
That's for consistency. Spacing works the same across the framework. If you thing it's excessive for your project, you should simply predefine the spacing variables at the start, like normal.

**Comment by csshugs** [comment]
@aaronstezycki 

> Should these have a variable map ( i.e. $table-spacing:(); ) with increments of 12px? (12px, 24px, 36px, 48px) as a default that can be overwritten?

We decided against this for simplicity (a huge bunch of default variables to be overridden). Also for every other module, you won't find any variable maps.

96px for a tables cell padding is really much indeed, but as @herzinger pointed out correctly, it's for consistency.

**Comment by herzinger** [comment]
96px is huge, as the name implies

**Comment by aaronstezycki** [comment]
Lol Okay, consistency it is! 👍

**Comment by nenadjelovac** [comment]
@aaronstezycki closing the issue then ;)
