### ISSUE TITLE
[utilities.colors] Color utilities?

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#248]
Hi,

I use these utilities on all my projects.

You?

````sass
/* ==========================================================================
   #COLORS
   ========================================================================== */

/**
 * Color utilities.
 */

$inuit-color-properties: (
        'color': 'color',
        'bg-color': 'background-color',
);

$inuit-colors-variants: (
        '-white': #fff,
        '-primary': $color-primary,
        '-gray': $color-gray,
) !default;

@each $selector, $property in $inuit-color-properties {
  @each $color, $value in $inuit-colors-variants {
    .u-#{$selector}#{$color} {
      #{$property}: $value !important;
    }
  }
}
```

**Comment by davidbwaters** [comment]
I appreciate this in theory,  I feel things get too cluttered and treads the opinion line.  There are too many ways people will want/need to do this.

When I would take this approach and I would apply a background color that needs a different text color, I almost always found myself using the same combination of classes.  It ended up being much more efficient to just apply the text and background color with the same class.

**Comment by fuhlig** [comment]
I agree with @davidbwaters as this is way too project specific.
In my experience every project has very different requirements to creating color palettes and variations and therefor should not be included in this framework (maybe as a plugin but not in core).

**Comment by hayatbiralem** [comment]
@davidbwaters @fuhlig I agree with you. Thanks :)
