### ISSUE TITLE
Remove _utilities.headings.scss

### ISSUE THREAD

**Issue by SarokuTuli** [inuitcss/inuitcss#251]
We base our philosophy on not giving structure meaning to style, so I always found very inappropriate to use utilities like .u-h1

Heading elements should be related to the HTML outline only, and nothing to do with style. There is no thing such as "style like H1".

**Comment by herzinger** [comment]
It's the exact opposite: your styling shouldn't be constrained by the markup, so it's completely valid to style something to look (actually, in this case, just to have the same font-size) as the 'h1' tag while being something else.

Your complaint is basically because of the naming. I personally like the greek letters convention better.

**Comment by kaydwithers** [comment]
On our very large project we have 8 heading classes. (u-h1 - u-h8) and 6 different types of paragraphs. (u-p1 - u-p6). Our designers actually want to add more font sizes but we've told them no.

Being able to use <h6 class="u-h8"> is incredibly helpful to us.

**Comment by herzinger** [comment]
Exactly. But you do have waaaay too many, from a design standpoint.

**Comment by kaydwithers** [comment]
I would also say we have too many font-sizes. Unfortunately I'm only a developer and the font-sizes have been a design decision. I was not happy with that decision but it had to be done.

**Comment by csshugs** [comment]
@SarokuTuli 

> It's the exact opposite: your styling shouldn't be constrained by the markup, so it's completely valid to style something to look (actually, in this case, just to have the same font-size) as the h1 tag while being something else.

@herzinger is completely right. 

If you don't use the classes of `utilities.headings`, you are completely free to just not `@import` this partial in your project.

> Your complaint is basically because of the naming. I personally like the greek letters convention better.

I also liked the old class names better, but they were confusing to inuitcss newcomers, just as the hipster naming for spacings (`.mb--`), so we made it more clear with the new naming.
