### ISSUE TITLE
[object.media] Remove this partial?

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/inuitcss#256]
Flag and media are doing basically the same thing, with flag being more versatile. Flag object has shown to be so reliable that I (and a lot of people I work with/talk to) haven't used media object since I switched to inuitcss years ago. I remember @florianbouvot suggested on one of the issues that we can do without object media.

What are your experiences @inuitcss/core? Do you think it's safe to remove media?

**Comment by csshugs** [comment]
@nenadjelovac I never used it anyway, so my opinion isn't that representative. I wouldn't miss it.

**Comment by denu5** [comment]
@nenadjelovac I stumbled upon a flexbox implemenation of the media object today, which solved an issue with the flag object. maybe you want to consider this as well. https://philipwalton.github.io/solved-by-flexbox/demos/media-object/

**Comment by clindsey** [comment]
I've been using this article as my rule for using media vs flag objects - http://csswizardry.com/2013/05/the-flag-object/

The section `Replacing the media object?` has a few reasons for why the flag object isn't meant to replace the media object, but the article is 3 years old and those reasons may not be a concern today.

I'm using the solution @denu5 [mentioned above](https://philipwalton.github.io/solved-by-flexbox/demos/media-object/)

**Comment by csshugs** [comment]
@denu5 

> I stumbled upon a flexbox implemenation of the media object today, which solved an issue with the flag object. maybe you want to consider this as well.

Since we are supporting IE9, unfortunately we have to wait until we provide flexbox-solutions by default.

@clindsey 
> but the article is 3 years old and those reasons may not be a concern today.

I think so, too. The first two points of that list in the article are obsolete IMO. And I think the flag object got tested thoroughly in the past 3 years.

**Comment by csshugs** [comment]
One more thing to consider: There are quite a few inuitcss users out there who use inuitcss a long time now. I know for a fact that there are folks out there considering to update from the pre-alpha version to this version or who actually already did update. For those people, it would be awkward when the media object suddenly would be missing.

I think it would be "safer" to just leave it in. Nobody has to import it anyway, so...

**Comment by florianbouvot** [comment]
> I think it would be "safer" to just leave it in. Nobody has to import it anyway, so...

Agree, I think we can merged this two objects when we decide to use flexbox...

**Comment by csshugs** [comment]
> I think we can merged this two objects when we decide to use flexbox...

👍

**Comment by nenadjelovac** [comment]
>For those people, it would be awkward when the media object suddenly would be missing.

>I think it would be "safer" to just leave it in. Nobody has to import it anyway, so...

Great point. I think we should then leave it for now, and "merge" it as @florianbouvot suggested - when we decide to use flexbox.

Closing this now. Thanks everyone.
