### ISSUE TITLE
[objects.layout] Markup "hack" off by default?

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/inuitcss#26]
@csswizardry This used to be [the other way around](https://github.com/inuitcss/objects.layout/issues/2#issuecomment-42482927). Why change of thoughts?

Btw, I'm using `font-size: 0` hack from the start, and never had much issues, so I am just wondering about this decision.

**Comment by csshugs** [comment]
👍 
Sorry for being late. Wasn't online for the last 3 weeks. I'm just catching up on everything.

**Comment by csswizardry** [comment]
@csshugs: No problem! I hope you had a good time away from the computer…?

**Comment by csshugs** [comment]
@csswizardry My batteries are fully charged again!
