### ISSUE TITLE
[utilities.spacing] Rename to plural "spacings"

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#260]
By looking at other modules names, e.g. `utilities.widths`, it gets clear that `utilities.spacing` is inconsistent in that matter being named singular. Wouldn't it be more accurate to rename it to `utilities.spacings` (plural)?

**Comment by nenadjelovac** [comment]
@csshugs Agreed (and PR approved ;))

**Comment by csshugs** [comment]
#261 is merged.
