### ISSUE TITLE
[objects.layout] Add auto-widths modifier

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#266]
This was already in the [pre-alpha](https://github.com/inuitcss/objects.layout/blob/master/_objects.layout.scss#L292-L307).

It contains a modifier class for when you want to have items with non-explicit widths.

It proved itself useful for many inuitcss users and since it's just a few extra lines, maybe we can add it?

**Comment by csshugs** [comment]
#267 is merged.

**Comment by herzinger** [comment]
Yeah, I have it in my projects, custom made.
