### ISSUE TITLE
Allow decimal value in crop ratio

### ISSUE THREAD

**Issue by sebelga** [inuitcss/inuitcss#276]
It would be nice to be able to set ratio like 2.66/1 for crops. The problem is the actual render of the generated class can't obviously have a "." in it.

On my fork I added a string replace function to remove dots in the class name. I will open a pull request with, let me know what you think.

Thanks for this great "framework" / guide lines! :)

**Comment by florianbouvot** [comment]
@sebelga as discussed in [PR](https://github.com/inuitcss/inuitcss/pull/277) I'm not in flavor of allowing decimal value because of complexity / unusual naming...

@inuitcss/core thought ?

**Comment by anselmh** [comment]
There are some common formats that are something like `1.43:1` (IMAX format) or `1.58577:1` for credit card. Even the golden ratio is `1.6180:1`, so I’d actually be in favour of supporting decimal values for crop ratios.

**Comment by csshugs** [comment]
@sebelga 
(**cc:** @inuitcss/core)

The only way I see in which this could be achieved with Sass is this:
http://www.sassmeister.com/gist/71f90d0a814d49238c092defb27af0c5

The concept is similar to what we are doing with the spacings, i.e. write the ratio twice:

```scss
$inuit-ratios: (
  (
    (4:3): (4:3)
  ),
  (
    (2:1): (2:1)
  ),
  (
    (16:9): (16:9)
  ),
  (
    (1.618:1): (1\.618:1)
  ),
) !default;
```

The first being what Sass uses to calculate the ratio (in `%`), the second being the string that's used as the class, i.e. with a potential escaping `\` before the decimal point in case it's needed (like `1\.618:1` for the golden ratio).

**Comment by sebelga** [comment]
I like the idea. If you want me to create another PR with your solution let me know.
Thanks for the feedback.

**Comment by florianbouvot** [comment]
@csshugs nice job, a little more complex but allow decimal.

**Comment by herzinger** [comment]
If you're going to declare the class name separated, why would you use the numbers instead of a readable name like "imax" or "golden-ratio".

**Comment by florianbouvot** [comment]
@herzinger indeed.

*Even if it's better to allow decimal in the framework, that's why I initially propose to extend at project level:*

```
@import "node_modules/inuitcss/objects/objects.crop";

.o-crop--golden {
  padding-bottom: 61.8%;
}
```

**Comment by herzinger** [comment]
We could even provide a simple function to get the % from any values.

**Comment by florianbouvot** [comment]
I vote for keeping this object as it is for now 😉

**Comment by csshugs** [comment]
I proposed [a PR](#343) which offers a solution which does not introduce breaking changes, since the `$inuit-ratios`/`$inuit-crops` lists are still the same (syntax-wise). It's just a bit more Sass logic (string-replacement) in the background, but without an extra Sass function like @sebelga did in his approach. So we keep everything under the hood and nothing changes for the inuitcss user.

**Comment by florianbouvot** [comment]
@csshugs good job.

**Comment by csshugs** [comment]
@florianbouvot Thank you.

#343 is merged, so I close this.

**Comment by herzinger** [comment]
Again, why use numbers in the class names at all? It's added logic to include something that's not all that good, when we could simply allow the uses to define a readable name in the map (where if he wanted, he could still use the numbers, and escape it manually).

**Comment by csshugs** [comment]
Personally, I find it way more clear looking at `class="o-ratio  o-ratio--4:3"` than `class="o-ratio  o-ratio--four-by-three"`. Admittedly, on the other hand, if you need the golden ratio, `class="o-ratio  o-ratio--golden"` would be much nicer. But in this case, there is really no big deal in writing the selector on your own, like [@florianbouvot suggested](https://github.com/inuitcss/inuitcss/issues/276#issuecomment-288480268).

The ultimate point for merging this in as we did was not introducing any breaking changes. The [other approach](https://github.com/inuitcss/inuitcss/issues/276#issuecomment-288363365) would do so and would also be slightly more complicated to look at.
