### ISSUE TITLE
New beta release?

### ISSUE THREAD

**Issue by KingScooty** [inuitcss/inuitcss#287]
Keen to get the latest responsive spacing in my project without having to npm install the master (develop) branch.

Can we get a `6.0.0-beta.5`?

**Comment by csshugs** [comment]
@KingScooty 

I'm also keen for a new release :stuck_out_tongue_winking_eye:. 

As you can see in the [6.0.0-beta.5 milestone](https://github.com/inuitcss/inuitcss/milestone/3), there is still one task left for the new release. I consider a changelog as critical improvement, so I'm in favour of waiting for this before we release beta.5

@inuitcss/core Thoughts?

**Comment by KingScooty** [comment]
Hi @csshugs

I have seen the milestone. I do think a changelog is important going forward, however, since we're on the develop branch, and this is a `beta` release, i see no reason to block releases just because of a changelog. These are certainly valid concerns for when we think about merging in to master.

I feel like blocking releases does more harm than good, as beta users can't detect and report bugs as easily if we aren't frequently releasing new beta releases. (Of course counter to this i am also aware that it's hard to test for bugs if there's no changelog.)

What is apparent though, is we've sat on the same beta version for nearly 6 months, despite changes being merged in and PRs closed. That's pretty poor. If a changelog is really that important, why hasn't it been done in those 6 months?

Is it a case of breaking releases down so just a few changes constitute a release, reducing the burden of writing said changelog?

I'm happy to contribute if it gets it done. There are now rather important features in `develop` that i'd like access to.

**Comment by florianbouvot** [comment]
It would be a good to create a new release (and I'm steel not in favor of adding a changelog 😁).

**Comment by KingScooty** [comment]
I'm not against added a changelog, as it does add succinct visibility of all changes going into the project. 

What i am against though, is actively blocking releases for 6 months (despite merging in changes), while we figure out what the changelog looks like. That's naughty!

**Comment by florianbouvot** [comment]
@KingScooty you are right. 

It's just a joke, I'm not alone to decide (for me Github Release is enough).

**Comment by herzinger** [comment]
Okay, that's not exactly what happened here. The project stayed pretty much inactive for a long time since the end of last year. It just so happen that a bunch of stuff - including the responsive spacing feature - was merged decently, with the changelog (which is in my hands) being the last one left.

**Comment by nenadjelovac** [comment]
@csshugs I am with @KingScooty. He has raised some valid points. Changelog is important, but ATM I'd prefer to get the current `develop` branch in the `master`.

**Comment by KingScooty** [comment]
>@csshugs I am with @KingScooty. He has raised some valid points. Changelog is important, but ATM I'd prefer to get the current develop branch in the master.

Woah there! Haha, i didn't say i want to merge `develop` into `master`, just that i want a new release tag for the `develop` branch.

**Comment by nenadjelovac** [comment]
@KingScooty sorry, still haven't woken up right :P 
The point is, people want new release, and I'm with them :)

**Comment by KingScooty** [comment]
@herzinger is there anything i can do to help?

**Comment by cata** [comment]
Hi guys, what's the status on this?

**Comment by seanislegend** [comment]
Chipping in to say that the beta 4 release was tagged in October 2016. From a fresh NPM install, I can see that there is a lot of new changes that are not included. Therefore, I'm having to go against the recommendation of installing with NPM.

**Comment by nicoqh** [comment]
The changelog has been in the loop for over half a year, and people have been asking about how they can contribute. I say screw the changelog for this release.

The changelog can be added when it's ready. The amount of time for which inuitcss goes without one doesn't increase if beta.5 is tagged.

**Comment by anselmh** [comment]
I totally agree here. We shouldn’t block the release because of a changelog. Can we please remove the issue from the milestone and do the release, @inuitcss/core ?

**Comment by anselmh** [comment]
Hey y’all, I’m happy to inform you that **we’ve just published `6.0.0-beta.5` now**. See all details in the [Github release](https://github.com/inuitcss/inuitcss/releases/tag/6.0.0-beta.5). The release is also available via npm already.
