### ISSUE TITLE
Reverse the rendered order of the grid system's behaviour

### ISSUE THREAD

**Issue by fcojgodoy** [inuitcss/inuitcss#302]
In `o-layout`, the Reverse the rendered order of the grid system: the behaviour is:
- reverse the rendered order of the grid system
- and too: fill up the layout system from the right-hand side.

Is the second behavior expected?

What if I wanted to do this?:
- reverse the rendered order of the grid system, and
- fill up the layout system from the centre or from the left

My first solution is [this](https://fcojgodoy.github.io/inuitcss.examples/o-layout.html)

**Comment by afontcu** [comment]
Hi! I'd say the second behavior is expected since there's a `.o-layout--left` modifier which will make the layout system fill up from the left-hand side:

```
/**
 * Fill up the layout system from the left-hand side. This will likely only be
 * needed when using in conjunction with `.o-layout--reverse`.
 */

.o-layout--left {
  text-align: left;

  > .o-layout__item {
    text-align: left;
  }

}
```
Would this resolve your issue?

Hope it helps.

**Comment by fcojgodoy** [comment]
Yes! My code is in master and this modifier was not there.
