### ISSUE TITLE
using u-margin-* does not work correctly

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#303]
From what I understand, classes like u-maring-top-none@tablet etc are created automatically, when the proper configuration is set.

In my project, I need a container that has u-maring-top-none@tablet and u-maring-top@desktop.
But u-maring-top-none@tablet take precedence ALL the time and therefore nothing changes on desktop.

Is this the intended behaviour?

**Comment by csshugs** [comment]
@rowild I would not call this behaviour intended. But it's rather logical:
Below the `desktop` breakpoint, the `u-margin-top-none@tablet` class takes effect, obviously. But _above_ the `desktop` breakpoint, both classes—`u-margin-top-none@tablet` _and_ `u-margin-top@desktop`—apply. 
In this case, the cascade comes into play: `u-margin-top-none@tablet` is declared **after** `u-margin-top@desktop` in the generated CSS file:

```css
```

**Comment by florianbouvot** [comment]
@rowild Thank you for your feedback, currently this utilities look not robust 🙁

I propose to loop first on breakpoints, I think that will this issue (and remove a lot of `@media (min-width...) { }`

**Comment by herzinger** [comment]
That's one difference that came about since we adopted Sass-MQ. We used to have two separated breakpoint namespaces: `lap` and `lap-and-up`. `lap` was something similar to `$from: tablet, $until: desktop`, and `lap-and-up` was what we have now: `$from: tablet`. The way it is today, we are forced to work with a mobile first approach, and the cascading and source order needs to be really robust.

**Comment by rowild** [comment]
Thank you for your feedback!
(My guts somehow tell me that, going along with the idea that a ".u-" class should only do one thing, the @media should encompass the min- and max- values...)

@florianbouvot Would you mind to elaborate a bit on this loop proposal, maybe with an example? Thank you!

**Comment by herzinger** [comment]
>My guts somehow tell me that, going along with the idea that a ".u-" class should only do one thing, the @media should encompass the min- and max- values...

I disagree. Using only the min-width allows for easier cascading. It's just a matter of getting fully in a mobile first mindset. Exclusive breakpoints are useful sometimes, but should not be the norm. In the cases were you need one, it's easy to add it manually using the sass-mq sintaxe or even adding it to the breakpoints map.

> @florianbouvot Would you mind to elaborate a bit on this loop proposal, maybe with an example? Thank you!

He already did. There's a commit linked to the issue above.

**Comment by rowild** [comment]
I eventually grasped the concept. Please feel free to close this matter. Or let me know, if I should do so (since you referenced it, I am unsure, if I should be the one closing it...)

Thanks!
