### ISSUE TITLE
Why does .o-ratio contain overflow: hidden;?

### ISSUE THREAD

**Issue by dennisfrank** [inuitcss/inuitcss#304]
Does anyone know why there is an `overflow: hidden;` in `.o-ratio`?

https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.ratio.scss#L27

I stumbled over it because of a cropped box-shadow in `.o-ratio__content`.

**Comment by csshugs** [comment]
@dennisfrank After a quick view on it, I'm really not sure if it's needed at all. It does not make any sense at the moment, indeed. 

@inuitcss/core Am I missing something or can we dump this declaration?

But if we are going to include [this enhancement](https://github.com/inuitcss/inuitcss/issues/285) in the future, we will certainly need this declaration again.

**Comment by dennisfrank** [comment]
> But if we are going to include this enhancement in the future, we will certainly need this declaration again.

@csshugs Are your sure?

**Comment by csshugs** [comment]
@dennisfrank No 😆 

I have to admit, I didn't had a thorough look at that. Basically was just presenting my thoughts there.

Long story short: If `overflow: hidden;` doesn't do anything right now, we can dump it now. If we should need it again in the future, we just add it again.

**Comment by nenadjelovac** [comment]
@csshugs I am really confused why it's there :S I thought about it, and can't figure out a reason. Maybe it's remnants of https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.crop.scss#L26, if it was a quick copy/paste when creating `o-ratio` :)

**Comment by florianbouvot** [comment]
I just forgot to remove it when I create the object in inuitcss ☺️

Years ago I work with a similar object but sometimes I use work like this 

```
<div class="o-ratio">
  <div class="o-ratio__content">
    <img src="path/to/img.png" alt="">
  </div>
</div>
```

**Comment by florianbouvot** [comment]
@dennisfrank thank you for your feedback 😉

**Comment by dennisfrank** [comment]
Haha, thank you guys! 😀

**Comment by aaronstezycki** [comment]
@florianbouvot Just realised that Line 109 has :
```
.o-ratio--img-contain {
  > .o-ratio__content:before {
```
... but I don't think you need the `:before` Psuedo class. 👍

**Comment by aaronstezycki** [comment]
@florianbouvot I've also tested the `.o-ratio--img-contain` and thought that certain images would be centered via the `margin: auto` declaration, but currently because ` .o-ratio__content` (on line 39) doesn't have `right: 0;` this doesn't work.

https://github.com/inuitcss/inuitcss/blob/34c93aad4d5a1b333c4eccdf66ac80f1fc35ec7d/objects/_objects.ratio.scss#L39-L49

Just seen these small hiccups, by comparing your original Codepen Demo: 
https://codepen.io/florianbouvot/pen/evrBem

Hope all this helps.

**Comment by florianbouvot** [comment]
@aaronstezycki Sorry for the response time. I fix the issues, thank you.
