### ISSUE TITLE
".o-flag__img > img" not working, when img wrapped in a-tag

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#311]
On an o-flag object, the image disappears, as soon as it is wrapped in another tag, in this case an a-tag:

```
<div class="o-flag__img">
      <a href="/">
           <img src="./assets/logo.png" alt="logo alt text">
      </a>
</div>
```

Is there any specific reason, why the img has to be accessed via the child selector (" > ")? Using it without child selector works as expected.

**Comment by herzinger** [comment]
The reason is simply selector performance. It's not that important, so I wouldn't complain much if it's decided to change it. That being said, HTML5 changed the `<a>` selector as to make it capable of encapsulating block level elements, which makes the following correct:

```html
<a href="/">
  <div class="o-flag__img">
    <img src="./assets/logo.png" alt="logo alt text">
  </div>
</a>
```

**Comment by anselmh** [comment]
I personally don’t think selector performance is a real, measurable issue here, so I’d say we can change this and probably should.

**Comment by nenadjelovac** [comment]
@herzinger 

>The reason is simply selector performance. 

The actual reason was not that, but this:

>The `>` needs to remain in order for nested flag objects to not inherit their parent’s formatting.

source: https://github.com/inuitcss/objects.flag/issues/7#issuecomment-62701457

Having said that, I've rarely (if ever) had this issue by using @herzinger's approach.

**Comment by rowild** [comment]
That makes a lot of sense! It would be helpful to clearly comment the source regarding that phenomenon.

**Comment by anselmh** [comment]
@rowild Tests depend on https://github.com/inuitcss/inuitcss/pull/320.

**Comment by herzinger** [comment]
oh, well though, I didn't remember the nesting problem. 

But yes, the anchor element became way more versatile in HTML5, becoming able to wrap block level elements.

**Comment by csshugs** [comment]
> Having said that, I've rarely (if ever) had this issue by using @herzinger's approach.

Me too. 

So can this be closed then?

**Comment by rowild** [comment]
As for me, yes, it can be closed. I take the liberty to do so.
