### ISSUE TITLE
centering content (within o-layout--center etc)

### ISSUE THREAD

**Issue by codemonkeynorth** [inuitcss/inuitcss#317]
Hi,

seems like an obvious question, but how do you generally approach centering content when using eg `o-layout--center` since the `o-layout__item` adds `text-align: left`

if i set alignment in the outer wrappers I think it causes the `o-layout` to be misaligned due to offset margin etc

given i need to repeat the pattern a lot would it be best to add eg a `o-layout__item--center` modifier?
(ie `.o-layout__item.o-layout__item--center { text-align: center }`)

have i missed something in the library?

thanks
J

```html
<section class="[ news section ] c-news">
    <div class="o-wrapper">
        <div class="o-layout o-layout--center">
   	    <div class="o-layout-item u-10/12"> <!-- this adds text-align: left -->
                <!-- do i really need to add a wrapper to 
                     every piece of content  to text-align: center -->
                <!--<div class="text--center">-->
                <h2 class="section__title">Latest News.</h2>
	        <span class="section__text">Lorem ipsum...</span>
                <!--</div>-->
  	    </div>
        </div>
    </div>
</section>
```

**Comment by codemonkeynorth** [comment]
just realised I sometimes need different text alignment at different breakpoints, so any modifiers would need @breakpoint versions as well... at which point it seems like the wrong approach.

**Comment by florianbouvot** [comment]
Hi @codemonkeynorth,

Centering your content isn't the role of the layout object. Layout object do one thing only and one thing well and it's better to keep layout away from components, so adding this kind of modifiers (.o-layout__item--center) is a nonsense for me.

I see two solutions: manage centering at components or utilities levels.

* Components example: adding an extra div `section__item` to manage centering

```
<section class="[ news section ] c-news">
  <div class="o-wrapper">
    <div class="o-layout o-layout--center">
      <div class="o-layout-item u-10/12">

        <div class="section__item">
          <h2 class="section__title">Latest News.</h2>
          <span class="section__text">Lorem ipsum...</span>
        </div>
        
      </div>
    </div>
  </div>
</section>
```

* Utilities example: create a `_utilities.text.scss` *(with responsive classes if needed)*

```
.u-text-center {
  text-align: center !important;
}

.u-text-center\@mobile {
  @include mq($from: mobile){
    text-align: center !important;
  }
}

[...]

.u-text-center\@wide {
  @include mq($from: mobile){
    text-align: center !important;
  }
}
```

To go further, you can read articles about OOCSS and Single Responsibility Principle...

**Comment by codemonkeynorth** [comment]
those were the approaches i was considering.. i was just wondering about the extra html as I also have multiple list items that then contain layout, that then need alignment control

but I don't see any other way round it really due to the nested layouts

I'll probably go for the first option.

was mainly looking to see if I'd missed anything obvious that already exists with inuit.

thanks again
J

**Comment by herzinger** [comment]
The first approach is the only correct one: grid system elements (`.o-layout`and `.o-layout__item` in inuitcss) should never receive cosmetic styling directly.

**Comment by florianbouvot** [comment]
@herzinger 

> The first approach is the only correct one

You are talking about the two solutions that I propose? If yes why second is not good?

**Comment by csshugs** [comment]
My 2 cents: 
It's difficult (i.e. impossible IMO) to cover such a general task like “centering elements” with an all-in-one framework object. 
So to answer your question @codemonkeynorth: You didn't miss anything in the framework—it's not there. And I would also advise against using the layout object for your purposes. As @florianbouvot and @herzinger pointed out correctly, the layout object is just a wrapper for the components that go in the layout items. What happens _inside_ the layout items shouldn't be the concern of the layout object anymore ([“Separation of Concerns”](https://cssguidelin.es/#the-separation-of-concerns) / [“Single Responsibility Principle”](https://cssguidelin.es/#the-single-responsibility-principle)).

Concerning the question of _what is_ the best solution to this problem is very much a matter of taste I think. But if you—like in your example above—already have a component class (`section__title`), why not just center that class?

```scss
.section__title {
  text-align: center;
}
```

**Comment by herzinger** [comment]
@florianbouvot  That's right.

You should never put cosmetic styling on grid elements, that's a basic rule for css grid-systems, and it's specially true for our layout object. Both `o-layout` and `o-layout__item` should be applied to dedicated containers, concerned only with the grid positioning and sizing. It's even the example @csswizardry chose to use in the [separation of concerns topic on his css guidelines](https://cssguidelin.es/#the-separation-of-concerns).

One reason is, as mentioned, the separation of concerns principle. It makes it more modular, decoupled, and encapsulated, as to ensure it wont be broken by later changes to the additional classes.

In our specific case, we use padding and relative positioning to create the grid, which makes the block structure of the element actually different from the visual one. Take a look a this little demo:

https://codepen.io/herzinger/pen/wqaWML

**Comment by codemonkeynorth** [comment]
@csshugs 
> But if you—like in your example above—already have a component class (section__title), why not just center that class?

ah sorry.. incomplete example.. everything is centred within that block (not just `.section__title`) so I think this is the correct approach to start with
`.section__item { text-align: center }`

it's just because that block is repeated over and over, and it being centred is down to its context not necessarily the component itself, i'd tried to do it higher up. (ie it might be left aligned when used elsewhere)

(I'm aware that `o-layout__item` contains margin/padding etc and shouldn't be used for visual so I can see where `text-align: center` on that would have essentially been wrong anyway).. 

thanks for the advice
J

**Comment by codemonkeynorth** [comment]
on a related side note, if grid layout objects shouldn't be styled, what is the correct approach to this please, if I need to style my `ul` or my `li` in this context? since I can't see how to separate the layout in that case.

```
<ul class="o-layout section__content c-detail-list">
    <li class="o-layout__item u-1/2@tablet u-1/3@desktop c-detail-list__item">
```

**Comment by herzinger** [comment]
Why are you using the layout object with a list? I don't really understand your use case. 
We have another object for inline lists: `o-list-inline`. To use it in conjunction with the layout object, you still should use dedicated containers, like so:

```scss
<div class="o-layout">

  <ul class="o-list-inline">
  
    <div class="o-layout__item u-1/3">
      <li class="o-list-inline__item view">
        1/3
      </li>
    </div>
  
    <div class="o-layout__item u-1/3">
      <li class="o-list-inline__item view">
        1/3
      </li>
    </div>
  
    <div class="o-layout__item u-1/3">
      <li class="o-list-inline__item view">
        1/3
      </li>
    </div>
  
  </ul>

</div>
```

I updated the [demo](https://codepen.io/herzinger/pen/wqaWML) to include a list.

**Comment by herzinger** [comment]
>it's just because that block is repeated over and over, and it being centred is down to its context not necessarily the component itself, i'd tried to do it higher up. (ie it might be left aligned when used elsewhere)

Create a modifier class for your component. That's the text book definition of an use case for component modifiers. You should add it at the highest level, something like:

```scss
.c-section--centered {
  .c-section__item { text-align: center; }
}
```

**Comment by codemonkeynorth** [comment]
sorry, i had not considered you could have items wrapping the <li> inside a <ul>. I was going to but assumed it was invalid HTML

>HTML 5:
>Content model: Zero or more li elements.

also new to this version of inuit, so not got through the full set of objects yet. some reading for me then!

thanks for both examples

regards
J

**Comment by codemonkeynorth** [comment]
I'm looking at @csswizardry's example on csswizardry.com...

```<div class="wrapper  wrapper--wide">
   <ul class="layout  layout--large">
     <li class="layout__item  desk-one-third">
```
but you're correct that there's no actual cosmetic styling on the `ul/li` themselves.

**Comment by herzinger** [comment]
Yes, no cosmetic styling. What I do and advise is to aways use containers, as it makes it easier to change things later on (specially if you're not the only one working on the project).

**Comment by codemonkeynorth** [comment]
Would you consider top/bottom margins as "cosmetic styling"? I guess the component should be self contained (`c-news-list`) and therefore a container/wrapper (`c-news`) should control the margins? 

```
<div class="c-news">
  <ul class="o-inline-list o-layout c-news-list">
    <li class="o-inline-list__item o-layout__item u-1/5">
     <div class="c-news-list__item">
       <h2 class="c-news-list__headline>Headline</h2>
```
```
.c-news { margin-top: 1em }
```

**Comment by herzinger** [comment]
That's a matter of preference, and the pros and cons are heavily context dependent. No right or wrong about it.

We got really off topic in this issue. I would suggest you close it, as the original question is solved. For additional troubleshooting of this kind, you should sign up to this [slack channel](https://herzinger.typeform.com/to/h6e3Km). I'm the one managing it, and there's some members of the core development team there too. I'll be glad to help with any other questions there.

**Comment by codemonkeynorth** [comment]
ah yes. i was working out how to get it back on topic! 

thanks for the advice.

closing.
