### ISSUE TITLE
Is "html {overflow-y: scroll;}" still needed?

### ISSUE THREAD

**Issue by erfanimani** [inuitcss/inuitcss#323]
Hi all,

I'm wondering what people think about removing the "always visible scrollbar" feature. Most browsers nowadays have semi-transparent auto-disappearing scrollbars that are overlaid on top of the page, and do not make the viewport smaller. As such I don't think this feature is needed any more.

Also, it sometimes clashes with (fixed) modal windows that add `overflow: hidden` to the body, and as such it can cause two scrollbars on the page (I can elaborate on this one if needed).

To clarify, this is the part that I'm questioning:

```
...
 * 2. Force scrollbars to always be visible to prevent awkward ‘jumps’ when
 *    navigating between pages that do/do not have enough content to produce
 *    scrollbars naturally.
...
html {
  ...
  overflow-y: scroll; /* [2] */
  min-height: 100%; /* [3] */
}
```

Source: https://github.com/inuitcss/inuitcss/blob/develop/elements/_elements.page.scss#L20

**Comment by rowild** [comment]
"Most browsers nowadays have semi-transparent auto-disappearing scrollbars" - Are you sure?
 Even on desktop? My Chrome and my Firefox and my Safari have regular, some 15px-18px wide scrollbars. Isn't that either a mobile browser phenomenon or a situation, where JS scrollers are used?

**Comment by erfanimani** [comment]
My bad - it's OS specific rather than browser specific. On OSX both Chrome and Firefox have scrollbars that overlay. On Android and iOS as well.

**Comment by herzinger** [comment]
I had a problem with jumping viewport in a existing project I was asked to refactor just this week, so I assure you it's still an issue. Also, the width for the scrollbars in modern browsers is consistently 17px, so there's that too. 

This is just trivia in the end. I believe this issue resolved itself, right?

**Comment by erfanimani** [comment]
All good - yep.
