### ISSUE TITLE
6.0.0-beta.5 seems to ignore SASS settings.global.scss for $inuit-spacing-properties

### ISSUE THREAD

**Issue by MelissaSnell** [inuitcss/inuitcss#327]
I pulled a local copy of a repository, where dependencies set to:

"dependencies": {
    "inuitcss": "^6.0.0-beta.4",
    "sass-mq": "^3.3.2"
  }

This means that 6.0.0-beta.5 was installed when I ran npm install. The original developer would have been on beta 4.

The src/sass/setttings/_settings.global.scss contains the following:

$inuit-spacing-properties: (
	'padding': 'p',
	'margin': 'm',
) !default;

This creates a shorthand for the padding and margin settings, so the HTML that was written has as a class "u-p0" and not "u-padding0" for example.

We are using grunt to compile src into dist. In the SASS main.scss the _settings.global.scss file comes before the inuit utilities spacings file:

@import "../../../node_modules/inuitcss/utilities/utilities.spacings";

I have looked at the Inuit file for utilities.spacings and "$inuit-spacing-properties" appears to match.

I needed to make a CSS change, but the CSS that is generated excludes the "shorthand" settings. I can see from the live site that these were created previously by the previous developer. This results in the layout being 'out of whack' because none of the margin and padding settings are working.

I am new to inuit, so I wasn't sure if this was a bug in the latest release, given that one of the things that had changed was the fact that utilities.spacings had been renamed from utilities.spacing? I'm not sure if this would have changed a namespace somewhere that would mean that this wouldn't be picked up?

Is there a new way that one is supposed to set/override Inuit variables?

I can roll back to the previous release to see if that resolves the issue.

**Comment by herzinger** [comment]
There are a few breaking changes between the two betas. I'm not 100% sure what the problem you are experiencing is, but provably it has to do with one of those.

**Comment by MelissaSnell** [comment]
Dear Henrique

Thanks for the reply.

I might try rolling back to beta 4 then. I will let you know if this resolves the issue.

**Comment by MelissaSnell** [comment]
Hi there.

Just to let you know that I rolled it back to beta-4 and the issue is resolved
