### ISSUE TITLE
Could you make non-fluid images with explicit width or height opt-in/-out

### ISSUE THREAD

**Issue by kkalvaa** [inuitcss/inuitcss#328]
In elements/_elements.images.scss the following is stated:
"If a `width` and/or `height` attribute have been explicitly defined, let’s not make the image fluid."
And then those images are made non-responsive.

I keep having to unset this whenever I use Inuit.css for WordPress themes as WordPress often explicitly sets a width and height of an image, yet those images should be responsive/fluid.

My proposal is to create a setting which would turn this on or off, rather than completely overwriting the rule.

**Comment by csshugs** [comment]
@inuitcss/core what do you think, is [this](https://github.com/inuitcss/inuitcss/commit/f047bfe42b3e1e8676cc49a3e20cfeb3ffee18c0) an acceptable approach to the use case described above? By making it `true` by default, we don't break anything, but provide a way to opt-out for such cases @kkalvaa has experienced. 

Another option would be to remove [the static images altogether again](https://github.com/inuitcss/inuitcss/blob/a243936606a3334be14bea7b3fbdc0db1b86f7cd/elements/_elements.images.scss#L20-L28).

**Comment by nenadjelovac** [comment]
@csshugs I'm ok with this approach.

**Comment by kkalvaa** [comment]
I think this would be a good solution, and exactly what I hoped for.

**Comment by csshugs** [comment]
#338 is merged, so closing this.
