### ISSUE TITLE
@elseif causing problems in _tools.font-size.scss

### ISSUE THREAD

**Issue by GarethOates** [inuitcss/inuitcss#331]
Error: This at-rule is not allowed here.
  } @else {
    ^^^^^^
  css/tools/_tools.font-size.scss 20:5  root stylesheet

I installed sass globally using yarn . `yarn global add sass`, then ran `sass ./css/main.scss` and got the error mentioned above.

I'm on a Mac running Sierra with the following versions:

sass: 1.0.0-beta.2 compiled with dart2js 1.24.2
node: v8.7.0
npm: 5.5.1

**Comment by GarethOates** [comment]
Apologies for the missing labels.  can't seem to add them now.

**Comment by plumpNation** [comment]
I can confirm this. `@elseif` not working for me either.

```
$boom: false;
$things: null;

@if $boom == true {
  $things: red;
} @elseif $boom == false {
  $things: blue;
}

.gazza-mc-jeggs {
  color: $things;
}
```

renders

`@elseif $boom == false {}`

I'm on Windows 10.

sass installed via npm global:
version: 1.0.0-beta.2 compiled with dart2js 1.24.2

When using sass through gulp-sass I have no issues with either `elseif` or `else if`.

With the official sass download 3.5.2, no problem with either `elseif` or `else if`.

**Comment by else** [comment]
I hate my username ;_;

**Comment by herzinger** [comment]
Any reason to be running SASS 1.0.0-beta.2 when the current stable release is 3.5.1?

**Comment by GarethOates** [comment]
No reason other than that's what came down when I did `yarn global add sass`.

**Comment by plumpNation** [comment]
There is no reason to use an outdated version of SASS I agree. However, the documentation seems to suggest `@else if` is the correct format.

Would it not be preferable to match the documented style that works on 'everything' (clearly I have not tested everything, only the installations mentioned above)?

**Comment by anselmh** [comment]
Sorry for the long wait. The current specification of Sass says that both variants [are valid syntax](https://github.com/sass/sass-spec/pull/306/files) now (wasn’t always the case, that’s why it fails in some parsers). However, I think it‘s worth changing the syntax to the format that’s used in the original documentation and is available in every Sass compliant parser.
