### ISSUE TITLE
Question about selector in _generic.normalize.scss

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#345]
In _generic.normalize.scss, starting at line 108, there is this CSS:
```
/**
 * 1. Remove the bottom border in Chrome 57- and Firefox 39-.
 * 2. Add the correct text decoration in Chrome, Edge, IE, Opera, and Safari.
 */

abbr[title] {
  border-bottom: none; /* 1 */
  text-decoration: underline; /* 2 */
  text-decoration: underline dotted; /* 2 */
}
```

What is the reason for having text-decoration defined twice, once with an additional attribute (dotted)? Any backwards compatibility issues I've never heard about?

In case there is a reason, it would be great to have it explained (as '*/ 3 /*'). If not, it maybe should be removed?

Thank you for your feedback!

**Comment by csshugs** [comment]
@rowild 
Please note that we just copy/paste this module from [normalize.css](https://github.com/necolas/normalize.css), so this is not _our_ code. Hence we will not change anything in that file.

Your question was dealt with [in a PR](https://github.com/necolas/normalize.css/pull/468) of the official repo, though.

**Comment by rowild** [comment]
Ah - I thought that was inuitcss's overwrite of normalize! My bad! Sorry and thank you for your feedback!
