### ISSUE TITLE
[objects.ratio] Using string as o-ratio modifier

### ISSUE THREAD

**Issue by xavianaxw** [inuitcss/inuitcss#346]
This thought arises when working on a project where the UI designer will state that a image in the hero section would have a ratio of `220:158`. This magic number will then transition into HTML where we will be typing in something like `o-ratio--220:158` for our image ratio.

By adding whole word modifier names for our ratios, one will be able to achieve something like `o-ratio--hero`. This also allows changes to the ratio to be done on the fly which makes code management a whole lot better imo!

Just a thought/suggestion anyway :)

**Comment by herzinger** [comment]
Well, this is basically what I've been saying in #276, so I agree.

**Comment by herzinger** [comment]
@csshugs @xavianaxw well, I made a [pen](https://codepen.io/herzinger/pen/NyjYLM) with my proposal, as I promissed in the PR #350. It's the simplest, and it let's you name your classes however you want to. If you say it's cool like this, I'll adjust it into our guidelines, adapt to crop as well and make a PR.

**Comment by csshugs** [comment]
@herzinger 
It's cool! Definitely a more elegant solution as #350. I'd love to see a PR for that.

**Comment by herzinger** [comment]
#352 is up for review :)"

**Comment by csshugs** [comment]
Good stuff @herzinger!

**Comment by xavianaxw** [comment]
Love your work @herzinger ! 👍

**Comment by herzinger** [comment]
@xavianaxw thanks, much appreciated :)"

**Comment by csshugs** [comment]
#352 has landed, so I close this issue. Thanks @xavianaxw for bringing this topic back to the table and thanks @herzinger for providing such an elegant solution! 👍
