### ISSUE TITLE
README.md example does not link to correct scss file

### ISSUE THREAD

**Issue by olivertappin** [inuitcss/inuitcss#347]
In the [README.md on line 167](https://github.com/inuitcss/inuitcss/blame/develop/README.md#L167), it shows:

```
@import "node_modules/inuitcss/objects/objects.tables";
```

when this should be singular:

```
@import "node_modules/inuitcss/objects/objects.table";
```

which can be confirmed here: https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.table.scss

A minor typo, but those who are copying/pasting the example to find out it doesn't work isn't the best user experience. Easy to fix.

**Comment by herzinger** [comment]
Thanks for the contribution, and for finding the mistake, but please, take a look at the [contributing guidelines](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md). Also, there is a long running issue for this kind of corrections [here](https://github.com/inuitcss/inuitcss/issues/21). You can make a pull request, or I'm certain someone in the core team could do it instead.

**Comment by csshugs** [comment]
#348 is merged.

Thanks @olivertappin for addressing this and taking care of it!
