### ISSUE TITLE
Documentation _utilities.responsive-spacings

### ISSUE THREAD

**Issue by yourownmood** [inuitcss/inuitcss#354]
Amazing work on the `6.0.0` release.
When applying the breaking changes on a project I'am working on i discovered "which looks like" a mistake in the documentation of `_utilities.responsive-spacings.scss`

**New documentation: 6.0.0**
![screen shot 2018-02-27 at 11 39 55](https://user-images.githubusercontent.com/4748789/36724325-2bedb5aa-1bb3-11e8-86d1-89b0d4e09dcc.png)

If applied like this it will result in `.u-marginbottom-small@...`

**What it should be:**
![screen shot 2018-02-27 at 11 40 28](https://user-images.githubusercontent.com/4748789/36724410-6a7ce4bc-1bb3-11e8-84f6-5bcd98a3248a.png)

which results is `.u-margin-bottom-small@...`

**Pull-request:**
https://github.com/inuitcss/inuitcss/pull/355

**Comment by csshugs** [comment]
@yourownmood Good catch!

**Comment by csshugs** [comment]
Resolved with #355. Thanks @yourownmood for spotting it and taking care of it!
