### ISSUE TITLE
[CircleCI] Update build script to 2.0

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#357]
[CircleCI announced](https://circleci.com/blog/sunsetting-1-0/) that 1.0 builds will not be available after August 31, 2018. To still be able to lint our stylesheets and run our unit tests, we should update straight away.

**Comment by yourownmood** [comment]
You have probably seen my pr #360 😉 
If there are any questions or improvements, let me know!

**Comment by yourownmood** [comment]
Support for CircleCI 1.0 ended on August 31, 2018

**Comment by florianbouvot** [comment]
@yourownmood thank you.
