### ISSUE TITLE
Question about use of margin-left vs padding-left for indentation of lists

### ISSUE THREAD

**Issue by monkeyhybrid** [inuitcss/inuitcss#364]
In `_generic.shared.scss`, lists are indented with a margin, as seen below:

```
dd, ol, ul {
  margin-left: $inuit-global-spacing-unit;
}
```

I realise this works perfectly well, but I was just wondering if there is a specific reason `margin-left` is used rather than `padding-left`?

The W3C's recommendations for default user-agent styles, and the actual default styles used by most (all?) browsers, [uses padding for the indenting](https://www.w3.org/TR/html5/rendering.html#section-lists). This leads me to think there may be some clever reasoning for opting for margin here? Or am I overthinking this?

**Comment by afontcu** [comment]
Hi! Didn't know about it, but the MDN docs state the following:

> "[...] In order to avoid this and get some indentation, there are really only three options available to browser implementors.
> 
> Give each `<li>` element a left margin.
> Give the `<ul>` element a left margin.
> Give the `<ul>` element some left padding.
> As it turns out, nobody seems to have used the first option. The second option was taken by Internet Explorer for Windows and Macintosh, and Opera. The third was adopted by Gecko, and by extension all the browsers that embed it."

and

> "In the end, we can see that none of the browsers mentioned in this article is right or wrong about how they lay out lists. They use different default styles, and that's where the problems creep in. By making sure you style both the left padding and left margin of lists, you can find much greater cross-browser consistency in your list indentation."

([source](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Consistent_list_indentation)).

So looks like there's no consensus about it, but the MDN suggest styling both margin and padding. That rule in `shared.scss` could use a `padding: 0`.

**Comment by monkeyhybrid** [comment]
Ah, nice find!

The `ul` does have `padding: 0` set on it in `_generic.reset.scss` so that should clear up any browser consistency issues.

So really, it seems it's just down to preference whether to use `margin-left` or `padding-left`. That's good to hear. I typically use `padding-left` but started questioning my reasons for doing so.

Thank you for the clarification. :)

**Comment by ArmorDarks** [comment]
Actually, there is a difference. Margins are always collapsing with floats, while paddings are not.

Try to put `margin-left` on the list and then put image with `float: left` next to it. Here what you will get:

![chrome_2018-05-31_20-31-08](https://user-images.githubusercontent.com/4460311/40797633-92fab43a-6511-11e8-9c2d-5859bcaf846c.png)

Paddings will collapse too, but that's fixable by putting `overflow: auto` on the list:

![chrome_2018-05-31_20-32-24](https://user-images.githubusercontent.com/4460311/40797686-c2acb020-6511-11e8-992f-171a7958e88e.png)


while in case of margin it won't help, because margin will keep collapsing with float:

![chrome_2018-05-31_20-32-59](https://user-images.githubusercontent.com/4460311/40797714-d628b7f2-6511-11e8-88eb-b7f818c8bbf2.png)

**Comment by monkeyhybrid** [comment]
Interesting! I hadn't considered margin collapsing in the choice between the two. Given no other reason not to, and with `overflow: auto` being a very simple 'fix' in this situation, I'll stick to using `padding-left` for now.

Is this something that be worth changing in inuitcss? Should I reopen the issue and/or submit a PR? I'm guessing if it's been used this way for a couple of years, it may be best to leave it be and let other users tweak if needed?

**Comment by herzinger** [comment]
Not only is the difference neglectable, it would be a potential breaking change. It doesn't mean we couldn't introduce it, but I don't think it's worth it.

**Comment by monkeyhybrid** [comment]
@herzinger I totally agree. I only raised the initial question because seeing it made me wonder if I was missing some deeper reasoning. I think it's such a minor difference, and so easy to override, it's not worth changing.

**Comment by ArmorDarks** [comment]
I can't say that difference is neglectable, as it comes to a massive difference when list placed next to the floating elements.

I'd query that change for the next major release, with a good explanation why it should be that way.
