### ISSUE TITLE
[RFC] CSS Grid Layout

### ISSUE THREAD

**Issue by zomars** [inuitcss/inuitcss#365]
With the rapid adoption of CSS grids, I've been meaning to ask the inuitcss team. 

What would be a reasonable approach for using CSS grids with inuitcss?

Would it be a component? An object? An utility?

Also since CSS grids benefit from nesting, what would be the recommended selectors?

I'm still trying to wrap my head around these concepts and would love to hear your thoughts on this.

Cheers!

**Comment by herzinger** [comment]
I don't get what you mean... Css grids are a pretty mainstream concept for about a decade, not some new thing being adopted now. Also, inuitcss has its own grid system built-in, in the form of the layout object.

**Comment by herzinger** [comment]
wait, I think I got it now.. You mean the CSS Grid Layout. Sorry there, had a brain fart.

Yeah, this stuff is pretty modular and reusable as is, I don't think there is any need to abstract it, you can just use it in your components as is. If you have enough regular grids that repeat themselves, I guess you could build one or more objects out of it, but in most cases it's just overkill, in my opinion. Either way, grids (complex ones, not the generic columns based ones we are familiar with) in general are particular to each project, so it makes sense to write them directly into your own project specific components, and there's not much value in having them in the framework.

**Comment by zomars** [comment]
I've been using recurrent grids as objects but I see what you mean. I think my question was more for a BEMIT standpoint rather than inuitcss'

**Comment by herzinger** [comment]
The answer is the same. If you want to use recurrent versions of the grid as objects, that's okay. I'll go as far as to say it's the proper level to put it, since it's a reusable abstraction. I personally don't see much reason, so I just use the grids as part of my components and that's it.

**Comment by zomars** [comment]
Thanks for the feedback, I've just wanted to open the topic for further discussion.
