### ISSUE TITLE
Ambiguous Rounding of line-height in browser breaks the vertical rhythm

### ISSUE THREAD

**Issue by JanaVanMaele** [inuitcss/inuitcss#367]
Generating my text styles via inuitss _tools.font-size.scss, I noticed that in my browser, chrome, the computed line-height is for example set to '20px', but if I hover the element with the inspector of the dev chromes, it shows me that it is '19px'.

In the core I defined my $inuit-global-baseline to 4px, so I assume that my vertical grid and all my generated line-heights should be divisible by 4, but if I put a vertical grid of 4px on top of my generated text styles, the generated line-heights do not match visual with the grid, even when the computed browser style says '20px', it is not showing as '20px' in the viewport, but showing as '19px'.

I added a decimal ceil to 2 digits to the calculation of the line-height. This solved the problem for me. But a more general solution should be appropriate?

**Comment by LayZeeDK** [comment]
What is your Sass `precision` parameter set to?

**Comment by herzinger** [comment]
Firstly, I would hardly call a 1px difference a "break" of the vertical rhythm. This is a known issue regarding rounding and precision. You can find the whole discussion through links in the pull request for this feature: https://github.com/inuitcss/inuitcss/pull/349

Your ceil solution, while it might work well for this particular case, will most likely generate a 1px higher value with some other inputs. I wouldn't be to fixed on that, but if you mind it, whenever this little discrepancy occurs or is most easily noticed in your layout, you can simply use the `$line-height` parameter of the mixin to set the desired value manually.

This mixin is the most efficient and precise I got at after fiddling with it a lot, bearing the limitations of the language and environment. You can also set a higher precision in your sass transpiler configurations to minimize it further.
