### ISSUE TITLE
Add viewport heights utility

### ISSUE THREAD

**Issue by ajshortt** [inuitcss/inuitcss#368]
My team and I are constantly using a custom `_utilities` class we wrote to size elements, typically sections or heroes, vertically based on viewport percentages.

Example usage: `u-vh-50` which would generate `height: 50vh`. An optional boolean is also included to turn on the generation of min heights too e.g. `u-vh-min-50` which adds `min-height: 50vh` obviously allowing the element to grow if required. 

The min-height option is very useful when you have clients who have the right intention for their site but then edit (via a CMS or something) one part of one page which "requires" a million words subsequently making the content overflow a `u-vh-50` classed container for example.  

Developers can add to the default heights list (`25`, `50`, `75` and `100`).  

The file has already been written so a PR will be submitted shortly. The utility has come in great use over the last year or so and would love to get peoples opinions on it.

Look forward to your thoughts.

**Comment by herzinger** [comment]
Can you provide an example of this? As it is I fail to see a reason for that, outside of some project specific circumstances, which  would make it not so suited for inclusion in the framework proper (although it would be a fine example of an optional add-on)

**Comment by ajshortt** [comment]
@herzinger Teamed with a few flex styles, you can create nice, whitespace ample layouts. Here is some mock markup:
```
<header class="u-vh-100">
    <!-- Full screen image hero section -->
</header>
<section class="u-vh-min-50">
    <!-- An intro section that might grow -->
</section>
<section class="u-vh-100">
    <!-- A large, whitespace section -->
</section>
<section class="u-vh-100">
    <!-- A large, whitespace section -->
</section>
<section class="u-vh-25">
    <!-- A banner (above footer) section -->
</section>
<footer></footer>
```

Mostly, the utility supports the need for whitespace in designs that might need to grow if the content exceeds the set viewport height.

**Comment by herzinger** [comment]
Okay, I can see how it could be useful in a very specific (and kinda popular) type of design. It's a little bit optionated, but yeah. Try and write up your implementation, trying to be as generic and flexible as possible, and let's have the core team decide if it should be included. I might chime in agian after the code is up.

**Comment by ajshortt** [comment]
@herzinger I don't have permission to add a branch. Is this something you can allow me to do?

**Comment by herzinger** [comment]
You should first fork the project, create a new branch _in your fork_ following the [contributing guidelines](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md), and then make a pull request from your branch into the branch **develop** of the main repository.

**Comment by florianbouvot** [comment]
@ajshortt thank you, your works looks good but we don't want ta add more and more utility (and create an utility library) in the current version.

I encourage you to do your own package to follow your needs.

**Comment by ajshortt** [comment]
Thanks @florianbouvot
