### ISSUE TITLE
[objects.flag|media] Use flexbox

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#379]
Flexbox makes centering easy so we only need one object. I propose to remove `objects.flag` and use flexbox in `objects.media`.

- Use flexbox in `objects.media`
- Add vertical alignement modifiers in `objects.media`
- Remove `objects.flag`

Thoughts ?

**Comment by csshugs** [comment]
This makes totally sense, yes.

**Comment by csshugs** [comment]
#383 is merged.
