### ISSUE TITLE
[generic.shared] Organize propriety

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#38]
I think it can be convenient if propriety from [`generic.shared`](https://github.com/inuitcss/inuitcss/blob/develop/generic/_generic.shared.scss#L13-L19) and [`generic.reset`](https://github.com/inuitcss/inuitcss/blob/develop/generic/_generic.reset.scss#L9-L16) can follow the same organisation. Any opinion ?

**Comment by csswizardry** [comment]
Do we still want to do this, @florianbouvot?

**Comment by florianbouvot** [comment]
I propose a reorder based on generic.reset but not perfect. What the best way to organize CSS properties: alphabetical order, type (e.g.: sections, grouping content, text-level semantics) ?

**Comment by csswizardry** [comment]
> While keeping in mind that this is not really important 😆.

Haha! With this in mind, please feel free to open a PR for something, but it’s not something I care too strongly about. If you don’t want to do anything, that’s cool—we can close this thread :)

**Comment by csshugs** [comment]
@florianbouvot 
I have no strong opinion about this either, so I guess it's a good idea to stick to the standard. I suspect this only concerns `generic.reset` and `generic.shared`. Do you mind to open a PR @florianbouvot or should I do it?

**Comment by florianbouvot** [comment]
@csshugs thank you for your opinion, I will open a PR in the morning 😉

**Comment by csshugs** [comment]
Perfect! 😄

**Comment by nenadjelovac** [comment]
@florianbouvot is this merged? Can we close it now?
