### ISSUE TITLE
Use CSS3 syntax

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#388]
Why not using CSS3 syntax in inuitcss v7:

- pseudo-element (`::after`, `::before`)

and maybe others.

Thoughts ?

**Comment by nenadjelovac** [comment]
👍

**Comment by florianbouvot** [comment]
@nenadjelovac Do you see other changes like this?

**Comment by csshugs** [comment]
I agree to use the double colon syntax everywhere. I’m not sure what else there is though.

**Comment by csshugs** [comment]
#401 is merged. Closing this.
