### ISSUE TITLE
Add flexbox utilities

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#394]
I propose to add some basic flexbox utilities with responsive variants to give more control on some objects/components.

Thoughts ?

**Comment by rowild** [comment]
..and there is already a wonderful "extension":
https://github.com/xavianaxw/inuitcss-flexbox

**Comment by LayZeeDK** [comment]
I like the [flex value aliases](https://github.com/angular/flex-layout/wiki/fxFlex-API#fxflex-options) in Angular Flex-Layout.

| Alias | Equivalent CSS |
|------|------------------|
| `grow` | `flex: 1 1 100%;` |
| `initial` | `flex: 0 1 auto;` |
| `auto` | `flex: <grow> <shrink> 100%;` |
| `none` | `flex: 0 0 auto;` |
| `nogrow` | `flex: 0 1 auto;` |
| `noshrink` | `flex: 1 0 auto;` |

**Comment by csshugs** [comment]
I truly believe that such utilities are needless. I do get the request for such utilities myself regularly in my projects, but in literally every case, it’s a desired behaviour that would be better handled in an object or a custom component.

If anyone could give me a suited use case for such a utility, I’m happy to reconsider my opinion, though.

**Comment by rowild** [comment]
@csshugs I am confused. Are you refering to all proposals here or just the Angular-related one?

If it is the latter case: Did you look at the inuitcss-flexbox? It is thought as a replacement for o-layout (using o-flex instead of o-layout), not a set of utilities...

**Comment by csshugs** [comment]
@rowild 
Sorry for the confusion. I was giving my opinion about the general proposal of this issue to provide basic flexbox utilities in inuitcss.

In other words: I’m against adding any flexbox utilities to inuitcss.

**Comment by rowild** [comment]
Thanks! 
But you are not against implementing flexbox, right?

**Comment by csshugs** [comment]
No. Where it brings us advantages (e.g. combining media- and flag-object etc.), it’s of course totally fine to use flexbox. I just think that there are no real use-cases for such flexbox-**utilities**.

**Comment by rowild** [comment]
I understand that to refer specifically to utilities. But the above mentioned "plugin" is actually and object that "redefeines" the layout object using flex. I consider that the proper approach. Would you rather prefer to leave the layout object as it is?

**Comment by csshugs** [comment]
> Would you rather prefer to leave the layout object as it is?

No. If we drop the support for older browsers, there is no reason not to change our current layout object and use flexbox, because it just makes things easier. 

But I was really just referring to the proposal of providing flexbox **utilities**.

**Comment by rowild** [comment]
...ok, after a while I read the header of this post again... all clear! And agreed.

**Comment by herzinger** [comment]
I also agree. More than that, I'm of the same opinion as @csshugs when it comes to utilities: the least the better. Also, as I have said in the more appropriate issue, my starting point for the new layout object would be the great https://github.com/nicoqh/inuit-flexgrid. I've been using it in my projects for a while now already.

**Comment by ArmorDarks** [comment]
I'm actually supporting the proposal to add flexbox utilities.

We've added [flexbox helpers](https://github.com/ArmorDarks/ekzo/blob/master/helpers/_flex.scss) a long time ago into our framework, and they prove to be extremely useful for quickly building complex UI. Though Ekzo is a more atomic framework, and that can be the reason why such utilities worked for us better.

**Comment by inlikealion** [comment]
@florianbouvot @csswizardry @csshugs Can we close this and mark as resolved? Seems consensus is to NOT add *utilities*, but to go ahead with the separate proposal of adding an object for flex layout as per #380.

**Comment by csshugs** [comment]
Like [stated in #396](https://github.com/inuitcss/inuitcss/issues/396#issuecomment-608324676), we won’t add such utilities to inuitcss.
