### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#397]
First of all, I'm sorry. This topic is not an issue entry.

I want to thank you all contributors and users of inuitcss.

This package and its idea is just great.

I find it even more beautiful every time, and that makes me very happy.

It's like watching a baby grow up and seeing him turn into a great person.

I hope I can keep seeing you guys all the time.

In short, thanks :)

**Comment by csshugs** [comment]
Thank **you** so much @hayatbiralem! This is a real motivator for us!

**Comment by hayatbiralem** [comment]
You guys deserve much much more. I hope someone could find a way for this.
