### ISSUE TITLE
PostCSS usage possible?

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#404]
I was wondering if it is possible to use a scss framework like this one in an postcss environment - and if so, how?
I am trying to get acquainted with webpack4 using the webpack-4-starter-kit, which uses pcss. (I've used webpack 3 and 4 already, but never postcss, which for some reason has been and seems to stay very successful in being totally ununderstandable for my little brains...)
Thanks for exchanging your thoughts!

**Comment by herzinger** [comment]
I don't know what to say... You can use it with postCSS (in fact, you should use it, or something similar), so the title question's answer is a simple "yes". Now the how, it's well... The same way you would use it for any sass project. The framework affects exactly nothing of the process.

**Comment by rowild** [comment]
This postCSS topic confused me because of the autoprefixer topic. I was of the assumption that SCSS is already taking care of that and therefore thought that postCSS is adding another such step, which isn't needed. I guess it just happens after many years of SCSS usage and a working gulp setup that one forgets the one or other detail :-)
Thanks for responding! Closing the issue.

**Comment by florianbouvot** [comment]
For years I work with Gulp and use `gulp-sass` for SCSS things and `gulp-postcss` + some plugins for optimisations (vendor prefix, minify, ...).

I think you can use a full PostCSS workflow and work with SASS via `postcss-node-sass`.

_You can take a look to [my Gulp setup](https://github.com/florianbouvot/aperitif)_

**Comment by rowild** [comment]
@florianbouvot Awesome! Thanks so much for sharing! I switched to webpack, but every once in a while a good gulp is just irreplaceable.

**Comment by herzinger** [comment]
I fucking hate gulp.

**Comment by rowild** [comment]
@herzinger Why? And what do you use as a taskmanager / module builder?

**Comment by herzinger** [comment]
There's nothing you would do with gulp or something similar that you can't do with pure npm scripts, which are faster and easier to maintain. If the project is complex enough that I need something, I use webpack.

**Comment by rowild** [comment]
Ah... well... you sounded so serious... :-)
