### ISSUE TITLE
General question about utility classes and mobile-first approach

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#406]
I would love to read your opinion about the following (which is most likely not new to you and probably was already discussed here somewhere - I did search, but not correctly it seems...)

In a recent question, posted here: https://github.com/inuitcss/inuitcss/issues/405, I tried to find out, how to restrict certain utility classes (mainly the u-padding and u-margin classes, to one state only - the state they describe after the @.

For me, this problem made me aware of the question: why do these utility classes follow the mobile-first principle anyway?

As per definition, utility classes are defined as helper classes, which do one thing and one thing only, and should only be used rarely and in specific cases.
The current behaviour, though, creates a "waterfall", so-to-say: If I need to use, e.g., `u-margin-bottom@mobile` for the mobile state, but would like to leave tablet and desktop state untouched, I subsequently must also use `u-margin-bottom-none@tablet` (which cancels the previous behaviour again). (This happens to me quite often in grid systems, where an element must provide some distance to another element that suddenly jumped to the second row...)

This seems contradictory, since the utility class should only affect the situation for which it is intended.
I did write my own (non scss, but simply css) helper classes, at least for the paddings and margins, in the style of `[]@tablet-only` to restrict the behaviour to their respective state, and it turned out that there is a lot less need for adding classes to the html to control layout over the breakpoints.

My questions would be:
1. Is there anywhere such a discussion going on? (or has been?) A link would be most appreciated!
2. Since ITCSS is all about reducing css, would that be something worthwhile to rethink again for v7?

Currently, to me it seems that sticking to the principle alone - which is "mobile-first" - is in some cases counter productive.

What is your experience? Your opinion? Your thoughts? Any chance for a bit of discussion here? Looking forward to your feedbacks!

**Comment by rowild** [comment]
nobody?

**Comment by florianbouvot** [comment]
@rowild sorry, I will give you my opinion soon (not enough time now).

**Comment by herzinger** [comment]
My opinion on this is based on my own experience designing and developing on the wild. If I came across a situation similar to the one you described (in which I had to reset a property for the next breakpoint) five or so times in my entire career, it's more than I remember. But let's think about it:

> 1. Is there anywhere such a discussion going on? (or has been?) A link would be most appreciated!

Not that I'm aware, no.

> 2. Since ITCSS is all about reducing css, would that be something worthwhile to rethink again for v7?

Your approach doesn't reduce css at all. It can, in some edge cases, reduce the amount of classes you add in your html, but that's all. The framework generated css is slightly more, since the media-queries are more complex. Also, in cases where the next breakpoint should inherit the same styles (also known as "most cases"), you would actually have to put down more classes. I fail to see how that would help. I guess if you write your own css for the most common style variation in the set, and use the utilities to adjust the outliners, it might be okay (maybe?), but if you're going that far, don't use utilities, write the whole logic yourself on the actual css. Using utilities like this nets no benefits, it's just lazy.

**Comment by rowild** [comment]
@herzinger You almost never have the situation, where you needed to clear a `u-margin-bottom-small@mobile`-like class? Like a one-col-footer that turns into a 3-col on desktop?

Maybe an example helps for discussion (usual abbreviations: "mb" = "margin-bottom", n = none, m = mobile, d = desktop...):

```html
<div class="[ c-footer ] o-layout  u-margin-bottom">
  <div class="o-layout__item  u-1/1@m  1/3@d  u-mb@m u-mbn@d">...</div>
  <div class="o-layout__item  u-1/1@m  1/3@d  u-mb@m u-mbn@d">...</div>
  <div class="o-layout__item  u-1/1@m  1/3@d">...</div>
</div>
<div class="[ c-copyright ]">...</div>
```

This example demonstrates that the 3 columns need a bottom margin when they are in mobile state, which must not be there, when in desktop state, because the surrounding div takes care of the regular distance. To achieve that, the margin of mobile state needs to be cleared, since it is not something that should be inherited by the next state (for the sake of conversation I skip "tablet").

In my projects, this is a very common scenario, especially with something like equal-height flex-boxes (think of backgrounds). A need for separate components for each 3-col section is not necessary, it is just that: an often-used 3-col component.
How do you approach such a scenario? 

Usage of utilities like in the given example does not seem to be "lazy", but concise with "u-1/1" etc. and very much the inuitcss-way to go. But I'm happy to be proven wrong.

As for a reducing the size of the generated CSS: There are less classes to be used in the html, right, but my approach also reduces the generated CSS, because there is no need for "***-none" classes. Also, the ordering becomes not so much a factor. The current inuitcss does not allow to write this:
`u-mb@mobile u-mbn`, 
, but instead must be written like this: 
`u-mb@mobile u-mbn@desktop`
, where `u-mbn` === `u-mbn@desktop`.
which, to me, seems to be the only reason, why there has to be a "***-none" class.

Right?

Wrong?

:-)

**Comment by herzinger** [comment]
Okay, lets go with your example. First of all, I rarely ever use `@mobile` classes. Those are mostly for little hard to do adjustments for mobile only, and even then only if you can't avoid it. In mobile-first, the mobile layout is the norm. Also, what I call lazy is using utilities everywhere just to not have to write css. So I would write this code something like this:

```html
<footer class="c-footer  o-layout  u-margin-bottom">
  <section class="c-footer__col  o-layout__item  1/3@d">...</div>
  <section class="c-footer__col  o-layout__item  1/3@d">...</div>
  <section class="c-footer__col  o-layout__item  1/3@d">...</div>
</footer>
<div class="[ c-copyright ]">...</div>
```

```scss
.c-footer__col {
  margin-bottom: $global-spacing-unit;

  &:last-child { margin-bottom: 0; }

  @include mq($from: desktop) {
    margin-bottom: 0;
  }
}
```

**Comment by florianbouvot** [comment]
Unlike @herzinger, I use a lot of utilities in some project _(and I like that)_ but I agree with him about mobile first approach.

I tried the "one state only" some years ago but I need to add lot of class to inherit style. 
So I prefer to inherit by default and reset when needed (simple for my mind).

About you example, for basic use case I'ill only remove the bottom margin on `c-footer` and I think it will works the same, no ?

```
<footer class="c-footer  o-layout">
  <section class="c-footer__col  o-layout__item  u-1/3@d  u-mb">...</div>
  <section class="c-footer__col  o-layout__item  u-1/3@d  u-mb">...</div>
  <section class="c-footer__col  o-layout__item  u-1/3@d. u-mb">...</div>
</footer>
<div class="c-copyright">...</div>
```

For complex use case I'ill use a `u-mbn@d` to reset style.

**Comment by rowild** [comment]
Great feedback here! Thank you so much for taking the time!!!

@herzinger 
> I rarely ever use @mobile classes. Those are mostly for little hard to do adjustments for mobile only [...]

You say `mobile only` - which is not the case with those classes discussed here. They are not mobile-only, instead, they affect every breakpoint.
To me it seems, that, what you are saying here, is actually just one more reason, why responsive utility classes should be constrained to the breakpoint they are intended for. Currently, fixing a problem in mobile just has the consequence that tablet and desktop need adjustments ('clearing'), too.

What would be a "counter example" that prooves my assumption wrong?

@herzinger Your trick is a very elegant one! I am wondering now, if my example was probably a bit too much simplified... :-)
I also like to use utility classes, not for the reason of being lazy (or am I?), but for keeping myself from writing more CSS than need be.

**Comment by rowild** [comment]
I guess there will not be anymore feedback on this topic here. I therefore close this issue.
