### ISSUE TITLE
Question: o-ratio has no overflow: hidden - why?

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#407]
It's the first time that I use `.o-ratio`. What a great idea you had here - awesome!!! Congrats!

Is there a reason, why the `.o-ratio` does not have an `overflow:hidden` attribute? In my test, I put a 16:9 image into a 16:10 frame. The result: the complete image ist shown. My expectation was that the image gets cropped, though...

(I know: I can always write my own objects. But I would just like to know, what the reason behind this decision was - if there was on at all.)

Thank you!

EDIT:
I did something wrong in my code. Everything is working fine. Sorry!
Closing this issue again.

**Comment by herzinger** [comment]
The behavior you are expecting is what the crop object exists for, not the ratio one. Crop object crops the content, ratio enforces aspect ratio only.

**Comment by rowild** [comment]
Got it! Thanks for the clarification!

**Comment by florianbouvot** [comment]
For performance reasons, I think crop of images must be done with another tools 😉
But ratio with lazy loading looks good to "reserve" space.

**Comment by rowild** [comment]
@florianbouvot I prepared my scissors already... ;-)
