### ISSUE TITLE
[generic.normalize] Use npm dependency

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#415]
Instead of copy/pasting the source code of normalize.css, we could just as well reference the npm package.

We already discussed this in the past, but dismissed it because Ruby Sass is not capable of `@import`ing regular CSS files. However, [it seems like Ruby Sass is now officially deprecated](https://sass-lang.com/ruby-sass), so I think it’s safe for us to go that route now.

**Comment by csshugs** [comment]
#417 is merged.

**Comment by davidbwaters** [comment]
If SCSS were still desirable, it could be renamed with a post-install command.
