### ISSUE TITLE
doubt in the code, about the layout. how to split the columns.

### ISSUE THREAD

**Issue by leitemaximiano** [inuitcss/inuitcss#422]
I read this article [Building better grid systems](https://csswizardry.com/2011/08/building-better-grid-systems/). And I didn't find the answer to my question in it

I'm studying the code. I'm in doubt where this class came from (`u-1/2`).
```css
/*
*   <div class="o-layout">
 *     <div class="o-layout__item  u-1/2">
 *     </div>
 *     <div class="o-layout__item  u-1/2">
 *     </div>
 *   </div>
*/
```

I didn't find that for example.
```css
.u-1\/3{
  /* commands */
}
```

Can someone help me?

**Comment by csshugs** [comment]
@maximanoLeite 
These classes are generated automatically in [`_utilities.widths.scss`](https://github.com/inuitcss/inuitcss/blob/a1314e6b2f413ba162237967e905a3a7de137e85/utilities/_utilities.widths.scss).

You can define, which classes are generated via the [`$inuit-fractions` list](https://github.com/inuitcss/inuitcss/blob/a1314e6b2f413ba162237967e905a3a7de137e85/utilities/_utilities.widths.scss#L43). E.g., if you redefine the variable like this:

```scss
$inuit-fractions: 1 2 !default;
```

In this case, only the classes `.u-1/1` and `.u-1/2` are generated. When you extend the list like this:

```scss
$inuit-fractions: 1 2 3 4 !default;
```

the following classes are generated:

* `.u-1/1`
* `.u-1/2`
* `.u-1/3`, `.u-2/3`
* `.u-1/4`, `.u-2/4`, `.u-3/4`

Hope, that answers your question.
