### ISSUE TITLE
Add the 'wrapper' object to example file in the readme.

### ISSUE THREAD

**Issue by davidbwaters** [inuitcss/inuitcss#424]
Hi, the readme is missing the import line
 `@import "node_modules/inuitcss/objects/objects.wrapper";`

**Comment by csshugs** [comment]
The example in the `README.md` isn’t supposed to be used as a boilerplate manifest file for new projects. As a matter of fact, we don’t want to encourage users to `@import` just all of it and go with it and maybe never use half of the imported framework partials. If you really need a boilerplate for a manifest file, there is the `example.main.scss` that is supposed for exactly that, [as documented in the `README.md`](https://github.com/inuitcss/inuitcss/blob/436cf77923d9787bfd6eb277cbf44b82d43179be/README.md#examplemainscss) as well.
