### ISSUE TITLE
Question: Is this project still usable in 2021?

### ISSUE THREAD

**Issue by atrevino89** [inuitcss/inuitcss#431]
Hi guys, super noob here

We're migrating an app from old AngularJs to Vue and we're changing some pieces of CSS and its structure so I was told to use iniuitcss as our most experienced developer really likes it. I see that there have been no changes this year and gives me the impression of 1) is super mature and is not needed or 2) probably there was a decision to not keep working on it, which brings me to the question described in the title of this post, is this project useful in 2021 so people can invest some time learning the way of working of inuitcss or is it better to look for different options?

**Comment by herzinger** [comment]
It is mostly inactive for a while now, but still quite usable. The methodology behind inuitcss is still the one I use and recommend, even if what I personally use is somewhat updated with some more modern css. One of the strengths of this project is how modular it is, after all.
