### ISSUE TITLE
[utilities.clearfix] Use !important

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#55]
`@mixin inuit-clearfix($important: false) {` propose a `$important` option, why not using it for `utilities.clearfix`?

**Comment by florianbouvot** [comment]
@inuitcss/core I reopen this issue and add same option as font-size mixin. If it's not necessary, to complex... please close the issue 😉

**Comment by csshugs** [comment]
> If it's not necessary and to complex... please close the issue

I think it's too complex and unnecessary. [The way it is at the moment](https://github.com/inuitcss/inuitcss/blob/87b603e3b60e6d20f9c0a91cd2558f12ff0b298d/tools/_tools.mixins.scss#L82-L84) does it it, IMO.

([Related](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md#simplicity-is-paramount))
