### ISSUE TITLE
We need to talk about responsive…

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/inuitcss#80]
I’m having some thoughts about RWD…

I want to leave breakpoint management to a dedicated tool, rather than trying to implement something myself—there are tools out there that

* people are already familiar with;
* do a better job than I could;
* I don’t have to maintain.

I like the idea of letting people use their favourite breakpoint/MQ/RWD library alongside inuitcss—I like freedom of choice—but I also have some reservations.

* **Is it making it more difficult for people, rather than easier?** Is it too much to expect them to choose a CSS framework (inuitcss, yay!) _and_ a RWD library?
* **Is it weird having a framework in 2016 that doesn’t do responsive by default?** Would people be put off using/choosing inuitcss because it doesn’t do responsive for them? inuitcss’ grid is fantastic, and a lot of people choose inuitcss _because_ of its RWD grid. Would people be more likely to choose something else because of a lack of native RWD support?

The only options as I see them:

1. Encourage people to adopt their own BP management library and get them to integrate that with how they want to use inuitcss?
2. Make [Sass MQ](https://github.com/sass-mq/sass-mq)* an official dependency of inuitcss, and ship the framework with that?

\* I really like Sass MQ, and I think it does its job _really_ well. I wouldn’t want to write my own version of it for inuitcss, and I can’t think of a library I’d rather use.

What does anyone think; Option 1, Option 2, or another option that I haven’t thought of?

- - -

cc. @kaelig

**Comment by florianbouvot** [comment]
I think that inuitcss must provide a way to work with responsive *without making it mandatory*.

> Is it making it more difficult for people, rather than easier? Is it too much to expect them to choose a CSS framework (inuitcss, yay!) and a RWD library?

It depends on the target audience (beginner, expert, freelance, agency, large team...) but for a part of them I think so.

> Is it weird having a framework in 2016 that doesn’t do responsive by default? Would people be put off using/choosing inuitcss because it doesn’t do responsive for them? inuitcss’ grid is fantastic, and a lot of people choose inuitcss because of its RWD grid. Would people be more likely to choose something else because of a lack of native RWD support?

YES, inuitcss will become least attractive...

**Comment by kaelig** [comment]
The spectrum of use cases for dealing with RWD is so broad that my reason would tend towards option 1.

For example, PostCSS allows interesting [things with Custom Media Queries](https://github.com/sass-mq/sass-mq/issues/84) that mimic the future of the spec and for this reason, it'd be a shame to limit people's choices to a Sass mixin in particular.

Of course, Sass MQ is definitely something I would personally use whenever I have the choice but I wouldn't force it onto anyone's stack.

**Comment by florianbouvot** [comment]
@kaelig don't you think that it can keep people back from using inuitcss?

I think inuitcss can propose a solution without imposing it.

**Comment by kaelig** [comment]
Good point, if a default solution such as Sass MQ is not deeply rooted in inuitcss and users still have a choice… that could be a sensible proposition!

**Comment by florianbouvot** [comment]
@kaelig exactly a default solution which is not mandatory and documentation to move further...

I worked 1 year with Sass MQ before inuitcss include a responsive solution. I tried [Include-media](http://include-media.com) and [Sass Custom Media Queries](https://gist.github.com/fvsch/dff0aab899f5573ea859) his last months.

Sass MQ is flexible, powerful and widely used : a good default solution *almost to complete for my needs* (bravo @kaelig 😄).

**Comment by csswizardry** [comment]
Cool. Give this a 👍  if I should make a branch experimenting with Sass MQ as a default dependency :)

cc. @inuitcss/core, @kaelig

**Comment by florianbouvot** [comment]
@csswizardry did you need help ?

**Comment by csswizardry** [comment]
@florianbouvot: No, I can take an hour this afternoon to spike it; I just want to get general feedback about whether I should do it or not :)

**Comment by csswizardry** [comment]
@inuitcss/core: Can people checkout `tkt-0080` and have a play around? :)

**Comment by csshugs** [comment]
I like this approach of having a default media-query tool like Sass MQ, but would like it even more if the tool would not be baked in into the framework that much.

I can think of a solution like in pre-alpha: Split normal widths and responsive-widths into separate files, so that the user can either take Sass MQ out of the box (importing both widths files), or just not importing the responsive widths file and take another tool that fits her needs.

Another solution would be putting the Sass MQ section in `utilities.widths` behind a flag (which is true by default), so the user can opt-out of Sass MQ by disabling the flag.

**Comment by csswizardry** [comment]
@csshugs: I really think the framework needs RWD by default, and I think the best way to add it is Sass MQ. It’s a pretty invisible addition that won’t have negative impact, and the small amount of users that want to use something else can do so quite easily.

In short: I want to officially use Sass MQ as the default (see `tkt-0080`), and provide instructions for using something different in the docs.

What does @inuitcss/core think?
