### ISSUE TITLE
[settings.global] What should this file do?

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/inuitcss#83]
I was thinking about this yesterday, and after [@nenadjelovac’s comment](https://github.com/inuitcss/inuitcss/pull/82#discussion_r71079404) today, I’m wondering what to do with this file. Current problems:

* It does contain design related things right now, which we should get rid of, because…
* It isn’t an `example.` file, so users aren’t encouraged to duplicate it and modify it.
* If we remove design stuff, it just has core settings in it.
* So we could just reduce the file’s scope.

Solutions:

* Make it an `example.` files and encourage users to add more of their own globals to is.
* Remove the design stuff and rename the file `_settings.core.css` and limit its scope just to spacing units etc.

**Comment by nenadjelovac** [comment]
>Remove the design stuff and rename the file` _settings.core.css` and limit its scope just to spacing units etc.

My vote is for this option. It is more clear for the end user in terms of what to do with the file, what it is, what it is for etc. It is kinda "instructional" and educational, which is, IMO, a good thing (for this situation). We could (and probably should) include an `_example.settings.global.scss` to show an example of what globals settings could/should look like and where it fits compared to other settings files.

**Comment by florianbouvot** [comment]
I completely agree with @nenadjelovac 😉.
