### ISSUE TITLE
[objects.layout] Missing minus sign

### ISSUE THREAD

**Issue by johannes-r** [inuitcss/inuitcss#84]
Hi,

thank you guys so much for the awesome work on this project.

I was just playing around with the latest version of the develop branch and I might have spotted a tiny (but tedious) mistake in `_objects.layout.scss`.

[Line 136](https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.layout.scss#L136) is missing a minus in front of `$inuit-global-spacing-unit-small;` which causes the grid to "break" if the `--small` modifier is used.

**Comment by florianbouvot** [comment]
@johannes-r thank you 😉

**Comment by johannes-r** [comment]
Wow, that was quick - I'm glad I could help 😊

**Comment by florianbouvot** [comment]
Merged.
