### ISSUE TITLE
Remove opinionated UI specifics

### ISSUE THREAD

**Issue by anselmh** [inuitcss/inuitcss#86]
In https://github.com/inuitcss/inuitcss/pull/82/files#r71230546 we concluded that we want to remove opinionated UI specifics from inuitcss since it’s not thought as UI framework.

This affects, for example, `border-radius` or `transition`.

**Comment by csswizardry** [comment]
Closing as work already started: https://github.com/inuitcss/inuitcss/commit/5d30f2db728dcbd19b388eed5983809e5f2be8b0
