### ISSUE TITLE
[tools.functions] `inuit-halve` function still needed?

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#92]
Sorry in advance if I missed it anywhere but did we ever/do we need the `inuit-halve` function? The function is not called anywhere in the framework and also seems a bit opinionated anyway, because it just halves a value (rather than also provides modifiers to quarter/double/quadruple values).

EDIT:
https://github.com/inuitcss/inuitcss/blob/b158becc1c703656de2065f1741f6040bf0e4f64/tools/_tools.functions.scss#L16-L19

**Comment by csswizardry** [comment]
This entire file needs some thought. I’m going over it in my mind a lot of the moment :)

**Comment by nenadjelovac** [comment]
I'd go with removing it now (since it's not used anywhere) so we have a clear base, and add anything we think is needed at a later point.

**Comment by csshugs** [comment]
@nenadjelovac Agree.

Let's come back to this when/if #118 gets merged, so we just need to remove the file.

**Comment by csswizardry** [comment]
I deleted `halve()` in #118.

**Comment by nenadjelovac** [comment]
@csshugs can we close this?
