### ISSUE TITLE
[objects.wrapper] Do the sizing variants make sense?

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#93]
From a design perspective, does it makes sense to have [multiple modifiers](https://github.com/inuitcss/inuitcss/blob/b158becc1c703656de2065f1741f6040bf0e4f64/objects/_objects.wrapper.scss#L31-L49) which effectively create different width wrapper container?

![wrapper-objects-modifier](https://cloud.githubusercontent.com/assets/4582857/17058833/7b37d95a-5022-11e6-9178-af37d16cded0.png)

Isn't the purpose of such a wrapper to unify the design an the horizontal axis?

**Comment by csswizardry** [comment]
It’s only like having different sized gutters in our layout system… we might want different content to be further from edges of containers than others.

**Comment by csshugs** [comment]
And when you look at the screenshot, the naming is a bit misleading. `.o-wrapper--tiny` is much wider as `.o-wrapper--huge`.

I now that the naming refers to the padding rather than the width, but as I said: It could be misleading.

**Comment by csshugs** [comment]
> It’s only like having different sized gutters in our layout system… we might want different content to be further from edges of containers than others.

I would do that and always did with the box object.

**Comment by csshugs** [comment]
> I would do that and always did with the box object.

Example:

![wrapper-objects-modifier-with-box](https://cloud.githubusercontent.com/assets/4582857/17059083/c8d9d004-5023-11e6-810d-d37e0ef2ec7a.png)

**Comment by csswizardry** [comment]
`o-wrapper` is only tasked with doing _x_ paddings, so I guess you could continue to use `o-box` and others (like me) can use the `o-wrapper`.

I don’t think there’s anything wrong or broken with the current `o-wrapper` implementation—I’m happy keeping size variants for altering sizes of gutter :)

**Comment by csshugs** [comment]
> I don’t think there’s anything wrong or broken with the current o-wrapper implementation

Correct. 
I just didn't see the use case you just described.

Leads me to the question why I never did it that way 😞 
Anyway. Closing this quite depressed.

**Comment by florianbouvot** [comment]
> From a design perspective, does it makes sense to have multiple modifiers which effectively create different width wrapper container?

IMO size modifier are not needed. I prefer a simple `o-wrapper` and add `max-width` modifier to follow specific design needs ;)

**Comment by csshugs** [comment]
@florianbouvot 
Reopen the issue?

**Comment by florianbouvot** [comment]
@csshugs size variants are not a problem.

But in real project I think I use two king of modifier:

Responsive
```
.o-wrapper--responsive {
  @media screen and (max-width: 720px) {
    padding-left: $inuit-global-spacing-unit-factor-small;
    padding-right: $inuit-global-spacing-unit-factor-small;
  }
}
```

Content width (I use component or utility classes)
```
.c-text-limit {
  max-width: 33rem;
}

// or 

.u-mw-33 {
  max-width: 33rem;
}
```

**Comment by csshugs** [comment]
@florianbouvot 
Ok, but I think we all share the opinion that these two modifiers (responsive and max-width) would be two opinionated for inuitcss, or do you propose to integrate them?

**Comment by florianbouvot** [comment]
@csshugs fully agree

**Comment by csshugs** [comment]
> I just share my opinion cause it can give new idea...

That's good, don't stop doing that. Always helps to know how everyone else handles such things.

**Comment by zomars** [comment]
Actually you read my mind with this @csshugs, I always reuse the wrapper modifiers to alter the max-width instead of the gutter, maybe it's just me but a `o-wrapper--small` tells me that it's a smaller/narrower wrapper than the default one. My version ends up looking this this:
```css
.o-wrapper--small {
  max-width: $inuit-wrapper-width / 1.5;
}
.o-wrapper--tiny {
  max-width: $inuit-wrapper-width / 2;
}
```

An so on...
