### ISSUE TITLE
Port over objects.tables

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/inuitcss#97]

**Comment by florianbouvot** [comment]
LGTM, what about [this modifiers](https://github.com/inuitcss/objects.tables/blob/master/_objects.tables.scss#L116-L194)? Better at component level?

**Comment by csswizardry** [comment]
@florianbouvot: Yeah, I think it’s approaching design territory.

**Comment by florianbouvot** [comment]
@csswizardry I agree

**Comment by florianbouvot** [comment]
@csswizardry PR ?

**Comment by csshugs** [comment]
@inuitcss/core 
Concerns anyone? Can I open a PR?

**Comment by florianbouvot** [comment]
@csshugs yes, you can submit a PR.
