### ISSUE TITLE
Port over objects.pack

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/inuitcss#98]

**Comment by florianbouvot** [comment]
LGTM.

**Comment by csshugs** [comment]
@inuitcss/core 
Concerns anyone? Approved for PR?

**Comment by florianbouvot** [comment]
@csshugs same here, ok for PR.

**Comment by florianbouvot** [comment]
```
.o-pack {
  ...
  margin-left: 0;
  ...
}
```

Why `margin-left: 0;`?

**Comment by csshugs** [comment]
@florianbouvot 

> Why margin-left: 0;?

I think it is to be able to use `.o-pack` on an `<ul>` element.

**Comment by csswizardry** [comment]
@csshugs is correct 👍

**Comment by csshugs** [comment]
💪

**Comment by csshugs** [comment]
#123 is merged.
