### ISSUE TITLE
[utilities.widths] Misleading comment about spoken-word format

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/inuitcss#99]
>Classes can take a fraction-like format (e.g. `.u-2/3`) or a **spoken-word format (e.g. `.u-2-of-3`)**.

Spoken-word format is no longer supported (as per https://github.com/inuitcss/inuitcss/blob/develop/tools/_tools.widths.scss). So this [comment section](https://github.com/inuitcss/inuitcss/blob/3ec70a833d739090e30b6c7b9529a7e1fa652937/utilities/_utilities.widths.scss#L12) should need some update :)

**Comment by florianbouvot** [comment]
Good point, you can may be submit a PR?

**Comment by csshugs** [comment]
@nenadjelovac @florianbouvot 

I already [fixed that](https://github.com/inuitcss/inuitcss/blob/tkt-0021/utilities/_utilities.widths.scss) in #21.

Just isn't merged in yet.

**Comment by nenadjelovac** [comment]
@csshugs oh, nice. Closing the issue then ;)
